// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eventbus.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const InsertOutbox = `-- name: InsertOutbox :one

INSERT INTO eventbus.outbox (
    event_id, event_type, schema_version, tenant_id, market_id, account_id, seq, account_seq,
    subject, headers, payload, occurred_at, correlation_id, causation_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id
`

type InsertOutboxParams struct {
	EventID       string
	EventType     string
	SchemaVersion int32
	TenantID      string
	MarketID      *string
	AccountID     *string
	Seq           *int64
	AccountSeq    *int64
	Subject       string
	Headers       []byte
	Payload       []byte
	OccurredAt    time.Time
	CorrelationID *string
	CausationID   *string
}

// Event bus queries: the outbox (producers INSERT in their own transaction,
// the relay reads and stamps published_at) and consumer idempotency.
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, InsertOutbox,
		arg.EventID,
		arg.EventType,
		arg.SchemaVersion,
		arg.TenantID,
		arg.MarketID,
		arg.AccountID,
		arg.Seq,
		arg.AccountSeq,
		arg.Subject,
		arg.Headers,
		arg.Payload,
		arg.OccurredAt,
		arg.CorrelationID,
		arg.CausationID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ListOutboxByAccountSince = `-- name: ListOutboxByAccountSince :many
SELECT id, event_id, event_type, schema_version, tenant_id, market_id, account_id, seq, account_seq, subject, headers, payload, occurred_at, correlation_id, causation_id, published_at FROM eventbus.outbox
WHERE tenant_id = $1 AND account_id = $2 AND account_seq > $3
ORDER BY account_seq
LIMIT $4
`

type ListOutboxByAccountSinceParams struct {
	TenantID   string
	AccountID  *string
	AccountSeq *int64
	Limit      int32
}

// Private-stream resume: every event of one account after account_seq.
func (q *Queries) ListOutboxByAccountSince(ctx context.Context, arg ListOutboxByAccountSinceParams) ([]EventbusOutbox, error) {
	rows, err := q.db.Query(ctx, ListOutboxByAccountSince,
		arg.TenantID,
		arg.AccountID,
		arg.AccountSeq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventbusOutbox{}
	for rows.Next() {
		var i EventbusOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.SchemaVersion,
			&i.TenantID,
			&i.MarketID,
			&i.AccountID,
			&i.Seq,
			&i.AccountSeq,
			&i.Subject,
			&i.Headers,
			&i.Payload,
			&i.OccurredAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOutboxByMarket = `-- name: ListOutboxByMarket :many
SELECT id, event_id, event_type, schema_version, tenant_id, market_id, account_id, seq, account_seq, subject, headers, payload, occurred_at, correlation_id, causation_id, published_at FROM eventbus.outbox
WHERE tenant_id = $1 AND market_id = $2
ORDER BY id
LIMIT $3 OFFSET $4
`

type ListOutboxByMarketParams struct {
	TenantID string
	MarketID *string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListOutboxByMarket(ctx context.Context, arg ListOutboxByMarketParams) ([]EventbusOutbox, error) {
	rows, err := q.db.Query(ctx, ListOutboxByMarket,
		arg.TenantID,
		arg.MarketID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventbusOutbox{}
	for rows.Next() {
		var i EventbusOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.SchemaVersion,
			&i.TenantID,
			&i.MarketID,
			&i.AccountID,
			&i.Seq,
			&i.AccountSeq,
			&i.Subject,
			&i.Headers,
			&i.Payload,
			&i.OccurredAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnpublished = `-- name: ListUnpublished :many
SELECT id, event_id, event_type, schema_version, tenant_id, market_id, account_id, seq, account_seq, subject, headers, payload, occurred_at, correlation_id, causation_id, published_at FROM eventbus.outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
`

func (q *Queries) ListUnpublished(ctx context.Context, limit int32) ([]EventbusOutbox, error) {
	rows, err := q.db.Query(ctx, ListUnpublished, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventbusOutbox{}
	for rows.Next() {
		var i EventbusOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.SchemaVersion,
			&i.TenantID,
			&i.MarketID,
			&i.AccountID,
			&i.Seq,
			&i.AccountSeq,
			&i.Subject,
			&i.Headers,
			&i.Payload,
			&i.OccurredAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkProcessed = `-- name: MarkProcessed :execrows
INSERT INTO eventbus.processed_events (consumer, event_id)
VALUES ($1, $2)
ON CONFLICT (consumer, event_id) DO NOTHING
`

type MarkProcessedParams struct {
	Consumer string
	EventID  string
}

// 0 rows affected means the consumer already processed this event.
func (q *Queries) MarkProcessed(ctx context.Context, arg MarkProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, MarkProcessed, arg.Consumer, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const MarkPublished = `-- name: MarkPublished :exec
UPDATE eventbus.outbox SET published_at = now() WHERE id = ANY($1::bigint[]) AND published_at IS NULL
`

func (q *Queries) MarkPublished(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, MarkPublished, dollar_1)
	return err
}

const OutboxBacklog = `-- name: OutboxBacklog :one
SELECT count(*)::bigint AS backlog,
       COALESCE(EXTRACT(EPOCH FROM (now() - min(occurred_at))), 0)::double precision AS oldest_age_seconds
  FROM eventbus.outbox
 WHERE published_at IS NULL
`

type OutboxBacklogRow struct {
	Backlog          int64
	OldestAgeSeconds float64
}

func (q *Queries) OutboxBacklog(ctx context.Context) (OutboxBacklogRow, error) {
	row := q.db.QueryRow(ctx, OutboxBacklog)
	var i OutboxBacklogRow
	err := row.Scan(&i.Backlog, &i.OldestAgeSeconds)
	return i, err
}

const PruneOutbox = `-- name: PruneOutbox :execrows

DELETE FROM eventbus.outbox o
 WHERE o.id IN (SELECT i.id FROM eventbus.outbox i
                 WHERE i.published_at IS NOT NULL AND i.published_at < $1
                 ORDER BY i.id LIMIT $2)
`

type PruneOutboxParams struct {
	PublishedAt pgtype.Timestamptz
	Limit       int32
}

// Retention (docs/plan-v1.0.md §7.3: the outbox is kept 30 days) --------
// The worker role's retention loop calls these with a cutoff and a batch
// size until a call deletes fewer rows than the batch.
// Published rows older than the cutoff; unpublished rows are never touched
// (the relay still owes them to JetStream). Old rows have the lowest ids,
// so walking the primary key finds them without a new index.
func (q *Queries) PruneOutbox(ctx context.Context, arg PruneOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, PruneOutbox, arg.PublishedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const PruneProcessedEvents = `-- name: PruneProcessedEvents :execrows
DELETE FROM eventbus.processed_events p
 WHERE (p.consumer, p.event_id) IN (SELECT i.consumer, i.event_id FROM eventbus.processed_events i
                                     WHERE i.processed_at < $1 LIMIT $2)
`

type PruneProcessedEventsParams struct {
	ProcessedAt time.Time
	Limit       int32
}

func (q *Queries) PruneProcessedEvents(ctx context.Context, arg PruneProcessedEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, PruneProcessedEvents, arg.ProcessedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
