// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventbusOutbox struct {
	ID            int64
	EventID       string
	EventType     string
	SchemaVersion int32
	TenantID      string
	MarketID      *string
	AccountID     *string
	Seq           *int64
	AccountSeq    *int64
	Subject       string
	Headers       []byte
	Payload       []byte
	OccurredAt    time.Time
	CorrelationID *string
	CausationID   *string
	PublishedAt   pgtype.Timestamptz
}
