// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM auth.users WHERE tenant_id = $1 AND role = 'admin' AND status = 'active'
`

// Freezing the last one would lock everybody out of the back office.
func (q *Queries) CountActiveAdmins(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM auth.users WHERE tenant_id = $1 AND role = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one


INSERT INTO auth.users (tenant_id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, email, password_hash, role, kyc_level, status, totp_secret_enc, totp_enabled, version, created_at, updated_at, totp_failures, totp_locked_until, totp_last_step
`

type CreateUserParams struct {
	TenantID     string
	Email        string
	PasswordHash string
	Role         string
}

// Auth queries (api role writes users, refresh tokens and API keys; admin
// edits users). Schema-qualified.
// Users ------------------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycLevel,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpFailures,
		&i.TotpLockedUntil,
		&i.TotpLastStep,
	)
	return i, err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE auth.users
   SET totp_enabled = true, totp_failures = 0, totp_locked_until = NULL, totp_last_step = $2
 WHERE id = $1
`

type EnableTOTPParams struct {
	ID           string
	TotpLastStep *int64
}

func (q *Queries) EnableTOTP(ctx context.Context, arg EnableTOTPParams) error {
	_, err := q.db.Exec(ctx, enableTOTP, arg.ID, arg.TotpLastStep)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, tenant_id, user_id, key_id, secret_enc, label, scopes, ip_allowlist, created_at, last_used_at, revoked_at FROM auth.api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id string) (AuthApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i AuthApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.KeyID,
		&i.SecretEnc,
		&i.Label,
		&i.Scopes,
		&i.IpAllowlist,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByKeyID = `-- name: GetAPIKeyByKeyID :one
SELECT id, tenant_id, user_id, key_id, secret_enc, label, scopes, ip_allowlist, created_at, last_used_at, revoked_at FROM auth.api_keys WHERE key_id = $1
`

func (q *Queries) GetAPIKeyByKeyID(ctx context.Context, keyID string) (AuthApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByKeyID, keyID)
	var i AuthApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.KeyID,
		&i.SecretEnc,
		&i.Label,
		&i.Scopes,
		&i.IpAllowlist,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminSessionByHash = `-- name: GetAdminSessionByHash :one
SELECT id_hash, tenant_id, user_id, created_at, expires_at, totp_verified_at, last_seen_at, revoked_at, ip FROM auth.admin_sessions WHERE id_hash = $1
`

func (q *Queries) GetAdminSessionByHash(ctx context.Context, idHash []byte) (AuthAdminSession, error) {
	row := q.db.QueryRow(ctx, getAdminSessionByHash, idHash)
	var i AuthAdminSession
	err := row.Scan(
		&i.IDHash,
		&i.TenantID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TotpVerifiedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.Ip,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, tenant_id, user_id, token_hash, expires_at, created_at, revoked_at, replaced_by FROM auth.refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, email, password_hash, role, kyc_level, status, totp_secret_enc, totp_enabled, version, created_at, updated_at, totp_failures, totp_locked_until, totp_last_step FROM auth.users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycLevel,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpFailures,
		&i.TotpLockedUntil,
		&i.TotpLastStep,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, role, kyc_level, status, totp_secret_enc, totp_enabled, version, created_at, updated_at, totp_failures, totp_locked_until, totp_last_step FROM auth.users WHERE tenant_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	TenantID string
	Email    string
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycLevel,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpFailures,
		&i.TotpLockedUntil,
		&i.TotpLastStep,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one

INSERT INTO auth.api_keys (tenant_id, user_id, key_id, secret_enc, label, scopes, ip_allowlist)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, user_id, key_id, secret_enc, label, scopes, ip_allowlist, created_at, last_used_at, revoked_at
`

type InsertAPIKeyParams struct {
	TenantID    string
	UserID      string
	KeyID       string
	SecretEnc   []byte
	Label       string
	Scopes      []string
	IpAllowlist []string
}

// API keys -------------------------------------------------------------------
func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (AuthApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.TenantID,
		arg.UserID,
		arg.KeyID,
		arg.SecretEnc,
		arg.Label,
		arg.Scopes,
		arg.IpAllowlist,
	)
	var i AuthApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.KeyID,
		&i.SecretEnc,
		&i.Label,
		&i.Scopes,
		&i.IpAllowlist,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAdminSession = `-- name: InsertAdminSession :one

INSERT INTO auth.admin_sessions (id_hash, tenant_id, user_id, expires_at, totp_verified_at, ip)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id_hash, tenant_id, user_id, created_at, expires_at, totp_verified_at, last_seen_at, revoked_at, ip
`

type InsertAdminSessionParams struct {
	IDHash         []byte
	TenantID       string
	UserID         string
	ExpiresAt      time.Time
	TotpVerifiedAt pgtype.Timestamptz
	Ip             string
}

// Admin sessions (0018) ----------------------------------------------------
func (q *Queries) InsertAdminSession(ctx context.Context, arg InsertAdminSessionParams) (AuthAdminSession, error) {
	row := q.db.QueryRow(ctx, insertAdminSession,
		arg.IDHash,
		arg.TenantID,
		arg.UserID,
		arg.ExpiresAt,
		arg.TotpVerifiedAt,
		arg.Ip,
	)
	var i AuthAdminSession
	err := row.Scan(
		&i.IDHash,
		&i.TenantID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TotpVerifiedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.Ip,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one

INSERT INTO auth.refresh_tokens (tenant_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, token_hash, expires_at, created_at, revoked_at, replaced_by
`

type InsertRefreshTokenParams struct {
	TenantID  string
	UserID    string
	TokenHash []byte
	ExpiresAt time.Time
}

// Refresh tokens -----------------------------------------------------------
func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const listAPIKeySecretsForUpdate = `-- name: ListAPIKeySecretsForUpdate :many

SELECT id, secret_enc FROM auth.api_keys WHERE tenant_id = $1 ORDER BY created_at, id FOR UPDATE
`

type ListAPIKeySecretsForUpdateRow struct {
	ID        string
	SecretEnc []byte
}

// Rewrap under a rotated master key (exchange keys rewrap): every sealed
// secret of the tenant, locked so a concurrent create or enrol waits.
func (q *Queries) ListAPIKeySecretsForUpdate(ctx context.Context, tenantID string) ([]ListAPIKeySecretsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeySecretsForUpdate, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeySecretsForUpdateRow{}
	for rows.Next() {
		var i ListAPIKeySecretsForUpdateRow
		if err := rows.Scan(&i.ID, &i.SecretEnc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, tenant_id, user_id, key_id, secret_enc, label, scopes, ip_allowlist, created_at, last_used_at, revoked_at FROM auth.api_keys WHERE user_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]AuthApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthApiKey{}
	for rows.Next() {
		var i AuthApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.KeyID,
			&i.SecretEnc,
			&i.Label,
			&i.Scopes,
			&i.IpAllowlist,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTOTPSecretsForUpdate = `-- name: ListTOTPSecretsForUpdate :many
SELECT id, totp_secret_enc FROM auth.users WHERE tenant_id = $1 AND totp_secret_enc IS NOT NULL ORDER BY created_at, id FOR UPDATE
`

type ListTOTPSecretsForUpdateRow struct {
	ID            string
	TotpSecretEnc []byte
}

func (q *Queries) ListTOTPSecretsForUpdate(ctx context.Context, tenantID string) ([]ListTOTPSecretsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listTOTPSecretsForUpdate, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTOTPSecretsForUpdateRow{}
	for rows.Next() {
		var i ListTOTPSecretsForUpdateRow
		if err := rows.Scan(&i.ID, &i.TotpSecretEnc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, password_hash, role, kyc_level, status, totp_secret_enc, totp_enabled, version, created_at, updated_at, totp_failures, totp_locked_until, totp_last_step FROM auth.users
WHERE tenant_id = $1
  AND ($4::text = '' OR position($4::text IN email) > 0)
  AND ($5::text = '' OR status = $5::text)
  AND ($6::text = '' OR role = $6::text)
ORDER BY created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	TenantID string
	Limit    int32
	Offset   int32
	Email    string
	Status   string
	Role     string
}

// The operator's directory view. position() rather than LIKE so an email
// fragment cannot carry wildcards.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]AuthUser, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Email,
		arg.Status,
		arg.Role,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthUser{}
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.KycLevel,
			&i.Status,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotpFailures,
			&i.TotpLockedUntil,
			&i.TotpLastStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTOTPFailure = `-- name: RecordTOTPFailure :one
UPDATE auth.users
   SET totp_failures = totp_failures + 1,
       totp_locked_until = CASE WHEN totp_failures + 1 >= $2::int
                                THEN $3::timestamptz
                                ELSE totp_locked_until END
 WHERE id = $1
RETURNING totp_failures, totp_locked_until
`

type RecordTOTPFailureParams struct {
	ID          string
	MaxFailures int32
	LockUntil   time.Time
}

type RecordTOTPFailureRow struct {
	TotpFailures    int32
	TotpLockedUntil pgtype.Timestamptz
}

// Locks when this failure reaches the limit. The lock time is computed by the
// caller so tests can drive the clock.
func (q *Queries) RecordTOTPFailure(ctx context.Context, arg RecordTOTPFailureParams) (RecordTOTPFailureRow, error) {
	row := q.db.QueryRow(ctx, recordTOTPFailure, arg.ID, arg.MaxFailures, arg.LockUntil)
	var i RecordTOTPFailureRow
	err := row.Scan(&i.TotpFailures, &i.TotpLockedUntil)
	return i, err
}

const recordTOTPSuccess = `-- name: RecordTOTPSuccess :exec
UPDATE auth.users SET totp_failures = 0, totp_locked_until = NULL, totp_last_step = $2 WHERE id = $1
`

type RecordTOTPSuccessParams struct {
	ID           string
	TotpLastStep *int64
}

func (q *Queries) RecordTOTPSuccess(ctx context.Context, arg RecordTOTPSuccessParams) error {
	_, err := q.db.Exec(ctx, recordTOTPSuccess, arg.ID, arg.TotpLastStep)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE auth.api_keys SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID     string
	UserID string
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAdminSession = `-- name: RevokeAdminSession :execrows
UPDATE auth.admin_sessions SET revoked_at = now() WHERE id_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAdminSession(ctx context.Context, idHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAdminSession, idHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE auth.refresh_tokens
   SET revoked_at = now(), replaced_by = $2
 WHERE id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID         string
	ReplacedBy *string
}

// Marks a token used/revoked; 0 rows means it was already gone (reuse attempt).
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.ReplacedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserAdminSessions = `-- name: RevokeUserAdminSessions :execrows
UPDATE auth.admin_sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserAdminSessions(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserAdminSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :execrows
UPDATE auth.refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAPIKeySecretEnc = `-- name: SetAPIKeySecretEnc :exec
UPDATE auth.api_keys SET secret_enc = $2 WHERE id = $1
`

type SetAPIKeySecretEncParams struct {
	ID        string
	SecretEnc []byte
}

func (q *Queries) SetAPIKeySecretEnc(ctx context.Context, arg SetAPIKeySecretEncParams) error {
	_, err := q.db.Exec(ctx, setAPIKeySecretEnc, arg.ID, arg.SecretEnc)
	return err
}

const setPendingTOTPSecret = `-- name: SetPendingTOTPSecret :exec

UPDATE auth.users
   SET totp_secret_enc = $2, totp_enabled = false,
       totp_failures = 0, totp_locked_until = NULL, totp_last_step = NULL
 WHERE id = $1
`

type SetPendingTOTPSecretParams struct {
	ID            string
	TotpSecretEnc []byte
}

// TOTP (0007 columns + 0018 bookkeeping) -------------------------------------
// None of these bump version / updated_at: a failed code is not an edit of
// the user, and a counter that rewrote the row's version would make every
// optimistic check elsewhere see phantom changes.
func (q *Queries) SetPendingTOTPSecret(ctx context.Context, arg SetPendingTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setPendingTOTPSecret, arg.ID, arg.TotpSecretEnc)
	return err
}

const setTOTPSecretEnc = `-- name: SetTOTPSecretEnc :exec
UPDATE auth.users SET totp_secret_enc = $2 WHERE id = $1
`

type SetTOTPSecretEncParams struct {
	ID            string
	TotpSecretEnc []byte
}

func (q *Queries) SetTOTPSecretEnc(ctx context.Context, arg SetTOTPSecretEncParams) error {
	_, err := q.db.Exec(ctx, setTOTPSecretEnc, arg.ID, arg.TotpSecretEnc)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE auth.api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}

const touchAdminSession = `-- name: TouchAdminSession :exec
UPDATE auth.admin_sessions SET last_seen_at = now() WHERE id_hash = $1
`

func (q *Queries) TouchAdminSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, touchAdminSession, idHash)
	return err
}

const updateUserKYCLevel = `-- name: UpdateUserKYCLevel :one
UPDATE auth.users SET kyc_level = $2, version = version + 1, updated_at = now() WHERE id = $1 RETURNING id, tenant_id, email, password_hash, role, kyc_level, status, totp_secret_enc, totp_enabled, version, created_at, updated_at, totp_failures, totp_locked_until, totp_last_step
`

type UpdateUserKYCLevelParams struct {
	ID       string
	KycLevel int16
}

func (q *Queries) UpdateUserKYCLevel(ctx context.Context, arg UpdateUserKYCLevelParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserKYCLevel, arg.ID, arg.KycLevel)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycLevel,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpFailures,
		&i.TotpLockedUntil,
		&i.TotpLastStep,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE auth.users SET password_hash = $2, version = version + 1, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE auth.users SET status = $2, version = version + 1, updated_at = now() WHERE id = $1 RETURNING id, tenant_id, email, password_hash, role, kyc_level, status, totp_secret_enc, totp_enabled, version, created_at, updated_at, totp_failures, totp_locked_until, totp_last_step
`

type UpdateUserStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycLevel,
		&i.Status,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpFailures,
		&i.TotpLockedUntil,
		&i.TotpLastStep,
	)
	return i, err
}
