// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthAdminSession struct {
	IDHash         []byte
	TenantID       string
	UserID         string
	CreatedAt      time.Time
	ExpiresAt      time.Time
	TotpVerifiedAt pgtype.Timestamptz
	LastSeenAt     time.Time
	RevokedAt      pgtype.Timestamptz
	Ip             string
}

type AuthApiKey struct {
	ID          string
	TenantID    string
	UserID      string
	KeyID       string
	SecretEnc   []byte
	Label       string
	Scopes      []string
	IpAllowlist []string
	CreatedAt   time.Time
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type AuthRefreshToken struct {
	ID         string
	TenantID   string
	UserID     string
	TokenHash  []byte
	ExpiresAt  time.Time
	CreatedAt  time.Time
	RevokedAt  pgtype.Timestamptz
	ReplacedBy *string
}

type AuthUser struct {
	ID              string
	TenantID        string
	Email           string
	PasswordHash    string
	Role            string
	KycLevel        int16
	Status          string
	TotpSecretEnc   []byte
	TotpEnabled     bool
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	TotpFailures    int32
	TotpLockedUntil pgtype.Timestamptz
	TotpLastStep    *int64
}
