// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: breaks.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountOpenLedgerBreaks = `-- name: CountOpenLedgerBreaks :one
SELECT count(*) FROM admin.ledger_breaks WHERE tenant_id = $1 AND resolved_at IS NULL
`

func (q *Queries) CountOpenLedgerBreaks(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, CountOpenLedgerBreaks, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const InsertLedgerBreak = `-- name: InsertLedgerBreak :one
INSERT INTO admin.ledger_breaks (tenant_id, asset, debits, credits, diff, detected_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, asset, debits, credits, diff, detected_at, resolved_at
`

type InsertLedgerBreakParams struct {
	TenantID   string
	Asset      string
	Debits     pgtype.Numeric
	Credits    pgtype.Numeric
	Diff       pgtype.Numeric
	DetectedAt time.Time
}

func (q *Queries) InsertLedgerBreak(ctx context.Context, arg InsertLedgerBreakParams) (AdminLedgerBreak, error) {
	row := q.db.QueryRow(ctx, InsertLedgerBreak,
		arg.TenantID,
		arg.Asset,
		arg.Debits,
		arg.Credits,
		arg.Diff,
		arg.DetectedAt,
	)
	var i AdminLedgerBreak
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Asset,
		&i.Debits,
		&i.Credits,
		&i.Diff,
		&i.DetectedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const ListLedgerBreaks = `-- name: ListLedgerBreaks :many
SELECT id, tenant_id, asset, debits, credits, diff, detected_at, resolved_at FROM admin.ledger_breaks WHERE tenant_id = $1 ORDER BY detected_at DESC, asset LIMIT $2 OFFSET $3
`

type ListLedgerBreaksParams struct {
	TenantID string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListLedgerBreaks(ctx context.Context, arg ListLedgerBreaksParams) ([]AdminLedgerBreak, error) {
	rows, err := q.db.Query(ctx, ListLedgerBreaks, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminLedgerBreak{}
	for rows.Next() {
		var i AdminLedgerBreak
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Asset,
			&i.Debits,
			&i.Credits,
			&i.Diff,
			&i.DetectedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOpenLedgerBreaks = `-- name: ListOpenLedgerBreaks :many

SELECT id, tenant_id, asset, debits, credits, diff, detected_at, resolved_at FROM admin.ledger_breaks WHERE tenant_id = $1 AND resolved_at IS NULL ORDER BY asset
`

// admin.ledger_breaks (0019): the ledger's own reconciliation. Owned by the
// ledger package because the invariant it records -- debits equal credits per
// asset -- is the ledger's, even though the table sits in the admin schema
// next to the chain reconciliation it complements.
func (q *Queries) ListOpenLedgerBreaks(ctx context.Context, tenantID string) ([]AdminLedgerBreak, error) {
	rows, err := q.db.Query(ctx, ListOpenLedgerBreaks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminLedgerBreak{}
	for rows.Next() {
		var i AdminLedgerBreak
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Asset,
			&i.Debits,
			&i.Credits,
			&i.Diff,
			&i.DetectedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ResolveLedgerBreak = `-- name: ResolveLedgerBreak :execrows
UPDATE admin.ledger_breaks SET resolved_at = $2 WHERE id = $1 AND resolved_at IS NULL
`

type ResolveLedgerBreakParams struct {
	ID         string
	ResolvedAt pgtype.Timestamptz
}

func (q *Queries) ResolveLedgerBreak(ctx context.Context, arg ResolveLedgerBreakParams) (int64, error) {
	result, err := q.db.Exec(ctx, ResolveLedgerBreak, arg.ID, arg.ResolvedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
