// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminLedgerBreak struct {
	ID         string
	TenantID   string
	Asset      string
	Debits     pgtype.Numeric
	Credits    pgtype.Numeric
	Diff       pgtype.Numeric
	DetectedAt time.Time
	ResolvedAt pgtype.Timestamptz
}

type LedgerAccount struct {
	ID          string
	TenantID    string
	Kind        string
	HouseCode   *string
	OwnerUserID *string
	Status      string
	NextSeq     int64
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type LedgerBalance struct {
	AccountID string
	Asset     string
	Available pgtype.Numeric
	Hold      pgtype.Numeric
	Version   int64
	UpdatedAt time.Time
}

type LedgerJournalEntry struct {
	ID             int64
	TenantID       string
	IdempotencyKey string
	Kind           string
	RefType        *string
	RefID          *string
	Reason         *string
	CorrelationID  *string
	CreatedAt      time.Time
}

type LedgerPosting struct {
	ID        int64
	EntryID   int64
	AccountID string
	Asset     string
	Bucket    string
	Direction string
	Amount    pgtype.Numeric
}
