// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposits.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDepositReversals = `-- name: ClaimDepositReversals :many
SELECT id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at FROM chain.deposits
WHERE tenant_id = $1 AND status = 'credited' AND reversal_requested_at IS NOT NULL
ORDER BY reversal_requested_at
LIMIT $2
`

type ClaimDepositReversalsParams struct {
	TenantID string
	Limit    int32
}

// What the chain role should reverse on this tick.
func (q *Queries) ClaimDepositReversals(ctx context.Context, arg ClaimDepositReversalsParams) ([]ChainDeposit, error) {
	rows, err := q.db.Query(ctx, claimDepositReversals, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainDeposit{}
	for rows.Next() {
		var i ChainDeposit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.Address,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.BlockNumber,
			&i.BlockHash,
			&i.Confirmations,
			&i.Status,
			&i.OrphanedAtBlock,
			&i.CreditedAt,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Fee,
			&i.CreditedAmount,
			&i.ReorgedAtBlock,
			&i.ReversalRequestedBy,
			&i.ReversalRequestedAt,
			&i.ReversalNote,
			&i.ReversalError,
			&i.ReversedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDepositsAwaitingReversal = `-- name: CountDepositsAwaitingReversal :one
SELECT count(*) FROM chain.deposits
WHERE tenant_id = $1 AND status = 'credited' AND reorged_at_block IS NOT NULL
`

// Everything that has been stamped and not yet reversed, whether or not a
// person has decided about it. The gauge behind DepositAwaitingReversal: this
// number being anything but zero means an account holds a balance the chain
// does not back.
func (q *Queries) CountDepositsAwaitingReversal(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDepositsAwaitingReversal, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDepositsByStatus = `-- name: CountDepositsByStatus :many
SELECT asset, status, count(*) AS total
FROM chain.deposits
WHERE tenant_id = $1 AND chain_id = $2
GROUP BY asset, status
`

type CountDepositsByStatusParams struct {
	TenantID string
	ChainID  int64
}

type CountDepositsByStatusRow struct {
	Asset  string
	Status string
	Total  int64
}

// Backs deposits_total{asset,status} without keeping a counter in memory
// across restarts.
func (q *Queries) CountDepositsByStatus(ctx context.Context, arg CountDepositsByStatusParams) ([]CountDepositsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDepositsByStatus, arg.TenantID, arg.ChainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDepositsByStatusRow{}
	for rows.Next() {
		var i CountDepositsByStatusRow
		if err := rows.Scan(&i.Asset, &i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDepositsInStatus = `-- name: CountDepositsInStatus :one
SELECT count(*) FROM chain.deposits
WHERE tenant_id = $1 AND status = ANY($2::text[])
`

type CountDepositsInStatusParams struct {
	TenantID string
	Statuses []string
}

// The dashboard's "deposits still confirming" tile.
func (q *Queries) CountDepositsInStatus(ctx context.Context, arg CountDepositsInStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDepositsInStatus, arg.TenantID, arg.Statuses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBlocksFrom = `-- name: DeleteBlocksFrom :execrows
DELETE FROM chain.blocks WHERE tenant_id = $1 AND chain_id = $2 AND number >= $3
`

type DeleteBlocksFromParams struct {
	TenantID string
	ChainID  int64
	Number   int64
}

// Drops the abandoned branch when the cursor rewinds.
func (q *Queries) DeleteBlocksFrom(ctx context.Context, arg DeleteBlocksFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlocksFrom, arg.TenantID, arg.ChainID, arg.Number)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlock = `-- name: GetBlock :one
SELECT tenant_id, chain_id, number, hash, parent_hash, seen_at FROM chain.blocks WHERE tenant_id = $1 AND chain_id = $2 AND number = $3
`

type GetBlockParams struct {
	TenantID string
	ChainID  int64
	Number   int64
}

func (q *Queries) GetBlock(ctx context.Context, arg GetBlockParams) (ChainBlock, error) {
	row := q.db.QueryRow(ctx, getBlock, arg.TenantID, arg.ChainID, arg.Number)
	var i ChainBlock
	err := row.Scan(
		&i.TenantID,
		&i.ChainID,
		&i.Number,
		&i.Hash,
		&i.ParentHash,
		&i.SeenAt,
	)
	return i, err
}

const getChainState = `-- name: GetChainState :one
SELECT tenant_id, chain_id, anchor_hash, created_at, anchor_block FROM chain.chain_state WHERE tenant_id = $1 AND chain_id = $2
`

type GetChainStateParams struct {
	TenantID string
	ChainID  int64
}

func (q *Queries) GetChainState(ctx context.Context, arg GetChainStateParams) (ChainChainState, error) {
	row := q.db.QueryRow(ctx, getChainState, arg.TenantID, arg.ChainID)
	var i ChainChainState
	err := row.Scan(
		&i.TenantID,
		&i.ChainID,
		&i.AnchorHash,
		&i.CreatedAt,
		&i.AnchorBlock,
	)
	return i, err
}

const getDepositForUpdate = `-- name: GetDepositForUpdate :one
SELECT id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at FROM chain.deposits
WHERE tenant_id = $1 AND chain_id = $2 AND tx_hash = $3 AND log_index = $4
FOR UPDATE
`

type GetDepositForUpdateParams struct {
	TenantID string
	ChainID  int64
	TxHash   string
	LogIndex int32
}

// The re-detection path of docs/plan-v1.0.md §6.4.1: a deposit that reappears
// on the new canonical chain must be UPDATEd, never INSERTed, or the unique
// key rejects it and it can never be credited.
func (q *Queries) GetDepositForUpdate(ctx context.Context, arg GetDepositForUpdateParams) (ChainDeposit, error) {
	row := q.db.QueryRow(ctx, getDepositForUpdate,
		arg.TenantID,
		arg.ChainID,
		arg.TxHash,
		arg.LogIndex,
	)
	var i ChainDeposit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.TxHash,
		&i.LogIndex,
		&i.Address,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.BlockNumber,
		&i.BlockHash,
		&i.Confirmations,
		&i.Status,
		&i.OrphanedAtBlock,
		&i.CreditedAt,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fee,
		&i.CreditedAmount,
		&i.ReorgedAtBlock,
		&i.ReversalRequestedBy,
		&i.ReversalRequestedAt,
		&i.ReversalNote,
		&i.ReversalError,
		&i.ReversedAt,
	)
	return i, err
}

const getScanCursor = `-- name: GetScanCursor :one
SELECT tenant_id, chain_id, last_scanned_block, last_block_hash, updated_at FROM chain.scan_cursors WHERE tenant_id = $1 AND chain_id = $2
`

type GetScanCursorParams struct {
	TenantID string
	ChainID  int64
}

func (q *Queries) GetScanCursor(ctx context.Context, arg GetScanCursorParams) (ChainScanCursor, error) {
	row := q.db.QueryRow(ctx, getScanCursor, arg.TenantID, arg.ChainID)
	var i ChainScanCursor
	err := row.Scan(
		&i.TenantID,
		&i.ChainID,
		&i.LastScannedBlock,
		&i.LastBlockHash,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChainState = `-- name: InsertChainState :exec
INSERT INTO chain.chain_state (tenant_id, chain_id, anchor_block, anchor_hash)
VALUES ($1, $2, $3, $4)
`

type InsertChainStateParams struct {
	TenantID    string
	ChainID     int64
	AnchorBlock int64
	AnchorHash  string
}

// The anchor is the block this database's view of the chain starts at
// (ETH_SCAN_START_BLOCK) together with its hash. Recorded once, compared on
// every start: a different hash is a different chain, and a different block
// means the setting moved under a live database.
func (q *Queries) InsertChainState(ctx context.Context, arg InsertChainStateParams) error {
	_, err := q.db.Exec(ctx, insertChainState,
		arg.TenantID,
		arg.ChainID,
		arg.AnchorBlock,
		arg.AnchorHash,
	)
	return err
}

const insertDeposit = `-- name: InsertDeposit :one
INSERT INTO chain.deposits (
    tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount,
    block_number, block_hash, confirmations, status, correlation_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at
`

type InsertDepositParams struct {
	TenantID      string
	ChainID       int64
	TxHash        string
	LogIndex      int32
	Address       string
	AccountID     string
	Asset         string
	Amount        pgtype.Numeric
	BlockNumber   int64
	BlockHash     string
	Confirmations int32
	Status        string
	CorrelationID *string
}

func (q *Queries) InsertDeposit(ctx context.Context, arg InsertDepositParams) (ChainDeposit, error) {
	row := q.db.QueryRow(ctx, insertDeposit,
		arg.TenantID,
		arg.ChainID,
		arg.TxHash,
		arg.LogIndex,
		arg.Address,
		arg.AccountID,
		arg.Asset,
		arg.Amount,
		arg.BlockNumber,
		arg.BlockHash,
		arg.Confirmations,
		arg.Status,
		arg.CorrelationID,
	)
	var i ChainDeposit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.TxHash,
		&i.LogIndex,
		&i.Address,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.BlockNumber,
		&i.BlockHash,
		&i.Confirmations,
		&i.Status,
		&i.OrphanedAtBlock,
		&i.CreditedAt,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fee,
		&i.CreditedAmount,
		&i.ReorgedAtBlock,
		&i.ReversalRequestedBy,
		&i.ReversalRequestedAt,
		&i.ReversalNote,
		&i.ReversalError,
		&i.ReversedAt,
	)
	return i, err
}

const listDeposits = `-- name: ListDeposits :many
SELECT id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at FROM chain.deposits
WHERE tenant_id = $1
  AND ($4::text = '' OR status = $4::text)
  AND ($5::text = '' OR asset = $5::text)
ORDER BY created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListDepositsParams struct {
	TenantID string
	Limit    int32
	Offset   int32
	Status   string
	Asset    string
}

func (q *Queries) ListDeposits(ctx context.Context, arg ListDepositsParams) ([]ChainDeposit, error) {
	rows, err := q.db.Query(ctx, listDeposits,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Asset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainDeposit{}
	for rows.Next() {
		var i ChainDeposit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.Address,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.BlockNumber,
			&i.BlockHash,
			&i.Confirmations,
			&i.Status,
			&i.OrphanedAtBlock,
			&i.CreditedAt,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Fee,
			&i.CreditedAmount,
			&i.ReorgedAtBlock,
			&i.ReversalRequestedBy,
			&i.ReversalRequestedAt,
			&i.ReversalNote,
			&i.ReversalError,
			&i.ReversedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsAwaitingReversal = `-- name: ListDepositsAwaitingReversal :many
SELECT id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at FROM chain.deposits
WHERE tenant_id = $1 AND status = 'credited' AND reorged_at_block IS NOT NULL
  AND reversal_requested_at IS NULL
ORDER BY reorged_at_block, id
LIMIT $2 OFFSET $3
`

type ListDepositsAwaitingReversalParams struct {
	TenantID string
	Limit    int32
	Offset   int32
}

// The operator's queue: credited deposits the chain no longer shows, with no
// decision recorded yet.
func (q *Queries) ListDepositsAwaitingReversal(ctx context.Context, arg ListDepositsAwaitingReversalParams) ([]ChainDeposit, error) {
	rows, err := q.db.Query(ctx, listDepositsAwaitingReversal, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainDeposit{}
	for rows.Next() {
		var i ChainDeposit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.Address,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.BlockNumber,
			&i.BlockHash,
			&i.Confirmations,
			&i.Status,
			&i.OrphanedAtBlock,
			&i.CreditedAt,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Fee,
			&i.CreditedAmount,
			&i.ReorgedAtBlock,
			&i.ReversalRequestedBy,
			&i.ReversalRequestedAt,
			&i.ReversalNote,
			&i.ReversalError,
			&i.ReversedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsByAccount = `-- name: ListDepositsByAccount :many
SELECT id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at FROM chain.deposits
WHERE tenant_id = $1 AND account_id = $2
ORDER BY created_at DESC, id
LIMIT $3 OFFSET $4
`

type ListDepositsByAccountParams struct {
	TenantID  string
	AccountID string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListDepositsByAccount(ctx context.Context, arg ListDepositsByAccountParams) ([]ChainDeposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByAccount,
		arg.TenantID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainDeposit{}
	for rows.Next() {
		var i ChainDeposit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.Address,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.BlockNumber,
			&i.BlockHash,
			&i.Confirmations,
			&i.Status,
			&i.OrphanedAtBlock,
			&i.CreditedAt,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Fee,
			&i.CreditedAmount,
			&i.ReorgedAtBlock,
			&i.ReversalRequestedBy,
			&i.ReversalRequestedAt,
			&i.ReversalNote,
			&i.ReversalError,
			&i.ReversedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredOrphans = `-- name: ListExpiredOrphans :many
SELECT id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at FROM chain.deposits
WHERE tenant_id = $1 AND chain_id = $2 AND status = 'orphaned' AND orphaned_at_block <= $3
ORDER BY id
`

type ListExpiredOrphansParams struct {
	TenantID        string
	ChainID         int64
	OrphanedAtBlock *int64
}

func (q *Queries) ListExpiredOrphans(ctx context.Context, arg ListExpiredOrphansParams) ([]ChainDeposit, error) {
	rows, err := q.db.Query(ctx, listExpiredOrphans, arg.TenantID, arg.ChainID, arg.OrphanedAtBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainDeposit{}
	for rows.Next() {
		var i ChainDeposit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.Address,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.BlockNumber,
			&i.BlockHash,
			&i.Confirmations,
			&i.Status,
			&i.OrphanedAtBlock,
			&i.CreditedAt,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Fee,
			&i.CreditedAmount,
			&i.ReorgedAtBlock,
			&i.ReversalRequestedBy,
			&i.ReversalRequestedAt,
			&i.ReversalNote,
			&i.ReversalError,
			&i.ReversedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaturingDeposits = `-- name: ListMaturingDeposits :many
SELECT id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at FROM chain.deposits
WHERE tenant_id = $1 AND chain_id = $2 AND status IN ('detected', 'confirming')
ORDER BY block_number, id
`

type ListMaturingDepositsParams struct {
	TenantID string
	ChainID  int64
}

func (q *Queries) ListMaturingDeposits(ctx context.Context, arg ListMaturingDepositsParams) ([]ChainDeposit, error) {
	rows, err := q.db.Query(ctx, listMaturingDeposits, arg.TenantID, arg.ChainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainDeposit{}
	for rows.Next() {
		var i ChainDeposit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.Address,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.BlockNumber,
			&i.BlockHash,
			&i.Confirmations,
			&i.Status,
			&i.OrphanedAtBlock,
			&i.CreditedAt,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Fee,
			&i.CreditedAmount,
			&i.ReorgedAtBlock,
			&i.ReversalRequestedBy,
			&i.ReversalRequestedAt,
			&i.ReversalNote,
			&i.ReversalError,
			&i.ReversedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDepositCredited = `-- name: MarkDepositCredited :one
UPDATE chain.deposits
SET status = 'credited', confirmations = $3, credited_at = now(),
    fee = $4, credited_amount = $5,
    version = version + 1, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND status <> 'credited'
RETURNING id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at
`

type MarkDepositCreditedParams struct {
	ID             string
	TenantID       string
	Confirmations  int32
	Fee            pgtype.Numeric
	CreditedAmount pgtype.Numeric
}

func (q *Queries) MarkDepositCredited(ctx context.Context, arg MarkDepositCreditedParams) (ChainDeposit, error) {
	row := q.db.QueryRow(ctx, markDepositCredited,
		arg.ID,
		arg.TenantID,
		arg.Confirmations,
		arg.Fee,
		arg.CreditedAmount,
	)
	var i ChainDeposit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.TxHash,
		&i.LogIndex,
		&i.Address,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.BlockNumber,
		&i.BlockHash,
		&i.Confirmations,
		&i.Status,
		&i.OrphanedAtBlock,
		&i.CreditedAt,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fee,
		&i.CreditedAmount,
		&i.ReorgedAtBlock,
		&i.ReversalRequestedBy,
		&i.ReversalRequestedAt,
		&i.ReversalNote,
		&i.ReversalError,
		&i.ReversedAt,
	)
	return i, err
}

const markDepositDropped = `-- name: MarkDepositDropped :exec
UPDATE chain.deposits
SET status = 'dropped', version = version + 1, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND status = 'orphaned'
`

type MarkDepositDroppedParams struct {
	ID       string
	TenantID string
}

func (q *Queries) MarkDepositDropped(ctx context.Context, arg MarkDepositDroppedParams) error {
	_, err := q.db.Exec(ctx, markDepositDropped, arg.ID, arg.TenantID)
	return err
}

const markDepositReversed = `-- name: MarkDepositReversed :one
UPDATE chain.deposits
SET status = 'reversed', reversed_at = now(), credited_at = NULL,
    reversal_requested_at = NULL, reversal_error = NULL,
    version = version + 1, updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND status = 'credited'
RETURNING id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at
`

type MarkDepositReversedParams struct {
	ID       string
	TenantID string
}

// Applied. credited_at goes because 0009 ties it to the status; fee and
// credited_amount stay, because 0024 tied them to "the ledger moved" instead
// and they are the record of what was undone.
func (q *Queries) MarkDepositReversed(ctx context.Context, arg MarkDepositReversedParams) (ChainDeposit, error) {
	row := q.db.QueryRow(ctx, markDepositReversed, arg.ID, arg.TenantID)
	var i ChainDeposit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.TxHash,
		&i.LogIndex,
		&i.Address,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.BlockNumber,
		&i.BlockHash,
		&i.Confirmations,
		&i.Status,
		&i.OrphanedAtBlock,
		&i.CreditedAt,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fee,
		&i.CreditedAmount,
		&i.ReorgedAtBlock,
		&i.ReversalRequestedBy,
		&i.ReversalRequestedAt,
		&i.ReversalNote,
		&i.ReversalError,
		&i.ReversedAt,
	)
	return i, err
}

const markDepositsOrphaned = `-- name: MarkDepositsOrphaned :many
UPDATE chain.deposits
SET status = 'orphaned', orphaned_at_block = $4, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND chain_id = $2 AND block_number >= $3
  AND status IN ('detected', 'confirming')
RETURNING id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at
`

type MarkDepositsOrphanedParams struct {
	TenantID        string
	ChainID         int64
	BlockNumber     int64
	OrphanedAtBlock *int64
}

// Everything not yet credited in the abandoned blocks. Credited deposits are
// deliberately excluded: undoing those is the manual `reversed` path.
func (q *Queries) MarkDepositsOrphaned(ctx context.Context, arg MarkDepositsOrphanedParams) ([]ChainDeposit, error) {
	rows, err := q.db.Query(ctx, markDepositsOrphaned,
		arg.TenantID,
		arg.ChainID,
		arg.BlockNumber,
		arg.OrphanedAtBlock,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainDeposit{}
	for rows.Next() {
		var i ChainDeposit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.Address,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.BlockNumber,
			&i.BlockHash,
			&i.Confirmations,
			&i.Status,
			&i.OrphanedAtBlock,
			&i.CreditedAt,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Fee,
			&i.CreditedAmount,
			&i.ReorgedAtBlock,
			&i.ReversalRequestedBy,
			&i.ReversalRequestedAt,
			&i.ReversalNote,
			&i.ReversalError,
			&i.ReversedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDepositsReorged = `-- name: MarkDepositsReorged :many
UPDATE chain.deposits
SET reorged_at_block = $4, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND chain_id = $2 AND block_number >= $3
  AND status = 'credited' AND reorged_at_block IS NULL
RETURNING id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at
`

type MarkDepositsReorgedParams struct {
	TenantID       string
	ChainID        int64
	BlockNumber    int64
	ReorgedAtBlock *int64
}

// Credited deposits whose block was abandoned by a reorg. The status stays
// 'credited' -- the ledger still holds the credit and must until a reversing
// entry is posted -- so this only stamps the height, which is what puts the
// row in the operator's queue. Already-stamped rows are left alone: the first
// reorg is the one that matters, and a later, shallower one must not move the
// mark to a height the deposit was never valid at.
func (q *Queries) MarkDepositsReorged(ctx context.Context, arg MarkDepositsReorgedParams) ([]ChainDeposit, error) {
	rows, err := q.db.Query(ctx, markDepositsReorged,
		arg.TenantID,
		arg.ChainID,
		arg.BlockNumber,
		arg.ReorgedAtBlock,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainDeposit{}
	for rows.Next() {
		var i ChainDeposit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.Address,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.BlockNumber,
			&i.BlockHash,
			&i.Confirmations,
			&i.Status,
			&i.OrphanedAtBlock,
			&i.CreditedAt,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Fee,
			&i.CreditedAmount,
			&i.ReorgedAtBlock,
			&i.ReversalRequestedBy,
			&i.ReversalRequestedAt,
			&i.ReversalNote,
			&i.ReversalError,
			&i.ReversedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneBlocksBelow = `-- name: PruneBlocksBelow :execrows
DELETE FROM chain.blocks WHERE tenant_id = $1 AND chain_id = $2 AND number < $3
`

type PruneBlocksBelowParams struct {
	TenantID string
	ChainID  int64
	Number   int64
}

// Keeps the ring bounded; see the DELETE grant in migration 0009.
func (q *Queries) PruneBlocksBelow(ctx context.Context, arg PruneBlocksBelowParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneBlocksBelow, arg.TenantID, arg.ChainID, arg.Number)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDepositReversalError = `-- name: RecordDepositReversalError :exec
UPDATE chain.deposits
SET reversal_requested_at = NULL, reversal_error = $3,
    version = version + 1, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type RecordDepositReversalErrorParams struct {
	ID            string
	TenantID      string
	ReversalError *string
}

// The reversal could not be posted -- almost always because the account has
// already spent the money. The request is cleared so the worker does not spin
// on it, and the reason stays for the person who asked.
func (q *Queries) RecordDepositReversalError(ctx context.Context, arg RecordDepositReversalErrorParams) error {
	_, err := q.db.Exec(ctx, recordDepositReversalError, arg.ID, arg.TenantID, arg.ReversalError)
	return err
}

const requestDepositReversal = `-- name: RequestDepositReversal :one
UPDATE chain.deposits
SET reversal_requested_by = $3, reversal_requested_at = now(), reversal_note = $4,
    version = version + 1, updated_at = now()
WHERE id = $1 AND tenant_id = $2
  AND status = 'credited' AND reorged_at_block IS NOT NULL
  AND reversal_requested_at IS NULL
RETURNING id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at
`

type RequestDepositReversalParams struct {
	ID                  string
	TenantID            string
	ReversalRequestedBy *string
	ReversalNote        *string
}

// The admin role's only write to this table. It records a decision; it cannot
// move money, change the status, or touch a deposit the scanner has not marked.
func (q *Queries) RequestDepositReversal(ctx context.Context, arg RequestDepositReversalParams) (ChainDeposit, error) {
	row := q.db.QueryRow(ctx, requestDepositReversal,
		arg.ID,
		arg.TenantID,
		arg.ReversalRequestedBy,
		arg.ReversalNote,
	)
	var i ChainDeposit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.TxHash,
		&i.LogIndex,
		&i.Address,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.BlockNumber,
		&i.BlockHash,
		&i.Confirmations,
		&i.Status,
		&i.OrphanedAtBlock,
		&i.CreditedAt,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fee,
		&i.CreditedAmount,
		&i.ReorgedAtBlock,
		&i.ReversalRequestedBy,
		&i.ReversalRequestedAt,
		&i.ReversalNote,
		&i.ReversalError,
		&i.ReversedAt,
	)
	return i, err
}

const updateDepositSighting = `-- name: UpdateDepositSighting :one
UPDATE chain.deposits
SET block_number = $3, block_hash = $4, confirmations = $5, status = $6,
    orphaned_at_block = NULL, version = version + 1, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, chain_id, tx_hash, log_index, address, account_id, asset, amount, block_number, block_hash, confirmations, status, orphaned_at_block, credited_at, correlation_id, version, created_at, updated_at, fee, credited_amount, reorged_at_block, reversal_requested_by, reversal_requested_at, reversal_note, reversal_error, reversed_at
`

type UpdateDepositSightingParams struct {
	ID            string
	TenantID      string
	BlockNumber   int64
	BlockHash     string
	Confirmations int32
	Status        string
}

// Records where a deposit currently sits: a new block on a rescan, or another
// confirmation on the same one. Clears orphaned_at_block because a sighting
// means it is back on the canonical chain.
func (q *Queries) UpdateDepositSighting(ctx context.Context, arg UpdateDepositSightingParams) (ChainDeposit, error) {
	row := q.db.QueryRow(ctx, updateDepositSighting,
		arg.ID,
		arg.TenantID,
		arg.BlockNumber,
		arg.BlockHash,
		arg.Confirmations,
		arg.Status,
	)
	var i ChainDeposit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.TxHash,
		&i.LogIndex,
		&i.Address,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.BlockNumber,
		&i.BlockHash,
		&i.Confirmations,
		&i.Status,
		&i.OrphanedAtBlock,
		&i.CreditedAt,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fee,
		&i.CreditedAmount,
		&i.ReorgedAtBlock,
		&i.ReversalRequestedBy,
		&i.ReversalRequestedAt,
		&i.ReversalNote,
		&i.ReversalError,
		&i.ReversedAt,
	)
	return i, err
}

const upsertBlock = `-- name: UpsertBlock :exec
INSERT INTO chain.blocks (tenant_id, chain_id, number, hash, parent_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, chain_id, number) DO UPDATE
SET hash = excluded.hash, parent_hash = excluded.parent_hash, seen_at = now()
`

type UpsertBlockParams struct {
	TenantID   string
	ChainID    int64
	Number     int64
	Hash       string
	ParentHash string
}

// A rescan after a reorg writes a different hash at the same height, so the
// conflict target is the height and the hash is overwritten.
func (q *Queries) UpsertBlock(ctx context.Context, arg UpsertBlockParams) error {
	_, err := q.db.Exec(ctx, upsertBlock,
		arg.TenantID,
		arg.ChainID,
		arg.Number,
		arg.Hash,
		arg.ParentHash,
	)
	return err
}

const upsertScanCursor = `-- name: UpsertScanCursor :exec
INSERT INTO chain.scan_cursors (tenant_id, chain_id, last_scanned_block, last_block_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, chain_id) DO UPDATE
SET last_scanned_block = excluded.last_scanned_block,
    last_block_hash    = excluded.last_block_hash,
    updated_at         = now()
`

type UpsertScanCursorParams struct {
	TenantID         string
	ChainID          int64
	LastScannedBlock int64
	LastBlockHash    string
}

func (q *Queries) UpsertScanCursor(ctx context.Context, arg UpsertScanCursorParams) error {
	_, err := q.db.Exec(ctx, upsertScanCursor,
		arg.TenantID,
		arg.ChainID,
		arg.LastScannedBlock,
		arg.LastBlockHash,
	)
	return err
}
