// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminReconciliationBreak struct {
	ID            string
	TenantID      string
	ReportID      string
	ChainID       int64
	Asset         string
	BlockHeight   int64
	LedgerTotal   pgtype.Numeric
	ChainTotal    pgtype.Numeric
	Uncredited    pgtype.Numeric
	AboveFrontier pgtype.Numeric
	InFlight      pgtype.Numeric
	Diff          pgtype.Numeric
	CreatedAt     time.Time
}

type AdminReconciliationReport struct {
	ID         string
	TenantID   string
	ChainID    int64
	StartedAt  time.Time
	FinishedAt time.Time
	Balanced   bool
	Lines      []byte
	CreatedAt  time.Time
}

type ChainBlock struct {
	TenantID   string
	ChainID    int64
	Number     int64
	Hash       string
	ParentHash string
	SeenAt     time.Time
}

type ChainChainState struct {
	TenantID    string
	ChainID     int64
	AnchorHash  string
	CreatedAt   time.Time
	AnchorBlock int64
}

type ChainDeposit struct {
	ID              string
	TenantID        string
	ChainID         int64
	TxHash          string
	LogIndex        int32
	Address         string
	AccountID       string
	Asset           string
	Amount          pgtype.Numeric
	BlockNumber     int64
	BlockHash       string
	Confirmations   int32
	Status          string
	OrphanedAtBlock *int64
	CreditedAt      pgtype.Timestamptz
	CorrelationID   *string
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Fee             pgtype.Numeric
	CreditedAmount  pgtype.Numeric
}

type ChainDepositAddress struct {
	ID              string
	TenantID        string
	ChainID         int64
	DerivationIndex int64
	Address         string
	AccountID       *string
	CreatedAt       time.Time
	AssignedAt      pgtype.Timestamptz
}

type ChainHotWallet struct {
	TenantID     string
	ChainID      int64
	Address      string
	NextNonce    int64
	UpdatedAt    time.Time
	LowAlertedAt pgtype.Timestamptz
}

type ChainNonceFill struct {
	ID          int64
	TenantID    string
	ChainID     int64
	Nonce       int64
	TxHash      string
	Reason      string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BlockNumber *int64
	GasCost     pgtype.Numeric
}

type ChainScanCursor struct {
	TenantID         string
	ChainID          int64
	LastScannedBlock int64
	LastBlockHash    string
	UpdatedAt        time.Time
}

type ChainSigningLog struct {
	ID          int64
	TenantID    string
	Kind        string
	RefID       string
	Attempt     int32
	ChainID     int64
	FromAddress string
	ToAddress   string
	Nonce       int64
	TxHash      string
	RawTx       []byte
	SignedAt    time.Time
}

type ChainSweep struct {
	ID               string
	TenantID         string
	ChainID          int64
	AddressID        string
	FromAddress      string
	Asset            string
	Amount           pgtype.Numeric
	Status           string
	FailureReason    *string
	GasFundingTxHash *string
	GasFundingNonce  *int64
	GasFundingAmount pgtype.Numeric
	GasFundingRawTx  []byte
	GasFundingCost   pgtype.Numeric
	Nonce            *int64
	RawTx            []byte
	TxHash           *string
	BroadcastAt      pgtype.Timestamptz
	BlockNumber      *int64
	GasCost          pgtype.Numeric
	CorrelationID    *string
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	GasFundingBlock  *int64
}

type ChainWithdrawal struct {
	ID                 string
	TenantID           string
	AccountID          string
	Asset              string
	Amount             pgtype.Numeric
	ToAddress          string
	ChainID            int64
	IdempotencyKey     string
	RequestHash        string
	Status             string
	FailureReason      *string
	ReviewedBy         *string
	ReviewedAt         pgtype.Timestamptz
	ReviewNote         *string
	HoldEntryID        *int64
	CorrelationID      *string
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Nonce              *int64
	RawTx              []byte
	TxHash             *string
	BroadcastAt        pgtype.Timestamptz
	Replacements       int32
	BlockNumber        *int64
	GasCost            pgtype.Numeric
	CancelTxHash       *string
	ResolveAction      *string
	ResolveNote        *string
	ResolveRequestedBy *string
	ResolveRequestedAt pgtype.Timestamptz
	ResolveError       *string
	Fee                pgtype.Numeric
	FeeAsset           string
}
