// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signing.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateNonce = `-- name: AllocateNonce :one
UPDATE chain.hot_wallets
SET next_nonce = next_nonce + 1, updated_at = now()
WHERE tenant_id = $1 AND chain_id = $2
RETURNING next_nonce - 1 AS nonce
`

type AllocateNonceParams struct {
	TenantID string
	ChainID  int64
}

// Hands out the next nonce and advances the counter in one statement, so two
// workers cannot be given the same one. The row lock is the serialisation
// point of §6.4.2's single-goroutine rule, held by the database rather than
// by trust.
func (q *Queries) AllocateNonce(ctx context.Context, arg AllocateNonceParams) (int32, error) {
	row := q.db.QueryRow(ctx, allocateNonce, arg.TenantID, arg.ChainID)
	var nonce int32
	err := row.Scan(&nonce)
	return nonce, err
}

const allocateWithdrawalNonce = `-- name: AllocateWithdrawalNonce :one
UPDATE chain.withdrawals
SET nonce = $3, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error
`

type AllocateWithdrawalNonceParams struct {
	TenantID string
	ID       string
	Nonce    *int64
}

// Pins the nonce onto the withdrawal before anything is signed, so a crash
// between allocating and recording the signature does not strand the nonce and
// does not make the retry ask for a different transaction. The status stays
// funds_locked: nothing has been signed yet.
func (q *Queries) AllocateWithdrawalNonce(ctx context.Context, arg AllocateWithdrawalNonceParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, allocateWithdrawalNonce, arg.TenantID, arg.ID, arg.Nonce)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.Replacements,
		&i.BlockNumber,
		&i.GasCost,
		&i.CancelTxHash,
		&i.ResolveAction,
		&i.ResolveNote,
		&i.ResolveRequestedBy,
		&i.ResolveRequestedAt,
		&i.ResolveError,
	)
	return i, err
}

const getHotWallet = `-- name: GetHotWallet :one
SELECT tenant_id, chain_id, address, next_nonce, updated_at, low_alerted_at FROM chain.hot_wallets WHERE tenant_id = $1 AND chain_id = $2
`

type GetHotWalletParams struct {
	TenantID string
	ChainID  int64
}

func (q *Queries) GetHotWallet(ctx context.Context, arg GetHotWalletParams) (ChainHotWallet, error) {
	row := q.db.QueryRow(ctx, getHotWallet, arg.TenantID, arg.ChainID)
	var i ChainHotWallet
	err := row.Scan(
		&i.TenantID,
		&i.ChainID,
		&i.Address,
		&i.NextNonce,
		&i.UpdatedAt,
		&i.LowAlertedAt,
	)
	return i, err
}

const getSignature = `-- name: GetSignature :one
SELECT id, tenant_id, kind, ref_id, attempt, chain_id, from_address, to_address, nonce, tx_hash, raw_tx, signed_at FROM chain.signing_log
WHERE tenant_id = $1 AND kind = $2 AND ref_id = $3 AND attempt = $4
`

type GetSignatureParams struct {
	TenantID string
	Kind     string
	RefID    string
	Attempt  int32
}

func (q *Queries) GetSignature(ctx context.Context, arg GetSignatureParams) (ChainSigningLog, error) {
	row := q.db.QueryRow(ctx, getSignature,
		arg.TenantID,
		arg.Kind,
		arg.RefID,
		arg.Attempt,
	)
	var i ChainSigningLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.RefID,
		&i.Attempt,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TxHash,
		&i.RawTx,
		&i.SignedAt,
	)
	return i, err
}

const insertNonceFill = `-- name: InsertNonceFill :one
INSERT INTO chain.nonce_fills (tenant_id, chain_id, nonce, tx_hash, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, chain_id, nonce, tx_hash, reason, status, created_at, updated_at, block_number, gas_cost
`

type InsertNonceFillParams struct {
	TenantID string
	ChainID  int64
	Nonce    int64
	TxHash   string
	Reason   string
}

func (q *Queries) InsertNonceFill(ctx context.Context, arg InsertNonceFillParams) (ChainNonceFill, error) {
	row := q.db.QueryRow(ctx, insertNonceFill,
		arg.TenantID,
		arg.ChainID,
		arg.Nonce,
		arg.TxHash,
		arg.Reason,
	)
	var i ChainNonceFill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.Nonce,
		&i.TxHash,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlockNumber,
		&i.GasCost,
	)
	return i, err
}

const insertSignature = `-- name: InsertSignature :one
INSERT INTO chain.signing_log (
    tenant_id, kind, ref_id, attempt, chain_id, from_address, to_address, nonce, tx_hash, raw_tx
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, kind, ref_id, attempt, chain_id, from_address, to_address, nonce, tx_hash, raw_tx, signed_at
`

type InsertSignatureParams struct {
	TenantID    string
	Kind        string
	RefID       string
	Attempt     int32
	ChainID     int64
	FromAddress string
	ToAddress   string
	Nonce       int64
	TxHash      string
	RawTx       []byte
}

// Appended by the signer role only. The UNIQUE (kind, ref_id, attempt) is what
// makes signing unrepeatable: a retry or a replayed message collides here
// rather than producing a second valid transaction.
func (q *Queries) InsertSignature(ctx context.Context, arg InsertSignatureParams) (ChainSigningLog, error) {
	row := q.db.QueryRow(ctx, insertSignature,
		arg.TenantID,
		arg.Kind,
		arg.RefID,
		arg.Attempt,
		arg.ChainID,
		arg.FromAddress,
		arg.ToAddress,
		arg.Nonce,
		arg.TxHash,
		arg.RawTx,
	)
	var i ChainSigningLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.RefID,
		&i.Attempt,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TxHash,
		&i.RawTx,
		&i.SignedAt,
	)
	return i, err
}

const listAllocatedNonces = `-- name: ListAllocatedNonces :many
SELECT id, nonce, status, tx_hash, raw_tx FROM chain.withdrawals
WHERE tenant_id = $1 AND chain_id = $2 AND nonce IS NOT NULL
ORDER BY nonce
`

type ListAllocatedNoncesParams struct {
	TenantID string
	ChainID  int64
}

type ListAllocatedNoncesRow struct {
	ID     string
	Nonce  *int64
	Status string
	TxHash *string
	RawTx  []byte
}

// NonceManager's startup scan: every nonce this tenant has handed out on this
// chain, with the state of the withdrawal holding it.
func (q *Queries) ListAllocatedNonces(ctx context.Context, arg ListAllocatedNoncesParams) ([]ListAllocatedNoncesRow, error) {
	rows, err := q.db.Query(ctx, listAllocatedNonces, arg.TenantID, arg.ChainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllocatedNoncesRow{}
	for rows.Next() {
		var i ListAllocatedNoncesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nonce,
			&i.Status,
			&i.TxHash,
			&i.RawTx,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCancellingWithdrawals = `-- name: ListCancellingWithdrawals :many
SELECT id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error FROM chain.withdrawals
WHERE tenant_id = $1 AND status = 'broadcast' AND cancel_tx_hash IS NOT NULL
ORDER BY updated_at
LIMIT $2
`

type ListCancellingWithdrawalsParams struct {
	TenantID string
	Limit    int32
}

func (q *Queries) ListCancellingWithdrawals(ctx context.Context, arg ListCancellingWithdrawalsParams) ([]ChainWithdrawal, error) {
	rows, err := q.db.Query(ctx, listCancellingWithdrawals, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainWithdrawal{}
	for rows.Next() {
		var i ChainWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.ToAddress,
			&i.ChainID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.Status,
			&i.FailureReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.HoldEntryID,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Nonce,
			&i.RawTx,
			&i.TxHash,
			&i.BroadcastAt,
			&i.Replacements,
			&i.BlockNumber,
			&i.GasCost,
			&i.CancelTxHash,
			&i.ResolveAction,
			&i.ResolveNote,
			&i.ResolveRequestedBy,
			&i.ResolveRequestedAt,
			&i.ResolveError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconfirmedNonceFills = `-- name: ListUnconfirmedNonceFills :many
SELECT id, tenant_id, chain_id, nonce, tx_hash, reason, status, created_at, updated_at, block_number, gas_cost FROM chain.nonce_fills
WHERE tenant_id = $1 AND chain_id = $2 AND status = 'broadcast'
ORDER BY nonce
`

type ListUnconfirmedNonceFillsParams struct {
	TenantID string
	ChainID  int64
}

func (q *Queries) ListUnconfirmedNonceFills(ctx context.Context, arg ListUnconfirmedNonceFillsParams) ([]ChainNonceFill, error) {
	rows, err := q.db.Query(ctx, listUnconfirmedNonceFills, arg.TenantID, arg.ChainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainNonceFill{}
	for rows.Next() {
		var i ChainNonceFill
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.Nonce,
			&i.TxHash,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockNumber,
			&i.GasCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWithdrawalBroadcast = `-- name: MarkWithdrawalBroadcast :one
UPDATE chain.withdrawals
SET status = 'broadcast', broadcast_at = now(), version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error
`

type MarkWithdrawalBroadcastParams struct {
	TenantID string
	ID       string
}

func (q *Queries) MarkWithdrawalBroadcast(ctx context.Context, arg MarkWithdrawalBroadcastParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, markWithdrawalBroadcast, arg.TenantID, arg.ID)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.Replacements,
		&i.BlockNumber,
		&i.GasCost,
		&i.CancelTxHash,
		&i.ResolveAction,
		&i.ResolveNote,
		&i.ResolveRequestedBy,
		&i.ResolveRequestedAt,
		&i.ResolveError,
	)
	return i, err
}

const markWithdrawalCancelling = `-- name: MarkWithdrawalCancelling :one
UPDATE chain.withdrawals
SET cancel_tx_hash = $3, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error
`

type MarkWithdrawalCancellingParams struct {
	TenantID     string
	ID           string
	CancelTxHash *string
}

// Records the same-nonce transaction sent to displace a stuck withdrawal. The
// withdrawal stays broadcast: it is not resolved until the cancellation is
// mined.
func (q *Queries) MarkWithdrawalCancelling(ctx context.Context, arg MarkWithdrawalCancellingParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, markWithdrawalCancelling, arg.TenantID, arg.ID, arg.CancelTxHash)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.Replacements,
		&i.BlockNumber,
		&i.GasCost,
		&i.CancelTxHash,
		&i.ResolveAction,
		&i.ResolveNote,
		&i.ResolveRequestedBy,
		&i.ResolveRequestedAt,
		&i.ResolveError,
	)
	return i, err
}

const markWithdrawalConfirmed = `-- name: MarkWithdrawalConfirmed :one
UPDATE chain.withdrawals
SET status = 'confirmed', block_number = $3, gas_cost = $4,
    version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error
`

type MarkWithdrawalConfirmedParams struct {
	TenantID    string
	ID          string
	BlockNumber *int64
	GasCost     pgtype.Numeric
}

func (q *Queries) MarkWithdrawalConfirmed(ctx context.Context, arg MarkWithdrawalConfirmedParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, markWithdrawalConfirmed,
		arg.TenantID,
		arg.ID,
		arg.BlockNumber,
		arg.GasCost,
	)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.Replacements,
		&i.BlockNumber,
		&i.GasCost,
		&i.CancelTxHash,
		&i.ResolveAction,
		&i.ResolveNote,
		&i.ResolveRequestedBy,
		&i.ResolveRequestedAt,
		&i.ResolveError,
	)
	return i, err
}

const markWithdrawalReplacementFailed = `-- name: MarkWithdrawalReplacementFailed :one
UPDATE chain.withdrawals
SET broadcast_at = now(), replacements = replacements + 1,
    version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error
`

type MarkWithdrawalReplacementFailedParams struct {
	TenantID string
	ID       string
}

// A replacement the node refused (underpriced, or anything else that is not
// "already known").
//
// The attempt still counts. Until now the send error returned before
// ReplaceWithdrawalTx ran, so `replacements` never moved and MAX_REPLACEMENTS
// was unreachable: a withdrawal whose bumps the node kept refusing retried
// every REPLACE_AFTER forever instead of escalating to a person. Restarting
// the window at the same time stops the retry turning into a hot loop.
//
// raw_tx and tx_hash are deliberately untouched. The refused transaction is
// nowhere -- writing its hash would send the tracker chasing something that
// will never appear -- and the transaction it was meant to displace is still
// live in the mempool and still the one that might mine.
func (q *Queries) MarkWithdrawalReplacementFailed(ctx context.Context, arg MarkWithdrawalReplacementFailedParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, markWithdrawalReplacementFailed, arg.TenantID, arg.ID)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.Replacements,
		&i.BlockNumber,
		&i.GasCost,
		&i.CancelTxHash,
		&i.ResolveAction,
		&i.ResolveNote,
		&i.ResolveRequestedBy,
		&i.ResolveRequestedAt,
		&i.ResolveError,
	)
	return i, err
}

const recordWithdrawalGas = `-- name: RecordWithdrawalGas :one
UPDATE chain.withdrawals
SET block_number = $3, gas_cost = $4, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error
`

type RecordWithdrawalGasParams struct {
	TenantID    string
	ID          string
	BlockNumber *int64
	GasCost     pgtype.Numeric
}

// A failed transaction still burned gas, so the cost is recorded even though
// the transfer did not happen (§6.1.4 e).
func (q *Queries) RecordWithdrawalGas(ctx context.Context, arg RecordWithdrawalGasParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, recordWithdrawalGas,
		arg.TenantID,
		arg.ID,
		arg.BlockNumber,
		arg.GasCost,
	)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.Replacements,
		&i.BlockNumber,
		&i.GasCost,
		&i.CancelTxHash,
		&i.ResolveAction,
		&i.ResolveNote,
		&i.ResolveRequestedBy,
		&i.ResolveRequestedAt,
		&i.ResolveError,
	)
	return i, err
}

const replaceWithdrawalTx = `-- name: ReplaceWithdrawalTx :one
UPDATE chain.withdrawals
SET raw_tx = $3, tx_hash = $4, broadcast_at = now(), replacements = replacements + 1,
    version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error
`

type ReplaceWithdrawalTxParams struct {
	TenantID string
	ID       string
	RawTx    []byte
	TxHash   *string
}

// A re-send with a higher fee: same nonce, new signature, new hash. The
// replacement counter is also the attempt number in chain.signing_log.
func (q *Queries) ReplaceWithdrawalTx(ctx context.Context, arg ReplaceWithdrawalTxParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, replaceWithdrawalTx,
		arg.TenantID,
		arg.ID,
		arg.RawTx,
		arg.TxHash,
	)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.Replacements,
		&i.BlockNumber,
		&i.GasCost,
		&i.CancelTxHash,
		&i.ResolveAction,
		&i.ResolveNote,
		&i.ResolveRequestedBy,
		&i.ResolveRequestedAt,
		&i.ResolveError,
	)
	return i, err
}

const retryWithdrawal = `-- name: RetryWithdrawal :one
UPDATE chain.withdrawals
SET status = 'funds_locked', failure_reason = NULL,
    nonce = NULL, raw_tx = NULL, tx_hash = NULL, broadcast_at = NULL,
    block_number = NULL, cancel_tx_hash = NULL,
    replacements = replacements + 1, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error
`

type RetryWithdrawalParams struct {
	TenantID string
	ID       string
}

// Sends a failed withdrawal back for another attempt: the transaction columns
// are cleared so a fresh nonce is allocated, and the replacement counter is
// advanced so the new signature has a signing-log key of its own.
func (q *Queries) RetryWithdrawal(ctx context.Context, arg RetryWithdrawalParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, retryWithdrawal, arg.TenantID, arg.ID)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.Replacements,
		&i.BlockNumber,
		&i.GasCost,
		&i.CancelTxHash,
		&i.ResolveAction,
		&i.ResolveNote,
		&i.ResolveRequestedBy,
		&i.ResolveRequestedAt,
		&i.ResolveError,
	)
	return i, err
}

const setNextNonce = `-- name: SetNextNonce :exec
UPDATE chain.hot_wallets
SET next_nonce = $3, updated_at = now()
WHERE tenant_id = $1 AND chain_id = $2
`

type SetNextNonceParams struct {
	TenantID  string
	ChainID   int64
	NextNonce int64
}

// Recycles the most recently allocated nonce (§6.4.2: only when it is the
// last one out, otherwise the gap is filled instead).
func (q *Queries) SetNextNonce(ctx context.Context, arg SetNextNonceParams) error {
	_, err := q.db.Exec(ctx, setNextNonce, arg.TenantID, arg.ChainID, arg.NextNonce)
	return err
}

const signWithdrawal = `-- name: SignWithdrawal :one
UPDATE chain.withdrawals
SET status = 'signed', nonce = $3, raw_tx = $4, tx_hash = $5,
    version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at, nonce, raw_tx, tx_hash, broadcast_at, replacements, block_number, gas_cost, cancel_tx_hash, resolve_action, resolve_note, resolve_requested_by, resolve_requested_at, resolve_error
`

type SignWithdrawalParams struct {
	TenantID string
	ID       string
	Nonce    *int64
	RawTx    []byte
	TxHash   *string
}

// The one statement of §6.4.2's "nonce, raw signed tx and state land in the
// same transaction". Splitting it would leave a signed transaction nobody
// knows about, or a nonce nobody can spend.
func (q *Queries) SignWithdrawal(ctx context.Context, arg SignWithdrawalParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, signWithdrawal,
		arg.TenantID,
		arg.ID,
		arg.Nonce,
		arg.RawTx,
		arg.TxHash,
	)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.Replacements,
		&i.BlockNumber,
		&i.GasCost,
		&i.CancelTxHash,
		&i.ResolveAction,
		&i.ResolveNote,
		&i.ResolveRequestedBy,
		&i.ResolveRequestedAt,
		&i.ResolveError,
	)
	return i, err
}

const updateNonceFillStatus = `-- name: UpdateNonceFillStatus :exec
UPDATE chain.nonce_fills
SET status = $4, updated_at = now()
WHERE tenant_id = $1 AND chain_id = $2 AND nonce = $3
`

type UpdateNonceFillStatusParams struct {
	TenantID string
	ChainID  int64
	Nonce    int64
	Status   string
}

func (q *Queries) UpdateNonceFillStatus(ctx context.Context, arg UpdateNonceFillStatusParams) error {
	_, err := q.db.Exec(ctx, updateNonceFillStatus,
		arg.TenantID,
		arg.ChainID,
		arg.Nonce,
		arg.Status,
	)
	return err
}

const upsertHotWallet = `-- name: UpsertHotWallet :one
INSERT INTO chain.hot_wallets (tenant_id, chain_id, address, next_nonce)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, chain_id) DO UPDATE
SET updated_at = now()
RETURNING tenant_id, chain_id, address, next_nonce, updated_at, low_alerted_at
`

type UpsertHotWalletParams struct {
	TenantID  string
	ChainID   int64
	Address   string
	NextNonce int64
}

// Records the hot wallet on first start, and on every start after that returns
// what is already stored.
//
// The address is deliberately NOT overwritten. It is the evidence NonceManager
// compares against the key it derives, and a row that adopted whatever address
// it was last asked about could never disagree with anything -- which is to
// say the "this is a different wallet" refusal would be unreachable, and a
// deployment given the wrong seed would carry on allocating nonces against a
// stranger's counter.
func (q *Queries) UpsertHotWallet(ctx context.Context, arg UpsertHotWalletParams) (ChainHotWallet, error) {
	row := q.db.QueryRow(ctx, upsertHotWallet,
		arg.TenantID,
		arg.ChainID,
		arg.Address,
		arg.NextNonce,
	)
	var i ChainHotWallet
	err := row.Scan(
		&i.TenantID,
		&i.ChainID,
		&i.Address,
		&i.NextNonce,
		&i.UpdatedAt,
		&i.LowAlertedAt,
	)
	return i, err
}
