// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sweeps.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateSweepNonce = `-- name: AllocateSweepNonce :one
UPDATE chain.sweeps
SET nonce = $3, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type AllocateSweepNonceParams struct {
	TenantID string
	ID       string
	Nonce    *int64
}

// Pins the nonce before anything is signed, the same discipline
// AllocateWithdrawalNonce enforces: a crash between signing and recording must
// come back asking for the same transaction, not a different one.
func (q *Queries) AllocateSweepNonce(ctx context.Context, arg AllocateSweepNonceParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, allocateSweepNonce, arg.TenantID, arg.ID, arg.Nonce)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const claimSweeps = `-- name: ClaimSweeps :many
SELECT id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block FROM chain.sweeps
WHERE tenant_id = $1 AND status = ANY($3::text[])
ORDER BY created_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimSweepsParams struct {
	TenantID string
	Limit    int32
	Statuses []string
}

// The worker's queue, oldest first. SKIP LOCKED for the same reason
// ClaimWithdrawals uses it: a second worker takes different rows rather than
// waiting behind the first.
func (q *Queries) ClaimSweeps(ctx context.Context, arg ClaimSweepsParams) ([]ChainSweep, error) {
	rows, err := q.db.Query(ctx, claimSweeps, arg.TenantID, arg.Limit, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainSweep{}
	for rows.Next() {
		var i ChainSweep
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.AddressID,
			&i.FromAddress,
			&i.Asset,
			&i.Amount,
			&i.Status,
			&i.FailureReason,
			&i.GasFundingTxHash,
			&i.GasFundingNonce,
			&i.GasFundingAmount,
			&i.GasFundingRawTx,
			&i.GasFundingCost,
			&i.Nonce,
			&i.RawTx,
			&i.TxHash,
			&i.BroadcastAt,
			&i.BlockNumber,
			&i.GasCost,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GasFundingBlock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearSweepGasFunding = `-- name: ClearSweepGasFunding :one
UPDATE chain.sweeps
SET gas_funding_amount = NULL, gas_funding_nonce = NULL,
    version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND gas_funding_tx_hash IS NULL
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type ClearSweepGasFundingParams struct {
	TenantID string
	ID       string
}

// Forget a funding transaction that was pinned but never signed.
//
// FundSweepGas writes gas_funding_amount when it pins the nonce, before the
// signer is asked. If signing then fails, the row keeps an amount with no
// transaction, and the next tick -- finding the address can now pay its own
// way and taking the shortcut past funding -- would book that amount as ether
// the hot wallet sent. It never sent it.
func (q *Queries) ClearSweepGasFunding(ctx context.Context, arg ClearSweepGasFundingParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, clearSweepGasFunding, arg.TenantID, arg.ID)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const countUnsettledDeposits = `-- name: CountUnsettledDeposits :one
SELECT count(*) FROM chain.deposits d
JOIN chain.deposit_addresses a
  ON a.tenant_id = d.tenant_id AND a.chain_id = d.chain_id AND a.address = d.address
WHERE d.tenant_id = $1 AND a.id = $2 AND d.status IN ('detected', 'confirming', 'orphaned')
`

type CountUnsettledDepositsParams struct {
	TenantID string
	ID       string
}

// Deposits on this address that the ledger has not credited yet. An address
// with any of them is not swept at all: the sweep would move money the ledger
// is about to record arriving, and the two would cross.
func (q *Queries) CountUnsettledDeposits(ctx context.Context, arg CountUnsettledDepositsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsettledDeposits, arg.TenantID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const creditedToAddress = `-- name: CreditedToAddress :one
SELECT COALESCE(SUM(d.amount), 0)::numeric(36,18) AS total
FROM chain.deposits d
JOIN chain.deposit_addresses a
  ON a.tenant_id = d.tenant_id AND a.chain_id = d.chain_id AND a.address = d.address
WHERE d.tenant_id = $1 AND a.id = $2 AND d.asset = $3 AND d.status = 'credited'
`

type CreditedToAddressParams struct {
	TenantID string
	ID       string
	Asset    string
}

// How much of this asset the ledger believes arrived at this address: the sum
// of the deposits it actually credited.
//
// This is the ceiling on what may be swept. The chain balance can be higher --
// an internal contract transfer the scanner does not see (§4 puts those out of
// scope but nothing prevents them), or a deposit still confirming -- and
// sweeping money custody:deposit_addresses was never credited for would make
// that account claim a transfer it never received.
func (q *Queries) CreditedToAddress(ctx context.Context, arg CreditedToAddressParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, creditedToAddress, arg.TenantID, arg.ID, arg.Asset)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const failSweep = `-- name: FailSweep :one
UPDATE chain.sweeps
SET status = 'failed', failure_reason = $3, gas_cost = $4, block_number = $5,
    version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type FailSweepParams struct {
	TenantID      string
	ID            string
	FailureReason *string
	GasCost       pgtype.Numeric
	BlockNumber   *int64
}

// The sweep transaction itself failed. Its gas and the block it burned in are
// written together: reconciliation reads the two as a pair, and a cost with no
// block cannot be placed above or below the frontier.
func (q *Queries) FailSweep(ctx context.Context, arg FailSweepParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, failSweep,
		arg.TenantID,
		arg.ID,
		arg.FailureReason,
		arg.GasCost,
		arg.BlockNumber,
	)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const failSweepFunding = `-- name: FailSweepFunding :one
UPDATE chain.sweeps
SET status = 'failed', failure_reason = $3, gas_funding_cost = $4,
    gas_funding_block = $5, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type FailSweepFundingParams struct {
	TenantID        string
	ID              string
	FailureReason   *string
	GasFundingCost  pgtype.Numeric
	GasFundingBlock *int64
}

// The gas-funding transaction failed, so the cost belongs to the funding pair
// of columns rather than the sweep's. Writing it into gas_cost -- as this
// table did before reconciliation needed to read them -- would pair a funding
// cost with a sweep block that never happened.
func (q *Queries) FailSweepFunding(ctx context.Context, arg FailSweepFundingParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, failSweepFunding,
		arg.TenantID,
		arg.ID,
		arg.FailureReason,
		arg.GasFundingCost,
		arg.GasFundingBlock,
	)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const fundSweepGas = `-- name: FundSweepGas :one
UPDATE chain.sweeps
SET gas_funding_nonce = $3, gas_funding_raw_tx = $4, gas_funding_tx_hash = $5,
    gas_funding_amount = $6, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type FundSweepGasParams struct {
	TenantID         string
	ID               string
	GasFundingNonce  *int64
	GasFundingRawTx  []byte
	GasFundingTxHash *string
	GasFundingAmount pgtype.Numeric
}

// Records the gas-funding transaction before it is sent, so a crash cannot
// lose track of ETH the hot wallet has already committed.
func (q *Queries) FundSweepGas(ctx context.Context, arg FundSweepGasParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, fundSweepGas,
		arg.TenantID,
		arg.ID,
		arg.GasFundingNonce,
		arg.GasFundingRawTx,
		arg.GasFundingTxHash,
		arg.GasFundingAmount,
	)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const getDepositAddressByAddress = `-- name: GetDepositAddressByAddress :one
SELECT id, tenant_id, chain_id, derivation_index, address, account_id, created_at, assigned_at FROM chain.deposit_addresses
WHERE tenant_id = $1 AND chain_id = $2 AND address = $3
`

type GetDepositAddressByAddressParams struct {
	TenantID string
	ChainID  int64
	Address  string
}

func (q *Queries) GetDepositAddressByAddress(ctx context.Context, arg GetDepositAddressByAddressParams) (ChainDepositAddress, error) {
	row := q.db.QueryRow(ctx, getDepositAddressByAddress, arg.TenantID, arg.ChainID, arg.Address)
	var i ChainDepositAddress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.DerivationIndex,
		&i.Address,
		&i.AccountID,
		&i.CreatedAt,
		&i.AssignedAt,
	)
	return i, err
}

const getDepositAddressByID = `-- name: GetDepositAddressByID :one
SELECT id, tenant_id, chain_id, derivation_index, address, account_id, created_at, assigned_at FROM chain.deposit_addresses WHERE tenant_id = $1 AND id = $2
`

type GetDepositAddressByIDParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetDepositAddressByID(ctx context.Context, arg GetDepositAddressByIDParams) (ChainDepositAddress, error) {
	row := q.db.QueryRow(ctx, getDepositAddressByID, arg.TenantID, arg.ID)
	var i ChainDepositAddress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.DerivationIndex,
		&i.Address,
		&i.AccountID,
		&i.CreatedAt,
		&i.AssignedAt,
	)
	return i, err
}

const getSweep = `-- name: GetSweep :one
SELECT id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block FROM chain.sweeps WHERE tenant_id = $1 AND id = $2
`

type GetSweepParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetSweep(ctx context.Context, arg GetSweepParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, getSweep, arg.TenantID, arg.ID)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const insertSweep = `-- name: InsertSweep :one
INSERT INTO chain.sweeps (
    tenant_id, chain_id, address_id, from_address, asset, amount, correlation_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type InsertSweepParams struct {
	TenantID      string
	ChainID       int64
	AddressID     string
	FromAddress   string
	Asset         string
	Amount        pgtype.Numeric
	CorrelationID *string
}

func (q *Queries) InsertSweep(ctx context.Context, arg InsertSweepParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, insertSweep,
		arg.TenantID,
		arg.ChainID,
		arg.AddressID,
		arg.FromAddress,
		arg.Asset,
		arg.Amount,
		arg.CorrelationID,
	)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const listSweeps = `-- name: ListSweeps :many
SELECT id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block FROM chain.sweeps
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListSweepsParams struct {
	TenantID string
	Limit    int32
}

func (q *Queries) ListSweeps(ctx context.Context, arg ListSweepsParams) ([]ChainSweep, error) {
	rows, err := q.db.Query(ctx, listSweeps, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainSweep{}
	for rows.Next() {
		var i ChainSweep
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChainID,
			&i.AddressID,
			&i.FromAddress,
			&i.Asset,
			&i.Amount,
			&i.Status,
			&i.FailureReason,
			&i.GasFundingTxHash,
			&i.GasFundingNonce,
			&i.GasFundingAmount,
			&i.GasFundingRawTx,
			&i.GasFundingCost,
			&i.Nonce,
			&i.RawTx,
			&i.TxHash,
			&i.BroadcastAt,
			&i.BlockNumber,
			&i.GasCost,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GasFundingBlock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSweepBroadcast = `-- name: MarkSweepBroadcast :one
UPDATE chain.sweeps
SET status = 'broadcast', broadcast_at = now(), version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type MarkSweepBroadcastParams struct {
	TenantID string
	ID       string
}

func (q *Queries) MarkSweepBroadcast(ctx context.Context, arg MarkSweepBroadcastParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, markSweepBroadcast, arg.TenantID, arg.ID)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const markSweepConfirmed = `-- name: MarkSweepConfirmed :one
UPDATE chain.sweeps
SET status = 'confirmed', block_number = $3, gas_cost = $4,
    version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type MarkSweepConfirmedParams struct {
	TenantID    string
	ID          string
	BlockNumber *int64
	GasCost     pgtype.Numeric
}

func (q *Queries) MarkSweepConfirmed(ctx context.Context, arg MarkSweepConfirmedParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, markSweepConfirmed,
		arg.TenantID,
		arg.ID,
		arg.BlockNumber,
		arg.GasCost,
	)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const markSweepGasFunded = `-- name: MarkSweepGasFunded :one
UPDATE chain.sweeps
SET status = 'gas_funded', gas_funding_cost = $3, gas_funding_block = $4,
    version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type MarkSweepGasFundedParams struct {
	TenantID        string
	ID              string
	GasFundingCost  pgtype.Numeric
	GasFundingBlock *int64
}

// The funding transaction is mined: the address can now pay for its own
// transfer, and the ETH that moved is booked.
//
// gas_funding_block records where, so reconciliation can tell whether the
// ledger entry this produces is above or below the height it read balances at.
// Null when the address already held enough and no transaction was sent.
func (q *Queries) MarkSweepGasFunded(ctx context.Context, arg MarkSweepGasFundedParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, markSweepGasFunded,
		arg.TenantID,
		arg.ID,
		arg.GasFundingCost,
		arg.GasFundingBlock,
	)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const signSweep = `-- name: SignSweep :one
UPDATE chain.sweeps
SET raw_tx = $3, tx_hash = $4, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, chain_id, address_id, from_address, asset, amount, status, failure_reason, gas_funding_tx_hash, gas_funding_nonce, gas_funding_amount, gas_funding_raw_tx, gas_funding_cost, nonce, raw_tx, tx_hash, broadcast_at, block_number, gas_cost, correlation_id, version, created_at, updated_at, gas_funding_block
`

type SignSweepParams struct {
	TenantID string
	ID       string
	RawTx    []byte
	TxHash   *string
}

func (q *Queries) SignSweep(ctx context.Context, arg SignSweepParams) (ChainSweep, error) {
	row := q.db.QueryRow(ctx, signSweep,
		arg.TenantID,
		arg.ID,
		arg.RawTx,
		arg.TxHash,
	)
	var i ChainSweep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainID,
		&i.AddressID,
		&i.FromAddress,
		&i.Asset,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.GasFundingTxHash,
		&i.GasFundingNonce,
		&i.GasFundingAmount,
		&i.GasFundingRawTx,
		&i.GasFundingCost,
		&i.Nonce,
		&i.RawTx,
		&i.TxHash,
		&i.BroadcastAt,
		&i.BlockNumber,
		&i.GasCost,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GasFundingBlock,
	)
	return i, err
}

const sweptFromAddress = `-- name: SweptFromAddress :one
SELECT COALESCE(SUM(
    amount + CASE WHEN $1::text = $2::text
                  THEN COALESCE(gas_cost, 0) ELSE 0 END
), 0)::numeric(36,18) AS total
FROM chain.sweeps
WHERE tenant_id = $3 AND address_id = $4
  AND asset = $1::text AND status = 'confirmed'
`

type SweptFromAddressParams struct {
	Asset       string
	NativeAsset string
	TenantID    string
	AddressID   string
}

// How much of this asset has already left this address. Only confirmed sweeps
// count: one still in flight has not moved anything, and one that failed never
// will.
//
// The gas is added only when the asset swept *is* the native coin, because
// that is the only case where the gas came out of the same balance. A token
// sweep burns ether and moves USDC; adding one to the other would be adding
// two different currencies.
func (q *Queries) SweptFromAddress(ctx context.Context, arg SweptFromAddressParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sweptFromAddress,
		arg.Asset,
		arg.NativeAsset,
		arg.TenantID,
		arg.AddressID,
	)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}
