// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: withdrawals.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWithdrawals = `-- name: ClaimWithdrawals :many
SELECT id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at FROM chain.withdrawals
WHERE tenant_id = $1 AND status = ANY($3::text[])
ORDER BY created_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimWithdrawalsParams struct {
	TenantID string
	Limit    int32
	Statuses []string
}

// The worker's queue. SKIP LOCKED so a second worker takes different rows
// rather than waiting behind the first (the pattern chain.deposit_addresses
// already uses for the address pool).
func (q *Queries) ClaimWithdrawals(ctx context.Context, arg ClaimWithdrawalsParams) ([]ChainWithdrawal, error) {
	rows, err := q.db.Query(ctx, claimWithdrawals, arg.TenantID, arg.Limit, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainWithdrawal{}
	for rows.Next() {
		var i ChainWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.ToAddress,
			&i.ChainID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.Status,
			&i.FailureReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.HoldEntryID,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWithdrawalsByStatus = `-- name: CountWithdrawalsByStatus :one
SELECT count(*) FROM chain.withdrawals
WHERE tenant_id = $1 AND status = ANY($2::text[])
`

type CountWithdrawalsByStatusParams struct {
	TenantID string
	Statuses []string
}

// Feeds the review-queue gauge: a withdrawal waiting for a person is a user
// waiting for their money, and nothing else in the system notices.
func (q *Queries) CountWithdrawalsByStatus(ctx context.Context, arg CountWithdrawalsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWithdrawalsByStatus, arg.TenantID, arg.Statuses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWithdrawal = `-- name: GetWithdrawal :one
SELECT id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at FROM chain.withdrawals WHERE tenant_id = $1 AND id = $2
`

type GetWithdrawalParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetWithdrawal(ctx context.Context, arg GetWithdrawalParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawal, arg.TenantID, arg.ID)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalByIdempotencyKey = `-- name: GetWithdrawalByIdempotencyKey :one
SELECT id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at FROM chain.withdrawals
WHERE tenant_id = $1 AND account_id = $2 AND idempotency_key = $3
`

type GetWithdrawalByIdempotencyKeyParams struct {
	TenantID       string
	AccountID      string
	IdempotencyKey string
}

// The replay path of docs/plan-v1.0.md §6.4.2. The key is scoped to the
// account so one client's key cannot reach another's withdrawal.
func (q *Queries) GetWithdrawalByIdempotencyKey(ctx context.Context, arg GetWithdrawalByIdempotencyKeyParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawalByIdempotencyKey, arg.TenantID, arg.AccountID, arg.IdempotencyKey)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalForUpdate = `-- name: GetWithdrawalForUpdate :one
SELECT id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at FROM chain.withdrawals
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type GetWithdrawalForUpdateParams struct {
	TenantID string
	ID       string
}

// Every transition reads the row under a lock first: two workers must not
// both decide a withdrawal, and an admin approval must not race the worker
// that is already locking the funds.
func (q *Queries) GetWithdrawalForUpdate(ctx context.Context, arg GetWithdrawalForUpdateParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawalForUpdate, arg.TenantID, arg.ID)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWithdrawal = `-- name: InsertWithdrawal :one
INSERT INTO chain.withdrawals (
    tenant_id, account_id, asset, amount, to_address, chain_id,
    idempotency_key, request_hash, status, correlation_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'requested', $9)
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at
`

type InsertWithdrawalParams struct {
	TenantID       string
	AccountID      string
	Asset          string
	Amount         pgtype.Numeric
	ToAddress      string
	ChainID        int64
	IdempotencyKey string
	RequestHash    string
	CorrelationID  *string
}

func (q *Queries) InsertWithdrawal(ctx context.Context, arg InsertWithdrawalParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, insertWithdrawal,
		arg.TenantID,
		arg.AccountID,
		arg.Asset,
		arg.Amount,
		arg.ToAddress,
		arg.ChainID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.CorrelationID,
	)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWithdrawalsByAccount = `-- name: ListWithdrawalsByAccount :many
SELECT id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at FROM chain.withdrawals
WHERE tenant_id = $1 AND account_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListWithdrawalsByAccountParams struct {
	TenantID  string
	AccountID string
	Limit     int32
}

func (q *Queries) ListWithdrawalsByAccount(ctx context.Context, arg ListWithdrawalsByAccountParams) ([]ChainWithdrawal, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsByAccount, arg.TenantID, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainWithdrawal{}
	for rows.Next() {
		var i ChainWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.ToAddress,
			&i.ChainID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.Status,
			&i.FailureReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.HoldEntryID,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalsByStatus = `-- name: ListWithdrawalsByStatus :many
SELECT id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at FROM chain.withdrawals
WHERE tenant_id = $1 AND status = ANY($3::text[])
ORDER BY created_at
LIMIT $2
`

type ListWithdrawalsByStatusParams struct {
	TenantID string
	Limit    int32
	Statuses []string
}

// The admin review queue, oldest first: the person waiting longest is served
// first, unlike the user-facing listing.
func (q *Queries) ListWithdrawalsByStatus(ctx context.Context, arg ListWithdrawalsByStatusParams) ([]ChainWithdrawal, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsByStatus, arg.TenantID, arg.Limit, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChainWithdrawal{}
	for rows.Next() {
		var i ChainWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.Asset,
			&i.Amount,
			&i.ToAddress,
			&i.ChainID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.Status,
			&i.FailureReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.HoldEntryID,
			&i.CorrelationID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWithdrawalFunds = `-- name: LockWithdrawalFunds :one
UPDATE chain.withdrawals
SET status = 'funds_locked', hold_entry_id = $3, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at
`

type LockWithdrawalFundsParams struct {
	TenantID    string
	ID          string
	HoldEntryID *int64
}

// funds_locked also records which ledger entry did the locking, so the hold
// can be traced without reconstructing its idempotency key.
func (q *Queries) LockWithdrawalFunds(ctx context.Context, arg LockWithdrawalFundsParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, lockWithdrawalFunds, arg.TenantID, arg.ID, arg.HoldEntryID)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reviewWithdrawal = `-- name: ReviewWithdrawal :one
UPDATE chain.withdrawals
SET status = $3, failure_reason = $4, reviewed_by = $5, reviewed_at = now(),
    review_note = $6, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at
`

type ReviewWithdrawalParams struct {
	TenantID      string
	ID            string
	Status        string
	FailureReason *string
	ReviewedBy    *string
	ReviewNote    *string
}

// The admin decision. reviewed_by and reviewed_at are written together
// because 0010 requires them to be both set or both null.
func (q *Queries) ReviewWithdrawal(ctx context.Context, arg ReviewWithdrawalParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, reviewWithdrawal,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.ReviewedBy,
		arg.ReviewNote,
	)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumWithdrawnSince = `-- name: SumWithdrawnSince :one
SELECT COALESCE(SUM(amount), 0)::numeric(36,18) AS total
FROM chain.withdrawals
WHERE tenant_id = $1 AND account_id = $2 AND asset = $3
  AND created_at >= $4
  AND status NOT IN ('rejected', 'failed')
`

type SumWithdrawnSinceParams struct {
	TenantID  string
	AccountID string
	Asset     string
	CreatedAt time.Time
}

// The daily limit of §6.4.2. Everything that is not rejected or failed counts
// against it: a withdrawal still in review is money the account has already
// committed, and letting a second one through while the first waits would be
// a way to spend the limit twice.
func (q *Queries) SumWithdrawnSince(ctx context.Context, arg SumWithdrawnSinceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumWithdrawnSince,
		arg.TenantID,
		arg.AccountID,
		arg.Asset,
		arg.CreatedAt,
	)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const updateWithdrawalStatus = `-- name: UpdateWithdrawalStatus :one
UPDATE chain.withdrawals
SET status = $3, failure_reason = $4, version = version + 1, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, account_id, asset, amount, to_address, chain_id, idempotency_key, request_hash, status, failure_reason, reviewed_by, reviewed_at, review_note, hold_entry_id, correlation_id, version, created_at, updated_at
`

type UpdateWithdrawalStatusParams struct {
	TenantID      string
	ID            string
	Status        string
	FailureReason *string
}

// The one transition statement: it carries the failure reason because a
// failure must never be recorded without one (0010 CHECK).
func (q *Queries) UpdateWithdrawalStatus(ctx context.Context, arg UpdateWithdrawalStatusParams) (ChainWithdrawal, error) {
	row := q.db.QueryRow(ctx, updateWithdrawalStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.FailureReason,
	)
	var i ChainWithdrawal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.Asset,
		&i.Amount,
		&i.ToAddress,
		&i.ChainID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.FailureReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.HoldEntryID,
		&i.CorrelationID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
