// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type AuditAuditEvent struct {
	ID            int64
	TenantID      string
	ActorType     string
	ActorID       *string
	Action        string
	TargetType    *string
	TargetID      *string
	Before        []byte
	After         []byte
	Ip            *string
	CorrelationID *string
	CreatedAt     time.Time
}
