// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TradingOrder struct {
	ID            string
	TenantID      string
	AccountID     string
	MarketID      string
	MarketSymbol  string
	ClientOrderID string
	Side          string
	Type          string
	TimeInForce   string
	Price         pgtype.Numeric
	Qty           pgtype.Numeric
	QuoteQty      pgtype.Numeric
	FilledQty     pgtype.Numeric
	FilledQuote   pgtype.Numeric
	RemainingQty  pgtype.Numeric
	HoldAsset     string
	HoldAmount    pgtype.Numeric
	HoldRemaining pgtype.Numeric
	Status        string
	RejectReason  *string
	CancelReason  *string
	Seq           *int64
	CorrelationID *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type TradingTrade struct {
	ID             string
	TenantID       string
	MarketID       string
	MarketSymbol   string
	Seq            int64
	Idx            int32
	MakerOrderID   string
	TakerOrderID   string
	MakerAccountID string
	TakerAccountID string
	TakerSide      string
	Price          pgtype.Numeric
	Qty            pgtype.Numeric
	QuoteQty       pgtype.Numeric
	MakerFee       pgtype.Numeric
	MakerFeeAsset  string
	TakerFee       pgtype.Numeric
	TakerFeeAsset  string
	CreatedAt      time.Time
}
