// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trading.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const AdvanceMarketSequence = `-- name: AdvanceMarketSequence :execrows
UPDATE trading.market_sequences
   SET last_seq = $2, updated_at = now()
 WHERE market_id = $1 AND last_seq = $2 - 1
`

type AdvanceMarketSequenceParams struct {
	MarketID string
	LastSeq  int64
}

// Guarded: succeeds only when nobody else advanced the sequence since the
// engine last read it (a second engine instance would fail here).
func (q *Queries) AdvanceMarketSequence(ctx context.Context, arg AdvanceMarketSequenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, AdvanceMarketSequence, arg.MarketID, arg.LastSeq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const CountOpenOrdersByMarket = `-- name: CountOpenOrdersByMarket :one
SELECT count(*) FROM trading.orders WHERE market_id = $1 AND status IN ('open', 'partially_filled')
`

func (q *Queries) CountOpenOrdersByMarket(ctx context.Context, marketID string) (int64, error) {
	row := q.db.QueryRow(ctx, CountOpenOrdersByMarket, marketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const EnsureMarketSequence = `-- name: EnsureMarketSequence :one

INSERT INTO trading.market_sequences (market_id)
VALUES ($1)
ON CONFLICT (market_id) DO UPDATE SET updated_at = trading.market_sequences.updated_at
RETURNING last_seq
`

// Sequences ---------------------------------------------------------------
func (q *Queries) EnsureMarketSequence(ctx context.Context, marketID string) (int64, error) {
	row := q.db.QueryRow(ctx, EnsureMarketSequence, marketID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const GetMarketSequence = `-- name: GetMarketSequence :one
SELECT last_seq FROM trading.market_sequences WHERE market_id = $1
`

func (q *Queries) GetMarketSequence(ctx context.Context, marketID string) (int64, error) {
	row := q.db.QueryRow(ctx, GetMarketSequence, marketID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const GetOrder = `-- name: GetOrder :one


SELECT id, tenant_id, account_id, market_id, market_symbol, client_order_id, side, type, time_in_force, price, qty, quote_qty, filled_qty, filled_quote, remaining_qty, hold_asset, hold_amount, hold_remaining, status, reject_reason, cancel_reason, seq, correlation_id, created_at, updated_at FROM trading.orders WHERE id = $1
`

// Trading queries (engine role writes, every role reads). Schema-qualified.
// Orders -----------------------------------------------------------------
func (q *Queries) GetOrder(ctx context.Context, id string) (TradingOrder, error) {
	row := q.db.QueryRow(ctx, GetOrder, id)
	var i TradingOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.MarketID,
		&i.MarketSymbol,
		&i.ClientOrderID,
		&i.Side,
		&i.Type,
		&i.TimeInForce,
		&i.Price,
		&i.Qty,
		&i.QuoteQty,
		&i.FilledQty,
		&i.FilledQuote,
		&i.RemainingQty,
		&i.HoldAsset,
		&i.HoldAmount,
		&i.HoldRemaining,
		&i.Status,
		&i.RejectReason,
		&i.CancelReason,
		&i.Seq,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetOrderByClientID = `-- name: GetOrderByClientID :one
SELECT id, tenant_id, account_id, market_id, market_symbol, client_order_id, side, type, time_in_force, price, qty, quote_qty, filled_qty, filled_quote, remaining_qty, hold_asset, hold_amount, hold_remaining, status, reject_reason, cancel_reason, seq, correlation_id, created_at, updated_at FROM trading.orders
WHERE tenant_id = $1 AND account_id = $2 AND client_order_id = $3
`

type GetOrderByClientIDParams struct {
	TenantID      string
	AccountID     string
	ClientOrderID string
}

func (q *Queries) GetOrderByClientID(ctx context.Context, arg GetOrderByClientIDParams) (TradingOrder, error) {
	row := q.db.QueryRow(ctx, GetOrderByClientID, arg.TenantID, arg.AccountID, arg.ClientOrderID)
	var i TradingOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.MarketID,
		&i.MarketSymbol,
		&i.ClientOrderID,
		&i.Side,
		&i.Type,
		&i.TimeInForce,
		&i.Price,
		&i.Qty,
		&i.QuoteQty,
		&i.FilledQty,
		&i.FilledQuote,
		&i.RemainingQty,
		&i.HoldAsset,
		&i.HoldAmount,
		&i.HoldRemaining,
		&i.Status,
		&i.RejectReason,
		&i.CancelReason,
		&i.Seq,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const InsertOrder = `-- name: InsertOrder :one
INSERT INTO trading.orders (
    id, tenant_id, account_id, market_id, market_symbol, client_order_id,
    side, type, time_in_force, price, qty, quote_qty,
    filled_qty, filled_quote, remaining_qty,
    hold_asset, hold_amount, hold_remaining,
    status, reject_reason, cancel_reason, seq, correlation_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21, $22, $23, $24
)
RETURNING id, tenant_id, account_id, market_id, market_symbol, client_order_id, side, type, time_in_force, price, qty, quote_qty, filled_qty, filled_quote, remaining_qty, hold_asset, hold_amount, hold_remaining, status, reject_reason, cancel_reason, seq, correlation_id, created_at, updated_at
`

type InsertOrderParams struct {
	ID            string
	TenantID      string
	AccountID     string
	MarketID      string
	MarketSymbol  string
	ClientOrderID string
	Side          string
	Type          string
	TimeInForce   string
	Price         pgtype.Numeric
	Qty           pgtype.Numeric
	QuoteQty      pgtype.Numeric
	FilledQty     pgtype.Numeric
	FilledQuote   pgtype.Numeric
	RemainingQty  pgtype.Numeric
	HoldAsset     string
	HoldAmount    pgtype.Numeric
	HoldRemaining pgtype.Numeric
	Status        string
	RejectReason  *string
	CancelReason  *string
	Seq           *int64
	CorrelationID *string
	CreatedAt     time.Time
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (TradingOrder, error) {
	row := q.db.QueryRow(ctx, InsertOrder,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.MarketID,
		arg.MarketSymbol,
		arg.ClientOrderID,
		arg.Side,
		arg.Type,
		arg.TimeInForce,
		arg.Price,
		arg.Qty,
		arg.QuoteQty,
		arg.FilledQty,
		arg.FilledQuote,
		arg.RemainingQty,
		arg.HoldAsset,
		arg.HoldAmount,
		arg.HoldRemaining,
		arg.Status,
		arg.RejectReason,
		arg.CancelReason,
		arg.Seq,
		arg.CorrelationID,
		arg.CreatedAt,
	)
	var i TradingOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.MarketID,
		&i.MarketSymbol,
		&i.ClientOrderID,
		&i.Side,
		&i.Type,
		&i.TimeInForce,
		&i.Price,
		&i.Qty,
		&i.QuoteQty,
		&i.FilledQty,
		&i.FilledQuote,
		&i.RemainingQty,
		&i.HoldAsset,
		&i.HoldAmount,
		&i.HoldRemaining,
		&i.Status,
		&i.RejectReason,
		&i.CancelReason,
		&i.Seq,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const InsertTrade = `-- name: InsertTrade :exec

INSERT INTO trading.trades (
    id, tenant_id, market_id, market_symbol, seq, idx,
    maker_order_id, taker_order_id, maker_account_id, taker_account_id, taker_side,
    price, qty, quote_qty, maker_fee, maker_fee_asset, taker_fee, taker_fee_asset, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18, $19
)
`

type InsertTradeParams struct {
	ID             string
	TenantID       string
	MarketID       string
	MarketSymbol   string
	Seq            int64
	Idx            int32
	MakerOrderID   string
	TakerOrderID   string
	MakerAccountID string
	TakerAccountID string
	TakerSide      string
	Price          pgtype.Numeric
	Qty            pgtype.Numeric
	QuoteQty       pgtype.Numeric
	MakerFee       pgtype.Numeric
	MakerFeeAsset  string
	TakerFee       pgtype.Numeric
	TakerFeeAsset  string
	CreatedAt      time.Time
}

// Trades ------------------------------------------------------------------
func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) error {
	_, err := q.db.Exec(ctx, InsertTrade,
		arg.ID,
		arg.TenantID,
		arg.MarketID,
		arg.MarketSymbol,
		arg.Seq,
		arg.Idx,
		arg.MakerOrderID,
		arg.TakerOrderID,
		arg.MakerAccountID,
		arg.TakerAccountID,
		arg.TakerSide,
		arg.Price,
		arg.Qty,
		arg.QuoteQty,
		arg.MakerFee,
		arg.MakerFeeAsset,
		arg.TakerFee,
		arg.TakerFeeAsset,
		arg.CreatedAt,
	)
	return err
}

const ListFillsByAccount = `-- name: ListFillsByAccount :many
SELECT id, tenant_id, market_id, market_symbol, seq, idx, maker_order_id, taker_order_id, maker_account_id, taker_account_id, taker_side, price, qty, quote_qty, maker_fee, maker_fee_asset, taker_fee, taker_fee_asset, created_at FROM trading.trades
WHERE tenant_id = $1
  AND (maker_account_id = $2 OR taker_account_id = $2)
  AND ($5::text = '' OR market_symbol = $5::text)
  AND ($6::text = ''
       OR (maker_order_id = $6::text AND maker_account_id = $2)
       OR (taker_order_id = $6::text AND taker_account_id = $2))
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListFillsByAccountParams struct {
	TenantID       string
	MakerAccountID string
	Limit          int32
	Offset         int32
	MarketSymbol   string
	OrderID        string
}

func (q *Queries) ListFillsByAccount(ctx context.Context, arg ListFillsByAccountParams) ([]TradingTrade, error) {
	rows, err := q.db.Query(ctx, ListFillsByAccount,
		arg.TenantID,
		arg.MakerAccountID,
		arg.Limit,
		arg.Offset,
		arg.MarketSymbol,
		arg.OrderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradingTrade{}
	for rows.Next() {
		var i TradingTrade
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MarketID,
			&i.MarketSymbol,
			&i.Seq,
			&i.Idx,
			&i.MakerOrderID,
			&i.TakerOrderID,
			&i.MakerAccountID,
			&i.TakerAccountID,
			&i.TakerSide,
			&i.Price,
			&i.Qty,
			&i.QuoteQty,
			&i.MakerFee,
			&i.MakerFeeAsset,
			&i.TakerFee,
			&i.TakerFeeAsset,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOpenOrdersByMarket = `-- name: ListOpenOrdersByMarket :many
SELECT id, tenant_id, account_id, market_id, market_symbol, client_order_id, side, type, time_in_force, price, qty, quote_qty, filled_qty, filled_quote, remaining_qty, hold_asset, hold_amount, hold_remaining, status, reject_reason, cancel_reason, seq, correlation_id, created_at, updated_at FROM trading.orders
WHERE market_id = $1 AND status IN ('open', 'partially_filled')
ORDER BY seq
`

// The engine rebuilds the book from these rows on start (ADR-0002).
func (q *Queries) ListOpenOrdersByMarket(ctx context.Context, marketID string) ([]TradingOrder, error) {
	rows, err := q.db.Query(ctx, ListOpenOrdersByMarket, marketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradingOrder{}
	for rows.Next() {
		var i TradingOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.MarketID,
			&i.MarketSymbol,
			&i.ClientOrderID,
			&i.Side,
			&i.Type,
			&i.TimeInForce,
			&i.Price,
			&i.Qty,
			&i.QuoteQty,
			&i.FilledQty,
			&i.FilledQuote,
			&i.RemainingQty,
			&i.HoldAsset,
			&i.HoldAmount,
			&i.HoldRemaining,
			&i.Status,
			&i.RejectReason,
			&i.CancelReason,
			&i.Seq,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOrdersByAccount = `-- name: ListOrdersByAccount :many
SELECT id, tenant_id, account_id, market_id, market_symbol, client_order_id, side, type, time_in_force, price, qty, quote_qty, filled_qty, filled_quote, remaining_qty, hold_asset, hold_amount, hold_remaining, status, reject_reason, cancel_reason, seq, correlation_id, created_at, updated_at FROM trading.orders
WHERE tenant_id = $1 AND account_id = $2
  AND ($5::text = '' OR market_symbol = $5::text)
  AND ($6::text = '' OR status = $6::text)
  AND ($7::boolean = false OR status IN ('open', 'partially_filled'))
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListOrdersByAccountParams struct {
	TenantID     string
	AccountID    string
	Limit        int32
	Offset       int32
	MarketSymbol string
	Status       string
	OpenOnly     bool
}

func (q *Queries) ListOrdersByAccount(ctx context.Context, arg ListOrdersByAccountParams) ([]TradingOrder, error) {
	rows, err := q.db.Query(ctx, ListOrdersByAccount,
		arg.TenantID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
		arg.MarketSymbol,
		arg.Status,
		arg.OpenOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradingOrder{}
	for rows.Next() {
		var i TradingOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.MarketID,
			&i.MarketSymbol,
			&i.ClientOrderID,
			&i.Side,
			&i.Type,
			&i.TimeInForce,
			&i.Price,
			&i.Qty,
			&i.QuoteQty,
			&i.FilledQty,
			&i.FilledQuote,
			&i.RemainingQty,
			&i.HoldAsset,
			&i.HoldAmount,
			&i.HoldRemaining,
			&i.Status,
			&i.RejectReason,
			&i.CancelReason,
			&i.Seq,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTradesByMarket = `-- name: ListTradesByMarket :many
SELECT id, tenant_id, market_id, market_symbol, seq, idx, maker_order_id, taker_order_id, maker_account_id, taker_account_id, taker_side, price, qty, quote_qty, maker_fee, maker_fee_asset, taker_fee, taker_fee_asset, created_at FROM trading.trades
WHERE tenant_id = $1 AND market_symbol = $2
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListTradesByMarketParams struct {
	TenantID     string
	MarketSymbol string
	Limit        int32
	Offset       int32
}

func (q *Queries) ListTradesByMarket(ctx context.Context, arg ListTradesByMarketParams) ([]TradingTrade, error) {
	rows, err := q.db.Query(ctx, ListTradesByMarket,
		arg.TenantID,
		arg.MarketSymbol,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradingTrade{}
	for rows.Next() {
		var i TradingTrade
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MarketID,
			&i.MarketSymbol,
			&i.Seq,
			&i.Idx,
			&i.MakerOrderID,
			&i.TakerOrderID,
			&i.MakerAccountID,
			&i.TakerAccountID,
			&i.TakerSide,
			&i.Price,
			&i.Qty,
			&i.QuoteQty,
			&i.MakerFee,
			&i.MakerFeeAsset,
			&i.TakerFee,
			&i.TakerFeeAsset,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTradesByOrder = `-- name: ListTradesByOrder :many
SELECT id, tenant_id, market_id, market_symbol, seq, idx, maker_order_id, taker_order_id, maker_account_id, taker_account_id, taker_side, price, qty, quote_qty, maker_fee, maker_fee_asset, taker_fee, taker_fee_asset, created_at FROM trading.trades
WHERE maker_order_id = $1 OR taker_order_id = $1
ORDER BY seq, idx
`

func (q *Queries) ListTradesByOrder(ctx context.Context, makerOrderID string) ([]TradingTrade, error) {
	rows, err := q.db.Query(ctx, ListTradesByOrder, makerOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TradingTrade{}
	for rows.Next() {
		var i TradingTrade
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MarketID,
			&i.MarketSymbol,
			&i.Seq,
			&i.Idx,
			&i.MakerOrderID,
			&i.TakerOrderID,
			&i.MakerAccountID,
			&i.TakerAccountID,
			&i.TakerSide,
			&i.Price,
			&i.Qty,
			&i.QuoteQty,
			&i.MakerFee,
			&i.MakerFeeAsset,
			&i.TakerFee,
			&i.TakerFeeAsset,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LockMarketSequence = `-- name: LockMarketSequence :one
SELECT last_seq FROM trading.market_sequences WHERE market_id = $1 FOR UPDATE
`

// The engine's per-command transaction (or group of commands) starts by
// locking the sequence row and comparing it with what it committed last:
// a second engine instance that advanced it is caught here, before any
// write, and the row lock serialises the two until one of them fails.
func (q *Queries) LockMarketSequence(ctx context.Context, marketID string) (int64, error) {
	row := q.db.QueryRow(ctx, LockMarketSequence, marketID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const SetMarketSequence = `-- name: SetMarketSequence :execrows
UPDATE trading.market_sequences
   SET last_seq = $2, updated_at = now()
 WHERE market_id = $1 AND last_seq = $3
`

type SetMarketSequenceParams struct {
	MarketID string
	ToSeq    int64
	FromSeq  int64
}

// The last statement before COMMIT: guarded like AdvanceMarketSequence,
// but from the sequence the transaction started at to the last one it
// consumed, however many commands that was.
func (q *Queries) SetMarketSequence(ctx context.Context, arg SetMarketSequenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, SetMarketSequence, arg.MarketID, arg.ToSeq, arg.FromSeq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const UpdateOrderProgress = `-- name: UpdateOrderProgress :one
UPDATE trading.orders
   SET filled_qty     = $2,
       filled_quote   = $3,
       remaining_qty  = $4,
       hold_remaining = $5,
       status         = $6,
       cancel_reason  = $7,
       updated_at     = now()
 WHERE id = $1
RETURNING id, tenant_id, account_id, market_id, market_symbol, client_order_id, side, type, time_in_force, price, qty, quote_qty, filled_qty, filled_quote, remaining_qty, hold_asset, hold_amount, hold_remaining, status, reject_reason, cancel_reason, seq, correlation_id, created_at, updated_at
`

type UpdateOrderProgressParams struct {
	ID            string
	FilledQty     pgtype.Numeric
	FilledQuote   pgtype.Numeric
	RemainingQty  pgtype.Numeric
	HoldRemaining pgtype.Numeric
	Status        string
	CancelReason  *string
}

// A maker after a fill (or the taker's own remainder): fills, remaining,
// what is still frozen and the resulting status.
func (q *Queries) UpdateOrderProgress(ctx context.Context, arg UpdateOrderProgressParams) (TradingOrder, error) {
	row := q.db.QueryRow(ctx, UpdateOrderProgress,
		arg.ID,
		arg.FilledQty,
		arg.FilledQuote,
		arg.RemainingQty,
		arg.HoldRemaining,
		arg.Status,
		arg.CancelReason,
	)
	var i TradingOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.MarketID,
		&i.MarketSymbol,
		&i.ClientOrderID,
		&i.Side,
		&i.Type,
		&i.TimeInForce,
		&i.Price,
		&i.Qty,
		&i.QuoteQty,
		&i.FilledQty,
		&i.FilledQuote,
		&i.RemainingQty,
		&i.HoldAsset,
		&i.HoldAmount,
		&i.HoldRemaining,
		&i.Status,
		&i.RejectReason,
		&i.CancelReason,
		&i.Seq,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
