// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const alreadyDelivered = `-- name: AlreadyDelivered :one
SELECT EXISTS (
    SELECT 1 FROM webhook.deliveries
    WHERE tenant_id = $1 AND endpoint_id = $2 AND event_id = $3 AND status = 'delivered'
)
`

type AlreadyDeliveredParams struct {
	TenantID   string
	EndpointID string
	EventID    string
}

// JetStream is at-least-once, so the same event arrives again after a
// restart or a nak. This is what stops the customer getting it twice.
func (q *Queries) AlreadyDelivered(ctx context.Context, arg AlreadyDeliveredParams) (bool, error) {
	row := q.db.QueryRow(ctx, alreadyDelivered, arg.TenantID, arg.EndpointID, arg.EventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAttempts = `-- name: CountAttempts :one
SELECT count(*) FROM webhook.deliveries
WHERE tenant_id = $1 AND endpoint_id = $2 AND event_id = $3
`

type CountAttemptsParams struct {
	TenantID   string
	EndpointID string
	EventID    string
}

// How many times this event has been tried against this endpoint, which is
// both the next attempt number and the retry budget check.
func (q *Queries) CountAttempts(ctx context.Context, arg CountAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttempts, arg.TenantID, arg.EndpointID, arg.EventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActiveEndpoints = `-- name: ListActiveEndpoints :many
SELECT id, url, secret_enc, events, label
FROM webhook.endpoints
WHERE tenant_id = $1 AND status = 'active'
ORDER BY created_at
`

type ListActiveEndpointsRow struct {
	ID        string
	Url       string
	SecretEnc []byte
	Events    []string
	Label     string
}

// Every endpoint that could want an event, for one tenant. Filtering by
// event_type happens in Go against the events array: the array is small, and
// a GIN index maintained for a predicate that changes with every event buys
// nothing at this size.
func (q *Queries) ListActiveEndpoints(ctx context.Context, tenantID string) ([]ListActiveEndpointsRow, error) {
	rows, err := q.db.Query(ctx, listActiveEndpoints, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEndpointsRow{}
	for rows.Next() {
		var i ListActiveEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.SecretEnc,
			&i.Events,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAttempt = `-- name: RecordAttempt :one
INSERT INTO webhook.deliveries (
    tenant_id, endpoint_id, event_id, event_type, attempt, status,
    response_status, error, delivered_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type RecordAttemptParams struct {
	TenantID       string
	EndpointID     string
	EventID        string
	EventType      string
	Attempt        int32
	Status         string
	ResponseStatus *int32
	Error          string
	DeliveredAt    pgtype.Timestamptz
}

// One row per try. The unique index on (tenant, endpoint, event, attempt)
// makes a re-run of the same attempt a conflict rather than a second row, so
// a crash between sending and recording cannot double-count.
func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) (string, error) {
	row := q.db.QueryRow(ctx, recordAttempt,
		arg.TenantID,
		arg.EndpointID,
		arg.EventID,
		arg.EventType,
		arg.Attempt,
		arg.Status,
		arg.ResponseStatus,
		arg.Error,
		arg.DeliveredAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
