// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDue = `-- name: ClaimDue :many
SELECT q.tenant_id, q.endpoint_id, q.event_id, q.event_type, q.body, q.attempts,
       e.url, e.secret_enc
FROM webhook.queue q
JOIN webhook.endpoints e ON e.id = q.endpoint_id
WHERE q.tenant_id = $1 AND q.next_attempt_at <= now() AND e.status = 'active'
ORDER BY q.next_attempt_at
LIMIT $2
FOR UPDATE OF q SKIP LOCKED
`

type ClaimDueParams struct {
	TenantID string
	Limit    int32
}

type ClaimDueRow struct {
	TenantID   string
	EndpointID string
	EventID    string
	EventType  string
	Body       []byte
	Attempts   int32
	Url        string
	SecretEnc  []byte
}

// What is owed now. FOR UPDATE SKIP LOCKED so two workers can drain the same
// queue without either waiting on the other or sending the same event twice.
func (q *Queries) ClaimDue(ctx context.Context, arg ClaimDueParams) ([]ClaimDueRow, error) {
	rows, err := q.db.Query(ctx, claimDue, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueRow{}
	for rows.Next() {
		var i ClaimDueRow
		if err := rows.Scan(
			&i.TenantID,
			&i.EndpointID,
			&i.EventID,
			&i.EventType,
			&i.Body,
			&i.Attempts,
			&i.Url,
			&i.SecretEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dequeue = `-- name: Dequeue :exec
DELETE FROM webhook.queue
WHERE tenant_id = $1 AND endpoint_id = $2 AND event_id = $3
`

type DequeueParams struct {
	TenantID   string
	EndpointID string
	EventID    string
}

// Delivered, or out of schedule. Either way nothing more is owed, and what
// survives is the delivery rows -- the queue entry held no history.
func (q *Queries) Dequeue(ctx context.Context, arg DequeueParams) error {
	_, err := q.db.Exec(ctx, dequeue, arg.TenantID, arg.EndpointID, arg.EventID)
	return err
}

const enqueue = `-- name: Enqueue :execrows
INSERT INTO webhook.queue (tenant_id, endpoint_id, event_id, event_type, body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type EnqueueParams struct {
	TenantID   string
	EndpointID string
	EventID    string
	EventType  string
	Body       []byte
}

// Idempotent under JetStream's at-least-once redelivery: the primary key is
// (tenant, endpoint, event), so the same event arriving twice is a no-op
// rather than a second POST. Returns 0 when it was already queued.
func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueue,
		arg.TenantID,
		arg.EndpointID,
		arg.EventID,
		arg.EventType,
		arg.Body,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveEndpoints = `-- name: ListActiveEndpoints :many
SELECT id, url, secret_enc, events, label
FROM webhook.endpoints
WHERE tenant_id = $1 AND status = 'active'
ORDER BY created_at
`

type ListActiveEndpointsRow struct {
	ID        string
	Url       string
	SecretEnc []byte
	Events    []string
	Label     string
}

// Every endpoint that could want an event, for one tenant. Filtering by
// event_type happens in Go against the events array: the array is small, and
// a GIN index maintained for a predicate that changes with every event buys
// nothing at this size.
func (q *Queries) ListActiveEndpoints(ctx context.Context, tenantID string) ([]ListActiveEndpointsRow, error) {
	rows, err := q.db.Query(ctx, listActiveEndpoints, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEndpointsRow{}
	for rows.Next() {
		var i ListActiveEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.SecretEnc,
			&i.Events,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAttempt = `-- name: RecordAttempt :exec
INSERT INTO webhook.deliveries (
    tenant_id, endpoint_id, event_id, event_type, attempt, status,
    response_status, error, duration_ms, delivered_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT DO NOTHING
`

type RecordAttemptParams struct {
	TenantID       string
	EndpointID     string
	EventID        string
	EventType      string
	Attempt        int32
	Status         string
	ResponseStatus *int32
	Error          string
	DurationMs     int32
	DeliveredAt    pgtype.Timestamptz
}

// One row per try, append-only. The unique index on
// (tenant, endpoint, event, attempt) makes a re-run of the same attempt a
// conflict rather than a second row, so a crash between sending and recording
// cannot double-count.
func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) error {
	_, err := q.db.Exec(ctx, recordAttempt,
		arg.TenantID,
		arg.EndpointID,
		arg.EventID,
		arg.EventType,
		arg.Attempt,
		arg.Status,
		arg.ResponseStatus,
		arg.Error,
		arg.DurationMs,
		arg.DeliveredAt,
	)
	return err
}

const rescheduleQueued = `-- name: RescheduleQueued :exec
UPDATE webhook.queue
SET attempts = attempts + 1, next_attempt_at = $4
WHERE tenant_id = $1 AND endpoint_id = $2 AND event_id = $3
`

type RescheduleQueuedParams struct {
	TenantID      string
	EndpointID    string
	EventID       string
	NextAttemptAt time.Time
}

// The attempt failed and the schedule has more steps left.
func (q *Queries) RescheduleQueued(ctx context.Context, arg RescheduleQueuedParams) error {
	_, err := q.db.Exec(ctx, rescheduleQueued,
		arg.TenantID,
		arg.EndpointID,
		arg.EventID,
		arg.NextAttemptAt,
	)
	return err
}
