/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a user and open a spot account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token
         * @description The presented refresh token is revoked and a new pair is issued. Presenting an already-rotated token revokes every session of the user.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Idempotent; unknown tokens are ignored. Access tokens stay valid until they expire (15 min).
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public keys that verify access tokens */
        get: operations["getJWKS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's API keys */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Create an API key
         * @description Requires a session (JWT); API keys cannot mint API keys. The secret is returned once.
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's user and spot account */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balances of the caller's spot account */
        get: operations["listBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledger/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Journal entries that touched the caller's account */
        get: operations["listLedgerEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deposit-address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's deposit address for an asset
         * @description Returns the address to send deposits to. One address per account per chain: every asset on the same chain, native and ERC-20 alike, shares it, and repeated calls return the same address. Addresses are pre-generated, so a 503 means the pool is momentarily empty and the call should be retried.
         */
        get: operations["getDepositAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's deposits, newest first
         * @description A deposit is only money once its status is `credited`. `detected` and `confirming` mean it has been seen on chain but not yet posted; `orphaned` means the block carrying it was reorged away and it may still come back; `dropped` means it did not.
         */
        get: operations["listDeposits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's withdrawals, newest first
         * @description A withdrawal's `status` follows docs/plan-v1.0.md §6.4.2. `requested` has only been recorded; `pending_review` is waiting for an administrator; `auto_approved` and `approved` are cleared but not yet funded; `funds_locked` means the amount is held and the withdrawal is queued for signing. `rejected` and `failed` are terminal, and the funds were never or no longer held.
         */
        get: operations["listWithdrawals"];
        put?: never;
        /**
         * Request a withdrawal
         * @description Records a withdrawal request. Nothing is held and nothing is signed
         *     here: the chain role applies the withdrawal policy next, and either
         *     clears it automatically or queues it for an administrator.
         *
         *     `Idempotency-Key` is required and scoped to the account. Resending the
         *     same request with the same key returns the original withdrawal with
         *     **200**; reusing the key with a different asset, amount or destination
         *     is **422**. The key never expires — there is no window after which the
         *     same key would create a second withdrawal.
         *
         *     `to_address` may be given in any casing, but a mixed-case address must
         *     pass its EIP-55 checksum: that casing *is* a checksum, and accepting a
         *     wrong one would send funds to a mistyped address.
         *
         *     `amount` is what the destination receives. The account is debited
         *     `amount + fee`, and the response says what `fee` was quoted. The
         *     available-balance check covers the total, so a balance that covers the
         *     amount but not the fee is rejected here rather than minutes later.
         *     The asset's minimum withdrawal is compared against `amount` alone.
         */
        post: operations["createWithdrawal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List assets
         * @description Returns every listed asset, ordered by symbol.
         */
        get: operations["listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List markets
         * @description Returns every market that is not delisted, ordered by symbol.
         */
        get: operations["listMarkets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one market by symbol */
        get: operations["getMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{symbol}/depth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated order book */
        get: operations["getDepth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{symbol}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent public trades */
        get: operations["listTrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{symbol}/ticker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 24-hour ticker
         * @description Rolling 24-hour summary folded from the market's 1-minute candles:
         *     last price, the open 24 hours ago, high, low, base and quote volume,
         *     trade count and the change. The price fields are omitted when the
         *     window holds no trade. Served from persisted candles, so it lags the last
         *     trade by up to the worker's poll interval (about a second).
         */
        get: operations["getTicker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{symbol}/klines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candles (OHLCV)
         * @description One candle per bucket of `[from, to)`, oldest first, gaps filled with
         *     flat candles that carry the previous close (`trades` is `0` on those).
         *     Buckets are aligned to UTC; a day starts at 00:00 UTC. `to` defaults
         *     to now and `from` to `to − limit × interval`; a range wider than
         *     `limit` buckets is cut at `limit` from `from`.
         */
        get: operations["listKlines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's orders */
        get: operations["listOrders"];
        put?: never;
        /**
         * Place an order
         * @description Limit orders carry `price` and `qty`; market sells carry `qty`; market
         *     buys carry `quote_qty` (the quote budget). The response is the order in
         *     its state right after the command with the trades it produced as
         *     taker. Business rejections (tick, step, min notional, balance, market
         *     status) are **201 with `status: rejected`**, not errors.
         *
         *     `client_order_id` is idempotent per account: resending the same
         *     request returns the original order with **200**; reusing the id with
         *     a different request is **422**.
         */
        post: operations["placeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of the caller's orders with its trades */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        /**
         * Cancel an order
         * @description Idempotent — a terminal order is returned as it is. The response is the order after the cancel.
         */
        delete: operations["cancelOrder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's fills (its side of each trade) */
        get: operations["listFills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Arbitrary-precision decimal serialized as a string, at most 18 integer
         *     and 18 fractional digits (Postgres NUMERIC(36,18)). Never a JSON number.
         * @example 1990.00
         */
        Amount: string;
        RegisterRequest: {
            /**
             * Format: email
             * @example alice@example.com
             */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        Session: {
            user_id: string;
            /** @description The spot account every trading call is keyed by */
            account_id: string;
            /** @enum {string} */
            role: "user" | "admin";
            /** @description JWT, send as `Authorization: Bearer <access_token>` */
            access_token: string;
            /** @example Bearer */
            token_type: string;
            /**
             * Format: int64
             * @description Access token lifetime in seconds
             */
            expires_in: number;
            /** Format: date-time */
            expires_at: string;
            /** @description Opaque, single use; rotate with `/v1/auth/refresh` */
            refresh_token: string;
        };
        /** @description RFC 7517 key set; keys are OKP/Ed25519 with `use: sig` */
        JWKS: {
            keys: {
                [key: string]: unknown;
            }[];
        };
        /** @enum {string} */
        Scope: "read" | "trade" | "withdraw";
        APIKey: {
            id: string;
            /**
             * @description Public identifier sent in `X-API-KEY`
             * @example ak_3f1c9a2b7d4e6f8a0b1c2d3e
             */
            key_id: string;
            label: string;
            scopes: components["schemas"]["Scope"][];
            /** @description IPs or CIDRs the key may be used from; empty means any */
            ip_allowlist: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string;
            /** Format: date-time */
            revoked_at?: string;
        };
        APIKeyList: {
            api_keys: components["schemas"]["APIKey"][];
        };
        CreateAPIKeyRequest: {
            label?: string;
            scopes: components["schemas"]["Scope"][];
            ip_allowlist?: string[];
        };
        CreatedAPIKey: components["schemas"]["APIKey"] & {
            /** @description HMAC secret, shown exactly once */
            secret: string;
        };
        Account: {
            user_id: string;
            account_id: string;
            email: string;
            /** @enum {string} */
            role: "user" | "admin";
            /**
             * Format: int32
             * @description 0–2, written by the operator's systems through the admin API
             */
            kyc_level: number;
            /** @enum {string} */
            status: "active" | "frozen";
            /** Format: date-time */
            created_at: string;
        };
        Balance: {
            asset: string;
            available: components["schemas"]["Amount"];
            hold: components["schemas"]["Amount"];
            total: components["schemas"]["Amount"];
        };
        DepositAddress: {
            /** @example ETH */
            asset: string;
            /**
             * Format: int64
             * @description EVM chain the address lives on.
             * @example 31337
             */
            chain_id: number;
            /**
             * @description EIP-55 checksummed address. Send only assets of this chain to it.
             * @example 0x9858EfFD232B4033E47d90003D41EC34EcaEda94
             */
            address: string;
        };
        Deposit: {
            id: string;
            /** @example ETH */
            asset: string;
            amount: components["schemas"]["Amount"];
            /** @description What was deducted from `amount` before crediting, or null until the deposit is credited -- unlike a withdrawal fee this one is computed when the money is credited, not when it is first seen. `0` unless the operator has set a rate; deposits are free by default. */
            fee?: components["schemas"]["Amount"] | null;
            /** @description What became the account's balance: `amount - fee`. Null until credited. `amount` stays what the chain delivered, so the two can be reconciled independently. */
            credited_amount?: components["schemas"]["Amount"] | null;
            /** @description The deposit address the funds arrived at, lower-case. Note that this is *not* the form `GET /v1/deposit-address` returns: that one is EIP-55 checksummed so a wallet can catch a mistyped paste, while everything read back out of the chain tables is normalised. Compare the two only after deciding which representation you want. */
            address: string;
            tx_hash: string;
            /**
             * Format: int32
             * @description ERC-20 log index, or -1 for a native transfer.
             */
            log_index: number;
            /**
             * Format: int64
             * @description Where it currently sits; a reorg can change this.
             */
            block_number: number;
            /** Format: int32 */
            confirmations: number;
            /**
             * Format: int32
             * @description What this asset needs before it is credited.
             */
            required_confirmations: number;
            /**
             * @description detected, confirming, credited, orphaned, dropped or reversed. Open for new states.
             * @example credited
             */
            status: string;
            /** Format: date-time */
            credited_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CreateWithdrawalRequest: {
            /** @example ETH */
            asset: string;
            amount: components["schemas"]["Amount"];
            /**
             * @description Destination address. Any casing; a mixed-case one must pass EIP-55.
             * @example 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
             */
            to_address: string;
        };
        Withdrawal: {
            id: string;
            /** @example ETH */
            asset: string;
            amount: components["schemas"]["Amount"];
            /**
             * @description What this withdrawal is charged, on top of `amount`. The destination receives `amount`; the account is debited `amount + fee`. Quoted when the request was accepted and never recomputed, so changing the rate does not reprice a withdrawal already in flight.
             *     It is the account's money until the transaction is confirmed. On every path that does not confirm -- a broadcast that failed, a withdrawal displaced by a cancellation, an operator refund -- it goes back to the available balance. `0` unless the operator has set a rate.
             */
            fee: components["schemas"]["Amount"];
            /**
             * @description The asset `fee` is denominated in, which is `asset`. A USDC withdrawal is charged in USDC even though its gas is paid in ETH.
             * @example ETH
             */
            fee_asset: string;
            /** @description The destination, lower-case. */
            to_address: string;
            /** Format: int64 */
            chain_id: number;
            /**
             * @description requested, policy_check, auto_approved, pending_review, approved, funds_locked, signed, broadcast, confirmed, rejected or failed. Open for new states.
             * @example pending_review
             */
            status: string;
            /** @description The on-chain transaction, once one exists. While a stuck withdrawal is being cancelled this is the displacing transaction, because that is the one whose fate decides the money. */
            tx_hash?: string | null;
            /** @description Why it failed; null unless the status is failed. */
            failure_reason?: string | null;
            /** @description What the administrator wrote when approving or rejecting. */
            review_note?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        WithdrawalList: {
            withdrawals: components["schemas"]["Withdrawal"][];
        };
        DepositList: {
            deposits: components["schemas"]["Deposit"][];
        };
        BalanceList: {
            balances: components["schemas"]["Balance"][];
        };
        Posting: {
            asset: string;
            /** @enum {string} */
            bucket: "available" | "hold";
            /** @enum {string} */
            direction: "debit" | "credit";
            amount: components["schemas"]["Amount"];
        };
        LedgerEntry: {
            /** Format: int64 */
            id: number;
            /** @description hold | release | settle | credit | adjustment | … */
            kind: string;
            ref_type?: string;
            ref_id?: string;
            reason?: string;
            /** Format: date-time */
            created_at: string;
            /** @description Only the caller's own postings of the entry */
            postings: components["schemas"]["Posting"][];
        };
        LedgerEntryList: {
            entries: components["schemas"]["LedgerEntry"][];
        };
        /**
         * @description `disabled` assets are hidden from trading and deposits.
         * @enum {string}
         */
        AssetStatus: "active" | "disabled";
        /** @description A currency the exchange lists. */
        Asset: {
            /** @example USDC */
            symbol: string;
            /** @example USD Coin (mock) */
            name: string;
            /**
             * Format: int64
             * @description EVM chain id the asset lives on (31337 = anvil, 11155111 = Sepolia).
             * @example 31337
             */
            chain_id: number;
            /**
             * @description ERC-20 contract address; `null` for the chain's native coin.
             * @example 0x5FbDB2315678afecb367f032d93F642f64180aa3
             */
            contract_address: string | null;
            is_native: boolean;
            /**
             * Format: int32
             * @description Number of fractional digits carried internally (ETH 18, USDC 6).
             */
            scale: number;
            /**
             * Format: int32
             * @description Suggested number of fractional digits for display.
             */
            display_scale: number;
            /** Format: int32 */
            required_confirmations: number;
            min_deposit: components["schemas"]["Amount"];
            min_withdrawal: components["schemas"]["Amount"];
            /** @description The flat part of the withdrawal fee. The total charged is `withdrawal_fee + ceil(amount * withdrawal_fee_bps / 10000)`, rounded up at `scale`, and it is added to the amount rather than taken out of it: the destination receives `amount` and the account is debited the sum. */
            withdrawal_fee: components["schemas"]["Amount"];
            /**
             * Format: int32
             * @description The proportional part of the withdrawal fee, in basis points of the amount. `0` unless the operator has set a rate.
             * @example 0
             */
            withdrawal_fee_bps: number;
            deposit_enabled: boolean;
            withdraw_enabled: boolean;
            status: components["schemas"]["AssetStatus"];
        };
        AssetList: {
            assets: components["schemas"]["Asset"][];
        };
        /**
         * @description - `active`: accepts orders and cancels
         *     - `halted`: rejects new orders, keeps resting orders, accepts cancels
         *     - `cancel_only`: accepts cancels only
         *     - `delisted`: hidden (never returned by this API)
         * @enum {string}
         */
        MarketStatus: "active" | "halted" | "cancel_only" | "delisted";
        /**
         * @description What happens when a new order would trade against the same account's resting order. v1 implements `cancel_newest`.
         * @enum {string}
         */
        SelfTradePolicy: "cancel_newest" | "allow" | "cancel_oldest";
        /** @description A spot trading pair with its precision and fee configuration. */
        Market: {
            /** @example ETH-USDC */
            symbol: string;
            /**
             * @description Symbol of the asset being bought or sold.
             * @example ETH
             */
            base_asset: string;
            /**
             * @description Symbol of the asset prices are expressed in.
             * @example USDC
             */
            quote_asset: string;
            price_tick: components["schemas"]["Amount"];
            qty_step: components["schemas"]["Amount"];
            min_notional: components["schemas"]["Amount"];
            /** @description Maximum order quantity; absent when unlimited. */
            max_qty?: components["schemas"]["Amount"];
            /**
             * Format: int32
             * @description Market-order protection band relative to the best price, in basis points; absent when unlimited.
             */
            max_slippage_bps?: number;
            /**
             * Format: int32
             * @description Maker fee in basis points, charged in the asset the maker receives.
             * @example 10
             */
            maker_bps: number;
            /**
             * Format: int32
             * @description Taker fee in basis points, charged in the asset the taker receives.
             * @example 20
             */
            taker_bps: number;
            self_trade_policy: components["schemas"]["SelfTradePolicy"];
            status: components["schemas"]["MarketStatus"];
        };
        MarketList: {
            markets: components["schemas"]["Market"][];
        };
        /** @enum {string} */
        Side: "buy" | "sell";
        /** @enum {string} */
        OrderType: "limit" | "market";
        /**
         * @description `gtc` rests the unfilled remainder in the book; `ioc` cancels it. Market orders are always `ioc`.
         * @enum {string}
         */
        TimeInForce: "gtc" | "ioc";
        /**
         * @description docs/plan-v1.0.md §6.2; `filled`, `cancelled` and `rejected` are terminal
         * @enum {string}
         */
        OrderStatus: "open" | "partially_filled" | "filled" | "cancelled" | "rejected";
        PlaceOrderRequest: {
            /** @description Idempotency key per account; reuse with different content is 422 */
            client_order_id: string;
            /** @example ETH-USDC */
            market: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            time_in_force?: components["schemas"]["TimeInForce"];
            /** @description Limit orders only; must be a multiple of `price_tick` */
            price?: components["schemas"]["Amount"];
            /** @description Base quantity (limit orders and market sells); multiple of `qty_step` */
            qty?: components["schemas"]["Amount"];
            /** @description Quote budget of a market buy */
            quote_qty?: components["schemas"]["Amount"];
        };
        Order: {
            /** @description ULID */
            id: string;
            client_order_id: string;
            market: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            time_in_force: components["schemas"]["TimeInForce"];
            /** @description Absent for market orders */
            price?: components["schemas"]["Amount"];
            /** @description Absent for market buys */
            qty?: components["schemas"]["Amount"];
            /** @description Quote budget of a market buy */
            quote_qty?: components["schemas"]["Amount"];
            filled_qty: components["schemas"]["Amount"];
            filled_quote: components["schemas"]["Amount"];
            remaining_qty: components["schemas"]["Amount"];
            /** @description Asset frozen for this order (quote for buys, base for sells) */
            hold_asset: string;
            hold_amount: components["schemas"]["Amount"];
            hold_remaining: components["schemas"]["Amount"];
            status: components["schemas"]["OrderStatus"];
            /** @description invalid_price_tick | invalid_qty_step | below_min_notional | above_max_qty | market_not_active | insufficient_balance | empty_book | quote_qty_too_small | account_frozen | policy_denied */
            reject_reason?: string;
            /** @description user | ioc | self_trade | price_protection */
            cancel_reason?: string;
            /**
             * Format: int64
             * @description Engine sequence of the command that processed the order
             */
            seq?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OrderList: {
            orders: components["schemas"]["Order"][];
        };
        /** @description One public fill; price is always the resting (maker) price */
        Trade: {
            trade_id: string;
            market: string;
            price: components["schemas"]["Amount"];
            qty: components["schemas"]["Amount"];
            quote_qty: components["schemas"]["Amount"];
            taker_side: components["schemas"]["Side"];
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            executed_at: string;
        };
        TradeList: {
            trades: components["schemas"]["Trade"][];
        };
        Fill: components["schemas"]["Trade"] & {
            order_id: string;
            side: components["schemas"]["Side"];
            is_maker: boolean;
            fee: components["schemas"]["Amount"];
            fee_asset: string;
        };
        FillList: {
            fills: components["schemas"]["Fill"][];
        };
        OrderResult: {
            order: components["schemas"]["Order"];
            /** @description Fills of this order (for `POST`, those produced by the command) */
            trades: components["schemas"]["Fill"][];
        };
        Level: {
            price: components["schemas"]["Amount"];
            qty: components["schemas"]["Amount"];
            /** Format: int32 */
            orders: number;
        };
        Depth: {
            market: string;
            /**
             * Format: int64
             * @description Engine sequence the snapshot reflects; WebSocket depth deltas
             *     continue from it (docs/ws-api.md). The snapshot may come from the
             *     stream role's cache rather than the engine, at most a few hundred
             *     milliseconds behind, and is always consistent with its levels.
             */
            last_seq: number;
            /** @description Best (highest) bid first */
            bids: components["schemas"]["Level"][];
            /** @description Best (lowest) ask first */
            asks: components["schemas"]["Level"][];
        };
        /**
         * @description Candle width; buckets are aligned to UTC
         * @enum {string}
         */
        KlineInterval: "1m" | "5m" | "15m" | "1h" | "1d";
        /** @description One OHLCV bucket. `trades` is 0 on a synthesized candle that carries the previous close through an empty bucket. */
        Kline: {
            market: string;
            interval: components["schemas"]["KlineInterval"];
            /**
             * Format: date-time
             * @description Bucket start (UTC)
             */
            start: string;
            open: components["schemas"]["Amount"];
            high: components["schemas"]["Amount"];
            low: components["schemas"]["Amount"];
            close: components["schemas"]["Amount"];
            volume: components["schemas"]["Amount"];
            quote_volume: components["schemas"]["Amount"];
            /** Format: int64 */
            trades: number;
        };
        KlineList: {
            market: string;
            interval: components["schemas"]["KlineInterval"];
            /** @description Oldest first, one per bucket */
            klines: components["schemas"]["Kline"][];
        };
        /** @description Rolling 24-hour summary. The price fields are omitted when the window holds no trade. */
        Ticker: {
            market: string;
            last_price?: components["schemas"]["Amount"];
            /** @description First trade price inside the window */
            open?: components["schemas"]["Amount"];
            high?: components["schemas"]["Amount"];
            low?: components["schemas"]["Amount"];
            /** @description last_price − open */
            change?: components["schemas"]["Amount"];
            /** @description change / open × 100, truncated to two decimals */
            change_pct?: components["schemas"]["Amount"];
            /** @description Base volume inside the window */
            volume: components["schemas"]["Amount"];
            quote_volume: components["schemas"]["Amount"];
            /** Format: int64 */
            trades: number;
            /**
             * Format: date-time
             * @description When the summary was computed
             */
            at: string;
        };
        /** @description RFC 7807 problem details. */
        Problem: {
            /**
             * @description URI reference identifying the problem type; `about:blank` when the HTTP status says it all.
             * @example about:blank
             */
            type: string;
            /** @example Not Found */
            title: string;
            /** @example 404 */
            status: number;
            /** @example market NOPE-USDC does not exist */
            detail?: string;
            /**
             * @description Request path the problem occurred on.
             * @example /v1/markets/NOPE-USDC
             */
            instance?: string;
            /**
             * @description Value of `X-Request-Id`; quote it when reporting problems.
             * @example 7d5a9c1e0b2f4a6c8e1d3f5a7b9c0d2e
             */
            correlation_id?: string;
        };
    };
    responses: {
        /** @description Malformed request (shape, missing fields, invalid amounts) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The credential lacks the scope, or the key is not allowed from this address */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The email is already registered */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request is well-formed but violates a rule (weak password, `client_order_id` reused with different content) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded; retry after `Retry-After` seconds */
        TooManyRequests: {
            headers: {
                /** @description Seconds until a token is available */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The trading engine is not reachable or not ready; retry with the same `client_order_id` */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected server error; retry with the same `X-Request-Id` and quote the `correlation_id` when reporting */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Market symbol in `BASE-QUOTE` form, e.g. `ETH-USDC`. Case-sensitive. */
        MarketSymbol: string;
        /** @description Order id (ULID) */
        OrderID: string;
        /** @description Page size (default 100, max 500) */
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered; a session is returned so the client can start immediately */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Revoked (or already unknown) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getJWKS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON Web Key Set (RFC 7517) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JWKS"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keys (secrets are never returned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAPIKeyRequest"];
            };
        };
        responses: {
            /** @description Created; store the secret now */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedAPIKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per asset ever touched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listLedgerEntries: {
        parameters: {
            query?: {
                /** @description Page size (default 100, max 500) */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entries, newest first, with the caller's postings only */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getDepositAddress: {
        parameters: {
            query: {
                /** @description Asset symbol, used to pick the chain and to check deposits are open. */
                asset: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's deposit address */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositAddress"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listDeposits: {
        parameters: {
            query?: {
                /** @description Page size (default 100, max 500) */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deposits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listWithdrawals: {
        parameters: {
            query?: {
                /** @description Page size (default 100, max 500) */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createWithdrawal: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-chosen key, unique per request within the account. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWithdrawalRequest"];
            };
        };
        responses: {
            /** @description The withdrawal this Idempotency-Key already created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Withdrawal"];
                };
            };
            /** @description Withdrawal recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Withdrawal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listMarkets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Market list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getMarket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Market symbol in `BASE-QUOTE` form, e.g. `ETH-USDC`. Case-sensitive. */
                symbol: components["parameters"]["MarketSymbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Market */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Market"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getDepth: {
        parameters: {
            query?: {
                /** @description Levels per side (default 20, max 200) */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Market symbol in `BASE-QUOTE` form, e.g. `ETH-USDC`. Case-sensitive. */
                symbol: components["parameters"]["MarketSymbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Depth snapshot with the engine sequence it reflects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Depth"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listTrades: {
        parameters: {
            query?: {
                /** @description Page size (default 100, max 500) */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                /** @description Market symbol in `BASE-QUOTE` form, e.g. `ETH-USDC`. Case-sensitive. */
                symbol: components["parameters"]["MarketSymbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trades, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeList"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getTicker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Market symbol in `BASE-QUOTE` form, e.g. `ETH-USDC`. Case-sensitive. */
                symbol: components["parameters"]["MarketSymbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticker */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticker"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listKlines: {
        parameters: {
            query: {
                interval: components["schemas"]["KlineInterval"];
                /** @description Start of the range (inclusive), aligned down to a bucket */
                from?: string;
                /** @description End of the range (exclusive); default now */
                to?: string;
                /** @description Maximum candles returned (default 500, max 1000) */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Market symbol in `BASE-QUOTE` form, e.g. `ETH-USDC`. Case-sensitive. */
                symbol: components["parameters"]["MarketSymbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candles, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KlineList"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                market?: string;
                status?: components["schemas"]["OrderStatus"];
                /** @description Only `open` and `partially_filled` orders */
                open_only?: boolean;
                /** @description Page size (default 100, max 500) */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    placeOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceOrderRequest"];
            };
        };
        responses: {
            /** @description Replay of an earlier request with the same `client_order_id` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResult"];
                };
            };
            /** @description Order accepted or rejected by the engine */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order id (ULID) */
                id: components["parameters"]["OrderID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order and its trades */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order id (ULID) */
                id: components["parameters"]["OrderID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order after the cancel (or its terminal state) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listFills: {
        parameters: {
            query?: {
                market?: string;
                order_id?: string;
                /** @description Page size (default 100, max 500) */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fills, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
}
