// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type RegistryAsset struct {
	ID                    string
	TenantID              string
	Symbol                string
	Name                  string
	ChainID               int64
	ContractAddress       *string
	IsNative              bool
	Scale                 int16
	DisplayScale          int16
	RequiredConfirmations int32
	MinDeposit            pgtype.Numeric
	MinWithdrawal         pgtype.Numeric
	WithdrawalFee         pgtype.Numeric
	SweepThreshold        pgtype.Numeric
	DepositEnabled        bool
	WithdrawEnabled       bool
	Status                string
	Version               int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
	WithdrawalFeeBps      int32
	DepositFeeBps         int32
}

type RegistryFeeSchedule struct {
	ID            string
	TenantID      string
	Name          string
	MakerBps      int32
	TakerBps      int32
	EffectiveFrom time.Time
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
