// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type RegistryAsset struct {
	ID                    string
	TenantID              string
	Symbol                string
	Name                  string
	ChainID               int64
	ContractAddress       *string
	IsNative              bool
	Scale                 int16
	DisplayScale          int16
	RequiredConfirmations int32
	MinDeposit            pgtype.Numeric
	MinWithdrawal         pgtype.Numeric
	WithdrawalFee         pgtype.Numeric
	SweepThreshold        pgtype.Numeric
	DepositEnabled        bool
	WithdrawEnabled       bool
	Status                string
	Version               int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type RegistryFeeSchedule struct {
	ID            string
	TenantID      string
	Name          string
	MakerBps      int32
	TakerBps      int32
	EffectiveFrom time.Time
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type RegistryMarket struct {
	ID              string
	TenantID        string
	Symbol          string
	BaseAssetID     string
	QuoteAssetID    string
	PriceTick       pgtype.Numeric
	QtyStep         pgtype.Numeric
	MinNotional     pgtype.Numeric
	MaxQty          pgtype.Numeric
	MaxSlippageBps  *int32
	FeeScheduleID   string
	SelfTradePolicy string
	Status          string
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type RegistryWithdrawalLimit struct {
	TenantID            string
	AssetID             string
	KycLevel            int16
	AutoApproveLimit    pgtype.Numeric
	DailyLimit          pgtype.Numeric
	RequireManualReview bool
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}
