// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssetBySymbol = `-- name: GetAssetBySymbol :one
SELECT id, tenant_id, symbol, name, chain_id, contract_address, is_native, scale, display_scale, required_confirmations, min_deposit, min_withdrawal, withdrawal_fee, sweep_threshold, deposit_enabled, withdraw_enabled, status, version, created_at, updated_at, withdrawal_fee_bps, deposit_fee_bps FROM registry.assets
WHERE tenant_id = $1 AND symbol = $2
`

type GetAssetBySymbolParams struct {
	TenantID string
	Symbol   string
}

func (q *Queries) GetAssetBySymbol(ctx context.Context, arg GetAssetBySymbolParams) (RegistryAsset, error) {
	row := q.db.QueryRow(ctx, getAssetBySymbol, arg.TenantID, arg.Symbol)
	var i RegistryAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Symbol,
		&i.Name,
		&i.ChainID,
		&i.ContractAddress,
		&i.IsNative,
		&i.Scale,
		&i.DisplayScale,
		&i.RequiredConfirmations,
		&i.MinDeposit,
		&i.MinWithdrawal,
		&i.WithdrawalFee,
		&i.SweepThreshold,
		&i.DepositEnabled,
		&i.WithdrawEnabled,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawalFeeBps,
		&i.DepositFeeBps,
	)
	return i, err
}

const getFeeScheduleByName = `-- name: GetFeeScheduleByName :one
SELECT id, tenant_id, name, maker_bps, taker_bps, effective_from, version, created_at, updated_at FROM registry.fee_schedules
WHERE tenant_id = $1 AND name = $2
`

type GetFeeScheduleByNameParams struct {
	TenantID string
	Name     string
}

func (q *Queries) GetFeeScheduleByName(ctx context.Context, arg GetFeeScheduleByNameParams) (RegistryFeeSchedule, error) {
	row := q.db.QueryRow(ctx, getFeeScheduleByName, arg.TenantID, arg.Name)
	var i RegistryFeeSchedule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.MakerBps,
		&i.TakerBps,
		&i.EffectiveFrom,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarketBySymbol = `-- name: GetMarketBySymbol :one
SELECT m.id, m.tenant_id, m.symbol, m.base_asset_id, m.quote_asset_id, m.price_tick, m.qty_step, m.min_notional, m.max_qty, m.max_slippage_bps, m.fee_schedule_id, m.self_trade_policy, m.status, m.version, m.created_at, m.updated_at,
       b.symbol AS base_symbol,
       b.scale  AS base_scale,
       q.symbol AS quote_symbol,
       q.scale  AS quote_scale,
       f.name   AS fee_schedule_name,
       f.maker_bps,
       f.taker_bps
FROM registry.markets m
JOIN registry.assets b ON b.id = m.base_asset_id
JOIN registry.assets q ON q.id = m.quote_asset_id
JOIN registry.fee_schedules f ON f.id = m.fee_schedule_id
WHERE m.tenant_id = $1 AND m.symbol = $2
`

type GetMarketBySymbolParams struct {
	TenantID string
	Symbol   string
}

type GetMarketBySymbolRow struct {
	ID              string
	TenantID        string
	Symbol          string
	BaseAssetID     string
	QuoteAssetID    string
	PriceTick       pgtype.Numeric
	QtyStep         pgtype.Numeric
	MinNotional     pgtype.Numeric
	MaxQty          pgtype.Numeric
	MaxSlippageBps  *int32
	FeeScheduleID   string
	SelfTradePolicy string
	Status          string
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	BaseSymbol      string
	BaseScale       int16
	QuoteSymbol     string
	QuoteScale      int16
	FeeScheduleName string
	MakerBps        int32
	TakerBps        int32
}

func (q *Queries) GetMarketBySymbol(ctx context.Context, arg GetMarketBySymbolParams) (GetMarketBySymbolRow, error) {
	row := q.db.QueryRow(ctx, getMarketBySymbol, arg.TenantID, arg.Symbol)
	var i GetMarketBySymbolRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Symbol,
		&i.BaseAssetID,
		&i.QuoteAssetID,
		&i.PriceTick,
		&i.QtyStep,
		&i.MinNotional,
		&i.MaxQty,
		&i.MaxSlippageBps,
		&i.FeeScheduleID,
		&i.SelfTradePolicy,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseSymbol,
		&i.BaseScale,
		&i.QuoteSymbol,
		&i.QuoteScale,
		&i.FeeScheduleName,
		&i.MakerBps,
		&i.TakerBps,
	)
	return i, err
}

const getWithdrawalLimit = `-- name: GetWithdrawalLimit :one
SELECT w.tenant_id, w.asset_id, w.kyc_level, w.auto_approve_limit, w.daily_limit, w.require_manual_review, w.version, w.created_at, w.updated_at, a.symbol AS asset_symbol
FROM registry.withdrawal_limits w
JOIN registry.assets a ON a.id = w.asset_id
WHERE w.tenant_id = $1 AND a.symbol = $2 AND w.kyc_level = $3
`

type GetWithdrawalLimitParams struct {
	TenantID string
	Symbol   string
	KycLevel int16
}

type GetWithdrawalLimitRow struct {
	TenantID            string
	AssetID             string
	KycLevel            int16
	AutoApproveLimit    pgtype.Numeric
	DailyLimit          pgtype.Numeric
	RequireManualReview bool
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AssetSymbol         string
}

func (q *Queries) GetWithdrawalLimit(ctx context.Context, arg GetWithdrawalLimitParams) (GetWithdrawalLimitRow, error) {
	row := q.db.QueryRow(ctx, getWithdrawalLimit, arg.TenantID, arg.Symbol, arg.KycLevel)
	var i GetWithdrawalLimitRow
	err := row.Scan(
		&i.TenantID,
		&i.AssetID,
		&i.KycLevel,
		&i.AutoApproveLimit,
		&i.DailyLimit,
		&i.RequireManualReview,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssetSymbol,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many

SELECT id, tenant_id, symbol, name, chain_id, contract_address, is_native, scale, display_scale, required_confirmations, min_deposit, min_withdrawal, withdrawal_fee, sweep_threshold, deposit_enabled, withdraw_enabled, status, version, created_at, updated_at, withdrawal_fee_bps, deposit_fee_bps FROM registry.assets
WHERE tenant_id = $1
ORDER BY symbol
`

// Registry queries. Always schema-qualified; never rely on search_path.
func (q *Queries) ListAssets(ctx context.Context, tenantID string) ([]RegistryAsset, error) {
	rows, err := q.db.Query(ctx, listAssets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistryAsset{}
	for rows.Next() {
		var i RegistryAsset
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Symbol,
			&i.Name,
			&i.ChainID,
			&i.ContractAddress,
			&i.IsNative,
			&i.Scale,
			&i.DisplayScale,
			&i.RequiredConfirmations,
			&i.MinDeposit,
			&i.MinWithdrawal,
			&i.WithdrawalFee,
			&i.SweepThreshold,
			&i.DepositEnabled,
			&i.WithdrawEnabled,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WithdrawalFeeBps,
			&i.DepositFeeBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeSchedules = `-- name: ListFeeSchedules :many
SELECT id, tenant_id, name, maker_bps, taker_bps, effective_from, version, created_at, updated_at FROM registry.fee_schedules WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListFeeSchedules(ctx context.Context, tenantID string) ([]RegistryFeeSchedule, error) {
	rows, err := q.db.Query(ctx, listFeeSchedules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistryFeeSchedule{}
	for rows.Next() {
		var i RegistryFeeSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.MakerBps,
			&i.TakerBps,
			&i.EffectiveFrom,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkets = `-- name: ListMarkets :many
SELECT m.id, m.tenant_id, m.symbol, m.base_asset_id, m.quote_asset_id, m.price_tick, m.qty_step, m.min_notional, m.max_qty, m.max_slippage_bps, m.fee_schedule_id, m.self_trade_policy, m.status, m.version, m.created_at, m.updated_at,
       b.symbol AS base_symbol,
       b.scale  AS base_scale,
       q.symbol AS quote_symbol,
       q.scale  AS quote_scale,
       f.name   AS fee_schedule_name,
       f.maker_bps,
       f.taker_bps
FROM registry.markets m
JOIN registry.assets b ON b.id = m.base_asset_id
JOIN registry.assets q ON q.id = m.quote_asset_id
JOIN registry.fee_schedules f ON f.id = m.fee_schedule_id
WHERE m.tenant_id = $1
ORDER BY m.symbol
`

type ListMarketsRow struct {
	ID              string
	TenantID        string
	Symbol          string
	BaseAssetID     string
	QuoteAssetID    string
	PriceTick       pgtype.Numeric
	QtyStep         pgtype.Numeric
	MinNotional     pgtype.Numeric
	MaxQty          pgtype.Numeric
	MaxSlippageBps  *int32
	FeeScheduleID   string
	SelfTradePolicy string
	Status          string
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	BaseSymbol      string
	BaseScale       int16
	QuoteSymbol     string
	QuoteScale      int16
	FeeScheduleName string
	MakerBps        int32
	TakerBps        int32
}

func (q *Queries) ListMarkets(ctx context.Context, tenantID string) ([]ListMarketsRow, error) {
	rows, err := q.db.Query(ctx, listMarkets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketsRow{}
	for rows.Next() {
		var i ListMarketsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Symbol,
			&i.BaseAssetID,
			&i.QuoteAssetID,
			&i.PriceTick,
			&i.QtyStep,
			&i.MinNotional,
			&i.MaxQty,
			&i.MaxSlippageBps,
			&i.FeeScheduleID,
			&i.SelfTradePolicy,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseSymbol,
			&i.BaseScale,
			&i.QuoteSymbol,
			&i.QuoteScale,
			&i.FeeScheduleName,
			&i.MakerBps,
			&i.TakerBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalLimits = `-- name: ListWithdrawalLimits :many
SELECT w.tenant_id, w.asset_id, w.kyc_level, w.auto_approve_limit, w.daily_limit, w.require_manual_review, w.version, w.created_at, w.updated_at, a.symbol AS asset_symbol
FROM registry.withdrawal_limits w
JOIN registry.assets a ON a.id = w.asset_id
WHERE w.tenant_id = $1
ORDER BY a.symbol, w.kyc_level
`

type ListWithdrawalLimitsRow struct {
	TenantID            string
	AssetID             string
	KycLevel            int16
	AutoApproveLimit    pgtype.Numeric
	DailyLimit          pgtype.Numeric
	RequireManualReview bool
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AssetSymbol         string
}

// Joined to the asset so callers work in symbols; the table is keyed by id.
func (q *Queries) ListWithdrawalLimits(ctx context.Context, tenantID string) ([]ListWithdrawalLimitsRow, error) {
	rows, err := q.db.Query(ctx, listWithdrawalLimits, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWithdrawalLimitsRow{}
	for rows.Next() {
		var i ListWithdrawalLimitsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.AssetID,
			&i.KycLevel,
			&i.AutoApproveLimit,
			&i.DailyLimit,
			&i.RequireManualReview,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssetSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMarketStatus = `-- name: SetMarketStatus :exec
UPDATE registry.markets
   SET status     = $3,
       version    = version + 1,
       updated_at = now()
 WHERE tenant_id = $1 AND symbol = $2 AND status IS DISTINCT FROM $3
`

type SetMarketStatusParams struct {
	TenantID string
	Symbol   string
	Status   string
}

// Status changes are the one registry write the admin API makes on a live
// market; version and updated_at move only when the status really changes so
// an idempotent replay does not emit a new event.
func (q *Queries) SetMarketStatus(ctx context.Context, arg SetMarketStatusParams) error {
	_, err := q.db.Exec(ctx, setMarketStatus, arg.TenantID, arg.Symbol, arg.Status)
	return err
}

const upsertAsset = `-- name: UpsertAsset :exec
INSERT INTO registry.assets (
    tenant_id, symbol, name, chain_id, contract_address, is_native, scale, display_scale,
    required_confirmations, min_deposit, min_withdrawal, withdrawal_fee,
    withdrawal_fee_bps, deposit_fee_bps, sweep_threshold,
    deposit_enabled, withdraw_enabled, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ON CONFLICT (tenant_id, symbol) DO UPDATE
SET name                   = EXCLUDED.name,
    chain_id               = EXCLUDED.chain_id,
    contract_address       = EXCLUDED.contract_address,
    is_native              = EXCLUDED.is_native,
    scale                  = EXCLUDED.scale,
    display_scale          = EXCLUDED.display_scale,
    required_confirmations = EXCLUDED.required_confirmations,
    min_deposit            = EXCLUDED.min_deposit,
    min_withdrawal         = EXCLUDED.min_withdrawal,
    withdrawal_fee         = EXCLUDED.withdrawal_fee,
    withdrawal_fee_bps     = EXCLUDED.withdrawal_fee_bps,
    deposit_fee_bps        = EXCLUDED.deposit_fee_bps,
    sweep_threshold        = EXCLUDED.sweep_threshold,
    deposit_enabled        = EXCLUDED.deposit_enabled,
    withdraw_enabled       = EXCLUDED.withdraw_enabled,
    status                 = EXCLUDED.status,
    version                = registry.assets.version + 1,
    updated_at             = now()
WHERE (registry.assets.name, registry.assets.chain_id, registry.assets.contract_address, registry.assets.is_native,
       registry.assets.scale, registry.assets.display_scale, registry.assets.required_confirmations,
       registry.assets.min_deposit, registry.assets.min_withdrawal, registry.assets.withdrawal_fee,
       registry.assets.withdrawal_fee_bps, registry.assets.deposit_fee_bps,
       registry.assets.sweep_threshold, registry.assets.deposit_enabled, registry.assets.withdraw_enabled,
       registry.assets.status)
      IS DISTINCT FROM
      (EXCLUDED.name, EXCLUDED.chain_id, EXCLUDED.contract_address, EXCLUDED.is_native,
       EXCLUDED.scale, EXCLUDED.display_scale, EXCLUDED.required_confirmations,
       EXCLUDED.min_deposit, EXCLUDED.min_withdrawal, EXCLUDED.withdrawal_fee,
       EXCLUDED.withdrawal_fee_bps, EXCLUDED.deposit_fee_bps,
       EXCLUDED.sweep_threshold, EXCLUDED.deposit_enabled, EXCLUDED.withdraw_enabled,
       EXCLUDED.status)
`

type UpsertAssetParams struct {
	TenantID              string
	Symbol                string
	Name                  string
	ChainID               int64
	ContractAddress       *string
	IsNative              bool
	Scale                 int16
	DisplayScale          int16
	RequiredConfirmations int32
	MinDeposit            pgtype.Numeric
	MinWithdrawal         pgtype.Numeric
	WithdrawalFee         pgtype.Numeric
	WithdrawalFeeBps      int32
	DepositFeeBps         int32
	SweepThreshold        pgtype.Numeric
	DepositEnabled        bool
	WithdrawEnabled       bool
	Status                string
}

func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) error {
	_, err := q.db.Exec(ctx, upsertAsset,
		arg.TenantID,
		arg.Symbol,
		arg.Name,
		arg.ChainID,
		arg.ContractAddress,
		arg.IsNative,
		arg.Scale,
		arg.DisplayScale,
		arg.RequiredConfirmations,
		arg.MinDeposit,
		arg.MinWithdrawal,
		arg.WithdrawalFee,
		arg.WithdrawalFeeBps,
		arg.DepositFeeBps,
		arg.SweepThreshold,
		arg.DepositEnabled,
		arg.WithdrawEnabled,
		arg.Status,
	)
	return err
}

const upsertFeeSchedule = `-- name: UpsertFeeSchedule :exec

INSERT INTO registry.fee_schedules (tenant_id, name, maker_bps, taker_bps)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, name) DO UPDATE
SET maker_bps  = EXCLUDED.maker_bps,
    taker_bps  = EXCLUDED.taker_bps,
    version    = registry.fee_schedules.version + 1,
    updated_at = now()
WHERE (registry.fee_schedules.maker_bps, registry.fee_schedules.taker_bps)
      IS DISTINCT FROM (EXCLUDED.maker_bps, EXCLUDED.taker_bps)
`

type UpsertFeeScheduleParams struct {
	TenantID string
	Name     string
	MakerBps int32
	TakerBps int32
}

// Upserts bump version/updated_at only when something actually changed, so
// re-running the seed is a true no-op.
func (q *Queries) UpsertFeeSchedule(ctx context.Context, arg UpsertFeeScheduleParams) error {
	_, err := q.db.Exec(ctx, upsertFeeSchedule,
		arg.TenantID,
		arg.Name,
		arg.MakerBps,
		arg.TakerBps,
	)
	return err
}

const upsertMarket = `-- name: UpsertMarket :exec
INSERT INTO registry.markets (
    tenant_id, symbol, base_asset_id, quote_asset_id, price_tick, qty_step, min_notional,
    max_qty, max_slippage_bps, fee_schedule_id, self_trade_policy, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (tenant_id, symbol) DO UPDATE
SET base_asset_id     = EXCLUDED.base_asset_id,
    quote_asset_id    = EXCLUDED.quote_asset_id,
    price_tick        = EXCLUDED.price_tick,
    qty_step          = EXCLUDED.qty_step,
    min_notional      = EXCLUDED.min_notional,
    max_qty           = EXCLUDED.max_qty,
    max_slippage_bps  = EXCLUDED.max_slippage_bps,
    fee_schedule_id   = EXCLUDED.fee_schedule_id,
    self_trade_policy = EXCLUDED.self_trade_policy,
    status            = EXCLUDED.status,
    version           = registry.markets.version + 1,
    updated_at        = now()
WHERE (registry.markets.base_asset_id, registry.markets.quote_asset_id, registry.markets.price_tick,
       registry.markets.qty_step, registry.markets.min_notional, registry.markets.max_qty,
       registry.markets.max_slippage_bps, registry.markets.fee_schedule_id,
       registry.markets.self_trade_policy, registry.markets.status)
      IS DISTINCT FROM
      (EXCLUDED.base_asset_id, EXCLUDED.quote_asset_id, EXCLUDED.price_tick,
       EXCLUDED.qty_step, EXCLUDED.min_notional, EXCLUDED.max_qty,
       EXCLUDED.max_slippage_bps, EXCLUDED.fee_schedule_id,
       EXCLUDED.self_trade_policy, EXCLUDED.status)
`

type UpsertMarketParams struct {
	TenantID        string
	Symbol          string
	BaseAssetID     string
	QuoteAssetID    string
	PriceTick       pgtype.Numeric
	QtyStep         pgtype.Numeric
	MinNotional     pgtype.Numeric
	MaxQty          pgtype.Numeric
	MaxSlippageBps  *int32
	FeeScheduleID   string
	SelfTradePolicy string
	Status          string
}

func (q *Queries) UpsertMarket(ctx context.Context, arg UpsertMarketParams) error {
	_, err := q.db.Exec(ctx, upsertMarket,
		arg.TenantID,
		arg.Symbol,
		arg.BaseAssetID,
		arg.QuoteAssetID,
		arg.PriceTick,
		arg.QtyStep,
		arg.MinNotional,
		arg.MaxQty,
		arg.MaxSlippageBps,
		arg.FeeScheduleID,
		arg.SelfTradePolicy,
		arg.Status,
	)
	return err
}

const upsertWithdrawalLimit = `-- name: UpsertWithdrawalLimit :exec
INSERT INTO registry.withdrawal_limits (
    tenant_id, asset_id, kyc_level, auto_approve_limit, daily_limit, require_manual_review
)
SELECT $1, a.id, $3, $4, $5, $6 FROM registry.assets a
WHERE a.tenant_id = $1 AND a.symbol = $2
ON CONFLICT (tenant_id, asset_id, kyc_level) DO UPDATE
SET auto_approve_limit    = EXCLUDED.auto_approve_limit,
    daily_limit           = EXCLUDED.daily_limit,
    require_manual_review = EXCLUDED.require_manual_review,
    version               = registry.withdrawal_limits.version + 1,
    updated_at            = now()
WHERE (registry.withdrawal_limits.auto_approve_limit, registry.withdrawal_limits.daily_limit,
       registry.withdrawal_limits.require_manual_review)
      IS DISTINCT FROM
      (EXCLUDED.auto_approve_limit, EXCLUDED.daily_limit, EXCLUDED.require_manual_review)
`

type UpsertWithdrawalLimitParams struct {
	TenantID            string
	Symbol              string
	KycLevel            int16
	AutoApproveLimit    pgtype.Numeric
	DailyLimit          pgtype.Numeric
	RequireManualReview bool
}

func (q *Queries) UpsertWithdrawalLimit(ctx context.Context, arg UpsertWithdrawalLimitParams) error {
	_, err := q.db.Exec(ctx, upsertWithdrawalLimit,
		arg.TenantID,
		arg.Symbol,
		arg.KycLevel,
		arg.AutoApproveLimit,
		arg.DailyLimit,
		arg.RequireManualReview,
	)
	return err
}
