#!/usr/bin/env bash
# Regenerates THIRD-PARTY-NOTICES.md from the module cache (docs/adr/0014).
#
# Why not go-licenses: on this toolchain it aborts walking the standard
# library -- "Package io/ioutil does not have module info" -- and exits 1
# before writing anything (google/go-licenses#128). The information it would
# have gathered is already on disk: `go list -deps` says which packages are
# actually linked into the two binaries, `go list -m` maps those to modules
# and their unpacked directory, and every module ships its own licence file.
#
# The scope is deliberately what we DISTRIBUTE, not `go list -m all`. That
# would be 419 modules, most of which are in the graph without being built.
set -euo pipefail
cd "$(dirname "$0")/.."

out="${1:-THIRD-PARTY-NOTICES.md}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# modules behind every package linked into cmd/exchange and cmd/exchangectl
mods="$(go list -deps ./cmd/... |
  xargs go list -f '{{if .Module}}{{.Module.Path}}{{end}}' 2>/dev/null |
  grep -v '^$' | sort -u | grep -v '^github.com/arc119226/crypto-exchange$')"

{
  echo "# Third-party notices"
  echo
  echo "Generated by \`make notices\`. Do not edit by hand."
  echo
  echo "These are the modules linked into \`exchange\` and \`exchangectl\`, and"
  echo "therefore into the container images published from this repository. The"
  echo "licence text reproduced under each one is the authoritative statement;"
  echo "the short name next to the version is a convenience derived from that"
  echo "text and is not a legal classification."
  echo
  echo "The project's own code is Apache-2.0 (see LICENSE). go-ethereum is"
  echo "LGPL-3.0 and is called out separately in NOTICE, because it is the only"
  echo "dependency here whose licence is not permissive."
  echo
} >"$tmp"

count=0
while read -r mod; do
  [ -n "$mod" ] || continue
  read -r ver dir < <(go list -m -f '{{.Version}} {{.Dir}}' "$mod" 2>/dev/null || echo " ")
  [ -n "${dir:-}" ] && [ -d "$dir" ] || { echo "warning: no module dir for $mod" >&2; continue; }
  # Every licence file the module ships, not just the first. go-ethereum is
  # why: it carries COPYING (GPL-3.0) for its cmd/ tools and COPYING.LESSER
  # (LGPL-3.0) for the libraries, and taking one at random would misreport it
  # in whichever direction sort happened to land. Dual-licensed modules are
  # rare but getting one wrong is the kind of error nobody catches by reading.
  mapfile -t lics < <(find "$dir" -maxdepth 2 \
    -iregex '.*/\(licen[cs]e\|copying\)\(\.lesser\|\.md\|\.txt\)?' -type f 2>/dev/null | sort)
  [ "${#lics[@]}" -gt 0 ] || { echo "warning: no licence file in $dir" >&2; continue; }

  names=()
  for lic in "${lics[@]}"; do
    n="see text"
    if   grep -qi 'GNU LESSER GENERAL PUBLIC'      "$lic"; then n="LGPL-3.0"
    elif grep -qi 'GNU GENERAL PUBLIC'             "$lic"; then n="GPL-3.0"
    elif grep -qi 'Apache License'                 "$lic"; then n="Apache-2.0"
    elif grep -qi 'Mozilla Public License'         "$lic"; then n="MPL-2.0"
    elif grep -qi 'Permission is hereby granted, free of charge' "$lic"; then n="MIT"
    elif grep -qi 'Redistribution and use in source and binary' "$lic"; then n="BSD"
    elif grep -qi 'Permission to use, copy, modify' "$lic"; then n="ISC/0BSD"
    fi
    names+=("$n")
  done

  {
    echo "## $mod"
    echo
    # de-duplicate for the heading only; every text below is still reproduced.
    # maxdepth 2 finds vendored sub-licences, so the same family repeats.
    uniq_names="$(printf '%s\n' "${names[@]}" |
      awk '!seen[$0]++' |
      awk 'NR>1 {printf ", "} {printf "%s", $0} END {print ""}')"
    printf 'Version: `%s` — %s\n' "${ver:-(main module)}" "$uniq_names"
    if [ "${#lics[@]}" -gt 1 ]; then
      echo
      echo "> This module ships more than one licence file. Which one applies"
      echo "> depends on the package: see the module's own documentation. For"
      echo "> go-ethereum this project links only library packages, which are"
      echo "> LGPL-3.0; nothing under its \`cmd/\` (GPL-3.0) is imported."
    fi
    echo
    for lic in "${lics[@]}"; do
      echo "\`$(basename "$lic")\`:"
      echo
      echo '```'
      cat "$lic"
      echo '```'
      echo
    done
  } >>"$tmp"
  count=$((count + 1))
done <<<"$mods"

mv "$tmp" "$out"
trap - EXIT
echo "gen-notices: wrote $out covering $count modules" >&2
