// Package adminclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package adminclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/arc119226/crypto-exchange/internal/money"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AccountKind.
const (
	AccountKindHouse AccountKind = "house"
	AccountKindSpot  AccountKind = "spot"
)

// Valid indicates whether the value is a known member of the AccountKind enum.
func (e AccountKind) Valid() bool {
	switch e {
	case AccountKindHouse:
		return true
	case AccountKindSpot:
		return true
	default:
		return false
	}
}

// Defines values for AccountStatus.
const (
	AccountStatusActive AccountStatus = "active"
	AccountStatusFrozen AccountStatus = "frozen"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case AccountStatusActive:
		return true
	case AccountStatusFrozen:
		return true
	default:
		return false
	}
}

// Defines values for AdjustmentRequestDirection.
const (
	AdjustmentRequestDirectionCredit AdjustmentRequestDirection = "credit"
	AdjustmentRequestDirectionDebit  AdjustmentRequestDirection = "debit"
)

// Valid indicates whether the value is a known member of the AdjustmentRequestDirection enum.
func (e AdjustmentRequestDirection) Valid() bool {
	switch e {
	case AdjustmentRequestDirectionCredit:
		return true
	case AdjustmentRequestDirectionDebit:
		return true
	default:
		return false
	}
}

// Defines values for AuditEventActorType.
const (
	AuditEventActorTypeAPIKey AuditEventActorType = "api_key"
	AuditEventActorTypeAdmin  AuditEventActorType = "admin"
	AuditEventActorTypeSystem AuditEventActorType = "system"
	AuditEventActorTypeUser   AuditEventActorType = "user"
)

// Valid indicates whether the value is a known member of the AuditEventActorType enum.
func (e AuditEventActorType) Valid() bool {
	switch e {
	case AuditEventActorTypeAPIKey:
		return true
	case AuditEventActorTypeAdmin:
		return true
	case AuditEventActorTypeSystem:
		return true
	case AuditEventActorTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for HouseBalanceType.
const (
	HouseBalanceTypeAsset     HouseBalanceType = "asset"
	HouseBalanceTypeExpense   HouseBalanceType = "expense"
	HouseBalanceTypeExternal  HouseBalanceType = "external"
	HouseBalanceTypeLiability HouseBalanceType = "liability"
	HouseBalanceTypeRevenue   HouseBalanceType = "revenue"
)

// Valid indicates whether the value is a known member of the HouseBalanceType enum.
func (e HouseBalanceType) Valid() bool {
	switch e {
	case HouseBalanceTypeAsset:
		return true
	case HouseBalanceTypeExpense:
		return true
	case HouseBalanceTypeExternal:
		return true
	case HouseBalanceTypeLiability:
		return true
	case HouseBalanceTypeRevenue:
		return true
	default:
		return false
	}
}

// Defines values for HouseCode.
const (
	HouseCodeCustodyDepositAddresses HouseCode = "custody_deposit_addresses"
	HouseCodeCustodyHot              HouseCode = "custody_hot"
	HouseCodeExternal                HouseCode = "external"
	HouseCodeFeeRevenue              HouseCode = "fee_revenue"
	HouseCodeGasExpense              HouseCode = "gas_expense"
	HouseCodePendingWithdrawal       HouseCode = "pending_withdrawal"
)

// Valid indicates whether the value is a known member of the HouseCode enum.
func (e HouseCode) Valid() bool {
	switch e {
	case HouseCodeCustodyDepositAddresses:
		return true
	case HouseCodeCustodyHot:
		return true
	case HouseCodeExternal:
		return true
	case HouseCodeFeeRevenue:
		return true
	case HouseCodeGasExpense:
		return true
	case HouseCodePendingWithdrawal:
		return true
	default:
		return false
	}
}

// Defines values for PostingBucket.
const (
	PostingBucketAvailable PostingBucket = "available"
	PostingBucketHold      PostingBucket = "hold"
	PostingBucketHouse     PostingBucket = "house"
)

// Valid indicates whether the value is a known member of the PostingBucket enum.
func (e PostingBucket) Valid() bool {
	switch e {
	case PostingBucketAvailable:
		return true
	case PostingBucketHold:
		return true
	case PostingBucketHouse:
		return true
	default:
		return false
	}
}

// Defines values for PostingDirection.
const (
	PostingDirectionCredit PostingDirection = "credit"
	PostingDirectionDebit  PostingDirection = "debit"
)

// Valid indicates whether the value is a known member of the PostingDirection enum.
func (e PostingDirection) Valid() bool {
	switch e {
	case PostingDirectionCredit:
		return true
	case PostingDirectionDebit:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	CreatedAt time.Time `json:"created_at"`

	// HouseCode Present for house accounts only.
	HouseCode   *HouseCode    `json:"house_code,omitempty"`
	ID          string        `json:"id"`
	Kind        AccountKind   `json:"kind"`
	OwnerUserID *string       `json:"owner_user_id,omitempty"`
	Status      AccountStatus `json:"status"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

// AccountKind defines model for AccountKind.
type AccountKind string

// AccountList defines model for AccountList.
type AccountList struct {
	Accounts []Account `json:"accounts"`
}

// AccountStatus defines model for AccountStatus.
type AccountStatus string

// AccountStatusRequest defines model for AccountStatusRequest.
type AccountStatusRequest struct {
	Reason string        `json:"reason"`
	Status AccountStatus `json:"status"`
}

// AdjustmentRequest defines model for AdjustmentRequest.
type AdjustmentRequest struct {
	AccountID string `json:"account_id"`

	// Amount Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
	//
	// Example: 1990.00
	Amount Amount `json:"amount"`

	// Asset Example: USDC
	Asset string `json:"asset"`

	// Direction credit adds to the user's available balance, debit removes.
	Direction AdjustmentRequestDirection `json:"direction"`

	// IdempotencyKey Defaults to a fresh key; pass one to make retries safe.
	IdempotencyKey string `json:"idempotency_key,omitempty"`

	// Reason Example: dev faucet
	Reason string `json:"reason"`
}

// AdjustmentRequestDirection credit adds to the user's available balance, debit removes.
type AdjustmentRequestDirection string

// Amount Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
//
// Example: 1990.00
type Amount = money.Amount

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action        string              `json:"action"`
	ActorID       string              `json:"actor_id,omitempty"`
	ActorType     AuditEventActorType `json:"actor_type"`
	After         interface{}         `json:"after,omitempty"`
	Before        interface{}         `json:"before,omitempty"`
	CorrelationID string              `json:"correlation_id,omitempty"`
	CreatedAt     time.Time           `json:"created_at"`
	ID            int64               `json:"id"`
	IP            string              `json:"ip,omitempty"`
	TargetID      string              `json:"target_id,omitempty"`
	TargetType    string              `json:"target_type,omitempty"`
}

// AuditEventActorType defines model for AuditEvent.ActorType.
type AuditEventActorType string

// AuditEventList defines model for AuditEventList.
type AuditEventList struct {
	Events []AuditEvent `json:"events"`
}

// Balance defines model for Balance.
type Balance struct {
	Asset string `json:"asset"`

	// Available Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
	//
	// Example: 1990.00
	Available Amount `json:"available"`

	// Hold Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
	//
	// Example: 1990.00
	Hold Amount `json:"hold"`

	// Total Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
	//
	// Example: 1990.00
	Total Amount `json:"total"`
}

// BalanceList defines model for BalanceList.
type BalanceList struct {
	AccountID string    `json:"account_id"`
	Balances  []Balance `json:"balances"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	// OwnerUserID Optional until Phase 3 introduces users.
	OwnerUserID *string `json:"owner_user_id,omitempty"`
}

// HouseBalance defines model for HouseBalance.
type HouseBalance struct {
	Asset string `json:"asset"`

	// Balance Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
	//
	// Example: 1990.00
	Balance Amount           `json:"balance"`
	Code    HouseCode        `json:"code"`
	Type    HouseBalanceType `json:"type"`
}

// HouseBalanceType defines model for HouseBalance.Type.
type HouseBalanceType string

// HouseCode defines model for HouseCode.
type HouseCode string

// JournalEntry defines model for JournalEntry.
type JournalEntry struct {
	CorrelationID  string    `json:"correlation_id,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	ID             int64     `json:"id"`
	IdempotencyKey string    `json:"idempotency_key"`
	Kind           string    `json:"kind"`
	Postings       []Posting `json:"postings"`
	Reason         string    `json:"reason,omitempty"`
	RefID          string    `json:"ref_id,omitempty"`
	RefType        string    `json:"ref_type,omitempty"`
}

// JournalEntryList defines model for JournalEntryList.
type JournalEntryList struct {
	Entries []JournalEntry `json:"entries"`
}

// Posting defines model for Posting.
type Posting struct {
	AccountID string `json:"account_id"`

	// Amount Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
	//
	// Example: 1990.00
	Amount    Amount           `json:"amount"`
	Asset     string           `json:"asset"`
	Bucket    PostingBucket    `json:"bucket"`
	Direction PostingDirection `json:"direction"`
}

// PostingBucket defines model for Posting.Bucket.
type PostingBucket string

// PostingDirection defines model for Posting.Direction.
type PostingDirection string

// Problem RFC 7807 problem details.
type Problem struct {
	CorrelationID string `json:"correlation_id,omitempty"`
	Detail        string `json:"detail,omitempty"`
	Instance      string `json:"instance,omitempty"`
	Status        int    `json:"status"`
	Title         string `json:"title"`
	Type          string `json:"type"`
}

// TrialBalance defines model for TrialBalance.
type TrialBalance struct {
	// Balanced true when every diff is zero.
	Balanced bool               `json:"balanced"`
	House    []HouseBalance     `json:"house"`
	Lines    []TrialBalanceLine `json:"lines"`
}

// TrialBalanceLine defines model for TrialBalanceLine.
type TrialBalanceLine struct {
	Asset string `json:"asset"`

	// Credits Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
	//
	// Example: 1990.00
	Credits Amount `json:"credits"`

	// Debits Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
	//
	// Example: 1990.00
	Debits Amount `json:"debits"`

	// Diff Decimal serialized as a string (NUMERIC(36,18)); never a JSON number.
	//
	// Example: 1990.00
	Diff Amount `json:"diff"`
}

// AccountID defines model for AccountID.
type AccountID = string

// Limit defines model for Limit.
type Limit = int32

// Offset defines model for Offset.
type Offset = int32

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// InternalError RFC 7807 problem details.
type InternalError = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// Unauthorized RFC 7807 problem details.
type Unauthorized = Problem

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	Kind   *AccountKind `form:"kind,omitempty" json:"kind,omitempty"`
	Limit  *Limit       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset      `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	Action     *string `form:"action,omitempty" json:"action,omitempty"`
	TargetType *string `form:"target_type,omitempty" json:"target_type,omitempty"`
	TargetID   *string `form:"target_id,omitempty" json:"target_id,omitempty"`
	Limit      *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListEntriesParams defines parameters for ListEntries.
type ListEntriesParams struct {
	AccountID *string `form:"account_id,omitempty" json:"account_id,omitempty"`
	RefType   *string `form:"ref_type,omitempty" json:"ref_type,omitempty"`
	RefID     *string `form:"ref_id,omitempty" json:"ref_id,omitempty"`
	Limit     *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// SetAccountStatusJSONRequestBody defines body for SetAccountStatus for application/json ContentType.
type SetAccountStatusJSONRequestBody = AccountStatusRequest

// CreateAdjustmentJSONRequestBody defines body for CreateAdjustment for application/json ContentType.
type CreateAdjustmentJSONRequestBody = AdjustmentRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListAccounts List ledger accounts
	//
	// Corresponds with GET /admin/v1/accounts (the `ListAccounts` operationId).
	ListAccounts(ctx context.Context, params *ListAccountsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAccountWithBody Open a spot account
	//
	// Phase 2 dev/admin path; from Phase 3 registration opens the account.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /admin/v1/accounts (the `CreateAccount` operationId).
	CreateAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAccount Open a spot account
	//
	// Phase 2 dev/admin path; from Phase 3 registration opens the account.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /admin/v1/accounts (the `CreateAccount` operationId).
	CreateAccount(ctx context.Context, body CreateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAccount Get one account
	//
	// Corresponds with GET /admin/v1/accounts/{id} (the `GetAccount` operationId).
	GetAccount(ctx context.Context, id AccountID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAccountBalances Cached balances of a spot account
	//
	// Corresponds with GET /admin/v1/accounts/{id}/balances (the `GetAccountBalances` operationId).
	GetAccountBalances(ctx context.Context, id AccountID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetAccountStatusWithBody Freeze or reactivate an account
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /admin/v1/accounts/{id}/status (the `SetAccountStatus` operationId).
	SetAccountStatusWithBody(ctx context.Context, id AccountID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetAccountStatus Freeze or reactivate an account
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /admin/v1/accounts/{id}/status (the `SetAccountStatus` operationId).
	SetAccountStatus(ctx context.Context, id AccountID, body SetAccountStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListAuditEvents Audit trail, newest first
	//
	// Corresponds with GET /admin/v1/audit-events (the `ListAuditEvents` operationId).
	ListAuditEvents(ctx context.Context, params *ListAuditEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAdjustmentWithBody Post a manual adjustment against the external account
	//
	// `credit` adds to the account's available balance (the development
	// faucet, or a correction in the user's favour); `debit` removes from it.
	// A reason is mandatory and the call is recorded in the audit trail.
	// Repeating the same `idempotency_key` returns the original entry with
	// HTTP 200 instead of 201.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /admin/v1/ledger/adjustments (the `CreateAdjustment` operationId).
	CreateAdjustmentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAdjustment Post a manual adjustment against the external account
	//
	// `credit` adds to the account's available balance (the development
	// faucet, or a correction in the user's favour); `debit` removes from it.
	// A reason is mandatory and the call is recorded in the audit trail.
	// Repeating the same `idempotency_key` returns the original entry with
	// HTTP 200 instead of 201.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /admin/v1/ledger/adjustments (the `CreateAdjustment` operationId).
	CreateAdjustment(ctx context.Context, body CreateAdjustmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListEntries Journal entries with postings, newest first
	//
	// Corresponds with GET /admin/v1/ledger/entries (the `ListEntries` operationId).
	ListEntries(ctx context.Context, params *ListEntriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTrialBalance Trial balance per asset (must be zero) and house account balances
	//
	// Corresponds with GET /admin/v1/ledger/trial-balance (the `GetTrialBalance` operationId).
	GetTrialBalance(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListAccounts List ledger accounts
//
// Corresponds with GET /admin/v1/accounts (the `ListAccounts` operationId).
func (c *Client) ListAccounts(ctx context.Context, params *ListAccountsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAccountsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateAccountWithBody Open a spot account
//
// Phase 2 dev/admin path; from Phase 3 registration opens the account.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /admin/v1/accounts (the `CreateAccount` operationId).
func (c *Client) CreateAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAccountRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateAccount Open a spot account
//
// Phase 2 dev/admin path; from Phase 3 registration opens the account.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /admin/v1/accounts (the `CreateAccount` operationId).
func (c *Client) CreateAccount(ctx context.Context, body CreateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAccountRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetAccount Get one account
//
// Corresponds with GET /admin/v1/accounts/{id} (the `GetAccount` operationId).
func (c *Client) GetAccount(ctx context.Context, id AccountID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetAccountBalances Cached balances of a spot account
//
// Corresponds with GET /admin/v1/accounts/{id}/balances (the `GetAccountBalances` operationId).
func (c *Client) GetAccountBalances(ctx context.Context, id AccountID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountBalancesRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SetAccountStatusWithBody Freeze or reactivate an account
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /admin/v1/accounts/{id}/status (the `SetAccountStatus` operationId).
func (c *Client) SetAccountStatusWithBody(ctx context.Context, id AccountID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetAccountStatusRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SetAccountStatus Freeze or reactivate an account
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /admin/v1/accounts/{id}/status (the `SetAccountStatus` operationId).
func (c *Client) SetAccountStatus(ctx context.Context, id AccountID, body SetAccountStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetAccountStatusRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListAuditEvents Audit trail, newest first
//
// Corresponds with GET /admin/v1/audit-events (the `ListAuditEvents` operationId).
func (c *Client) ListAuditEvents(ctx context.Context, params *ListAuditEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAuditEventsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateAdjustmentWithBody Post a manual adjustment against the external account
//
// `credit` adds to the account's available balance (the development
// faucet, or a correction in the user's favour); `debit` removes from it.
// A reason is mandatory and the call is recorded in the audit trail.
// Repeating the same `idempotency_key` returns the original entry with
// HTTP 200 instead of 201.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /admin/v1/ledger/adjustments (the `CreateAdjustment` operationId).
func (c *Client) CreateAdjustmentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAdjustmentRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateAdjustment Post a manual adjustment against the external account
//
// `credit` adds to the account's available balance (the development
// faucet, or a correction in the user's favour); `debit` removes from it.
// A reason is mandatory and the call is recorded in the audit trail.
// Repeating the same `idempotency_key` returns the original entry with
// HTTP 200 instead of 201.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /admin/v1/ledger/adjustments (the `CreateAdjustment` operationId).
func (c *Client) CreateAdjustment(ctx context.Context, body CreateAdjustmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAdjustmentRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListEntries Journal entries with postings, newest first
//
// Corresponds with GET /admin/v1/ledger/entries (the `ListEntries` operationId).
func (c *Client) ListEntries(ctx context.Context, params *ListEntriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEntriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetTrialBalance Trial balance per asset (must be zero) and house account balances
//
// Corresponds with GET /admin/v1/ledger/trial-balance (the `GetTrialBalance` operationId).
func (c *Client) GetTrialBalance(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTrialBalanceRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAccountsRequest constructs an http.Request for the ListAccounts method
func NewListAccountsRequest(server string, params *ListAccountsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Kind != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "kind", *params.Kind, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateAccountRequest calls the generic CreateAccount builder with application/json body
func NewCreateAccountRequest(server string, body CreateAccountJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAccountRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAccountRequestWithBody constructs an http.Request for the CreateAccount method, with any body, and a specified content type
func NewCreateAccountRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAccountRequest constructs an http.Request for the GetAccount method
func NewGetAccountRequest(server string, id AccountID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAccountBalancesRequest constructs an http.Request for the GetAccountBalances method
func NewGetAccountBalancesRequest(server string, id AccountID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/accounts/%s/balances", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSetAccountStatusRequest calls the generic SetAccountStatus builder with application/json body
func NewSetAccountStatusRequest(server string, id AccountID, body SetAccountStatusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetAccountStatusRequestWithBody(server, id, "application/json", bodyReader)
}

// NewSetAccountStatusRequestWithBody constructs an http.Request for the SetAccountStatus method, with any body, and a specified content type
func NewSetAccountStatusRequestWithBody(server string, id AccountID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/accounts/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListAuditEventsRequest constructs an http.Request for the ListAuditEvents method
func NewListAuditEventsRequest(server string, params *ListAuditEventsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/audit-events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Action != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "action", *params.Action, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.TargetType != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "target_type", *params.TargetType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.TargetID != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "target_id", *params.TargetID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateAdjustmentRequest calls the generic CreateAdjustment builder with application/json body
func NewCreateAdjustmentRequest(server string, body CreateAdjustmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAdjustmentRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAdjustmentRequestWithBody constructs an http.Request for the CreateAdjustment method, with any body, and a specified content type
func NewCreateAdjustmentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/ledger/adjustments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListEntriesRequest constructs an http.Request for the ListEntries method
func NewListEntriesRequest(server string, params *ListEntriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/ledger/entries")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.AccountID != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "account_id", *params.AccountID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.RefType != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "ref_type", *params.RefType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.RefID != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "ref_id", *params.RefID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTrialBalanceRequest constructs an http.Request for the GetTrialBalance method
func NewGetTrialBalanceRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/v1/ledger/trial-balance")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListAccountsWithResponse List ledger accounts
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /admin/v1/accounts (the `ListAccounts` operationId).
	ListAccountsWithResponse(ctx context.Context, params *ListAccountsParams, reqEditors ...RequestEditorFn) (*ListAccountsResponse, error)

	// CreateAccountWithBodyWithResponse Open a spot account
	//
	// Phase 2 dev/admin path; from Phase 3 registration opens the account.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /admin/v1/accounts (the `CreateAccount` operationId).
	CreateAccountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAccountResponse, error)

	// CreateAccountWithResponse Open a spot account
	//
	// Phase 2 dev/admin path; from Phase 3 registration opens the account.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /admin/v1/accounts (the `CreateAccount` operationId).
	CreateAccountWithResponse(ctx context.Context, body CreateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAccountResponse, error)

	// GetAccountWithResponse Get one account
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /admin/v1/accounts/{id} (the `GetAccount` operationId).
	GetAccountWithResponse(ctx context.Context, id AccountID, reqEditors ...RequestEditorFn) (*GetAccountResponse, error)

	// GetAccountBalancesWithResponse Cached balances of a spot account
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /admin/v1/accounts/{id}/balances (the `GetAccountBalances` operationId).
	GetAccountBalancesWithResponse(ctx context.Context, id AccountID, reqEditors ...RequestEditorFn) (*GetAccountBalancesResponse, error)

	// SetAccountStatusWithBodyWithResponse Freeze or reactivate an account
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /admin/v1/accounts/{id}/status (the `SetAccountStatus` operationId).
	SetAccountStatusWithBodyWithResponse(ctx context.Context, id AccountID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetAccountStatusResponse, error)

	// SetAccountStatusWithResponse Freeze or reactivate an account
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /admin/v1/accounts/{id}/status (the `SetAccountStatus` operationId).
	SetAccountStatusWithResponse(ctx context.Context, id AccountID, body SetAccountStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*SetAccountStatusResponse, error)

	// ListAuditEventsWithResponse Audit trail, newest first
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /admin/v1/audit-events (the `ListAuditEvents` operationId).
	ListAuditEventsWithResponse(ctx context.Context, params *ListAuditEventsParams, reqEditors ...RequestEditorFn) (*ListAuditEventsResponse, error)

	// CreateAdjustmentWithBodyWithResponse Post a manual adjustment against the external account
	//
	// `credit` adds to the account's available balance (the development
	// faucet, or a correction in the user's favour); `debit` removes from it.
	// A reason is mandatory and the call is recorded in the audit trail.
	// Repeating the same `idempotency_key` returns the original entry with
	// HTTP 200 instead of 201.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /admin/v1/ledger/adjustments (the `CreateAdjustment` operationId).
	CreateAdjustmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAdjustmentResponse, error)

	// CreateAdjustmentWithResponse Post a manual adjustment against the external account
	//
	// `credit` adds to the account's available balance (the development
	// faucet, or a correction in the user's favour); `debit` removes from it.
	// A reason is mandatory and the call is recorded in the audit trail.
	// Repeating the same `idempotency_key` returns the original entry with
	// HTTP 200 instead of 201.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /admin/v1/ledger/adjustments (the `CreateAdjustment` operationId).
	CreateAdjustmentWithResponse(ctx context.Context, body CreateAdjustmentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAdjustmentResponse, error)

	// ListEntriesWithResponse Journal entries with postings, newest first
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /admin/v1/ledger/entries (the `ListEntries` operationId).
	ListEntriesWithResponse(ctx context.Context, params *ListEntriesParams, reqEditors ...RequestEditorFn) (*ListEntriesResponse, error)

	// GetTrialBalanceWithResponse Trial balance per asset (must be zero) and house account balances
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /admin/v1/ledger/trial-balance (the `GetTrialBalance` operationId).
	GetTrialBalanceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTrialBalanceResponse, error)
}

type ListAccountsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AccountList
	// ApplicationProblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationProblemJSON401 *Unauthorized
	// ApplicationProblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationProblemJSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListAccountsResponse) GetJSON200() *AccountList {
	return r.JSON200
}

// GetApplicationProblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ListAccountsResponse) GetApplicationProblemJSON401() *Unauthorized {
	return r.ApplicationProblemJSON401
}

// GetApplicationProblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r ListAccountsResponse) GetApplicationProblemJSON500() *InternalError {
	return r.ApplicationProblemJSON500
}

// GetBody returns the raw response body bytes
func (r ListAccountsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListAccountsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAccountsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListAccountsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Account
	// ApplicationProblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationProblemJSON400 *BadRequest
	// ApplicationProblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationProblemJSON401 *Unauthorized
	// ApplicationProblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationProblemJSON500 *InternalError
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateAccountResponse) GetJSON201() *Account {
	return r.JSON201
}

// GetApplicationProblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r CreateAccountResponse) GetApplicationProblemJSON400() *BadRequest {
	return r.ApplicationProblemJSON400
}

// GetApplicationProblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r CreateAccountResponse) GetApplicationProblemJSON401() *Unauthorized {
	return r.ApplicationProblemJSON401
}

// GetApplicationProblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r CreateAccountResponse) GetApplicationProblemJSON500() *InternalError {
	return r.ApplicationProblemJSON500
}

// GetBody returns the raw response body bytes
func (r CreateAccountResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateAccountResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Account
	// ApplicationProblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationProblemJSON401 *Unauthorized
	// ApplicationProblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationProblemJSON404 *NotFound
	// ApplicationProblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationProblemJSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetAccountResponse) GetJSON200() *Account {
	return r.JSON200
}

// GetApplicationProblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetAccountResponse) GetApplicationProblemJSON401() *Unauthorized {
	return r.ApplicationProblemJSON401
}

// GetApplicationProblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetAccountResponse) GetApplicationProblemJSON404() *NotFound {
	return r.ApplicationProblemJSON404
}

// GetApplicationProblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetAccountResponse) GetApplicationProblemJSON500() *InternalError {
	return r.ApplicationProblemJSON500
}

// GetBody returns the raw response body bytes
func (r GetAccountResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAccountResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAccountBalancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *BalanceList
	// ApplicationProblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationProblemJSON401 *Unauthorized
	// ApplicationProblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationProblemJSON404 *NotFound
	// ApplicationProblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationProblemJSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetAccountBalancesResponse) GetJSON200() *BalanceList {
	return r.JSON200
}

// GetApplicationProblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetAccountBalancesResponse) GetApplicationProblemJSON401() *Unauthorized {
	return r.ApplicationProblemJSON401
}

// GetApplicationProblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetAccountBalancesResponse) GetApplicationProblemJSON404() *NotFound {
	return r.ApplicationProblemJSON404
}

// GetApplicationProblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetAccountBalancesResponse) GetApplicationProblemJSON500() *InternalError {
	return r.ApplicationProblemJSON500
}

// GetBody returns the raw response body bytes
func (r GetAccountBalancesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetAccountBalancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountBalancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAccountBalancesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SetAccountStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Account
	// ApplicationProblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationProblemJSON400 *BadRequest
	// ApplicationProblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationProblemJSON401 *Unauthorized
	// ApplicationProblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationProblemJSON404 *NotFound
	// ApplicationProblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationProblemJSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SetAccountStatusResponse) GetJSON200() *Account {
	return r.JSON200
}

// GetApplicationProblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r SetAccountStatusResponse) GetApplicationProblemJSON400() *BadRequest {
	return r.ApplicationProblemJSON400
}

// GetApplicationProblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r SetAccountStatusResponse) GetApplicationProblemJSON401() *Unauthorized {
	return r.ApplicationProblemJSON401
}

// GetApplicationProblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r SetAccountStatusResponse) GetApplicationProblemJSON404() *NotFound {
	return r.ApplicationProblemJSON404
}

// GetApplicationProblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r SetAccountStatusResponse) GetApplicationProblemJSON500() *InternalError {
	return r.ApplicationProblemJSON500
}

// GetBody returns the raw response body bytes
func (r SetAccountStatusResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SetAccountStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetAccountStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SetAccountStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListAuditEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AuditEventList
	// ApplicationProblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationProblemJSON401 *Unauthorized
	// ApplicationProblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationProblemJSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListAuditEventsResponse) GetJSON200() *AuditEventList {
	return r.JSON200
}

// GetApplicationProblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ListAuditEventsResponse) GetApplicationProblemJSON401() *Unauthorized {
	return r.ApplicationProblemJSON401
}

// GetApplicationProblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r ListAuditEventsResponse) GetApplicationProblemJSON500() *InternalError {
	return r.ApplicationProblemJSON500
}

// GetBody returns the raw response body bytes
func (r ListAuditEventsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListAuditEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAuditEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListAuditEventsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateAdjustmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JournalEntry
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *JournalEntry
	// ApplicationProblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationProblemJSON400 *BadRequest
	// ApplicationProblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationProblemJSON401 *Unauthorized
	// ApplicationProblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationProblemJSON404 *NotFound
	// ApplicationProblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationProblemJSON422 *Problem
	// ApplicationProblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationProblemJSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateAdjustmentResponse) GetJSON200() *JournalEntry {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateAdjustmentResponse) GetJSON201() *JournalEntry {
	return r.JSON201
}

// GetApplicationProblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r CreateAdjustmentResponse) GetApplicationProblemJSON400() *BadRequest {
	return r.ApplicationProblemJSON400
}

// GetApplicationProblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r CreateAdjustmentResponse) GetApplicationProblemJSON401() *Unauthorized {
	return r.ApplicationProblemJSON401
}

// GetApplicationProblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r CreateAdjustmentResponse) GetApplicationProblemJSON404() *NotFound {
	return r.ApplicationProblemJSON404
}

// GetApplicationProblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r CreateAdjustmentResponse) GetApplicationProblemJSON422() *Problem {
	return r.ApplicationProblemJSON422
}

// GetApplicationProblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r CreateAdjustmentResponse) GetApplicationProblemJSON500() *InternalError {
	return r.ApplicationProblemJSON500
}

// GetBody returns the raw response body bytes
func (r CreateAdjustmentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateAdjustmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAdjustmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateAdjustmentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListEntriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JournalEntryList
	// ApplicationProblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationProblemJSON401 *Unauthorized
	// ApplicationProblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationProblemJSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListEntriesResponse) GetJSON200() *JournalEntryList {
	return r.JSON200
}

// GetApplicationProblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ListEntriesResponse) GetApplicationProblemJSON401() *Unauthorized {
	return r.ApplicationProblemJSON401
}

// GetApplicationProblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r ListEntriesResponse) GetApplicationProblemJSON500() *InternalError {
	return r.ApplicationProblemJSON500
}

// GetBody returns the raw response body bytes
func (r ListEntriesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListEntriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEntriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListEntriesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetTrialBalanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *TrialBalance
	// ApplicationProblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationProblemJSON401 *Unauthorized
	// ApplicationProblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationProblemJSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetTrialBalanceResponse) GetJSON200() *TrialBalance {
	return r.JSON200
}

// GetApplicationProblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetTrialBalanceResponse) GetApplicationProblemJSON401() *Unauthorized {
	return r.ApplicationProblemJSON401
}

// GetApplicationProblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetTrialBalanceResponse) GetApplicationProblemJSON500() *InternalError {
	return r.ApplicationProblemJSON500
}

// GetBody returns the raw response body bytes
func (r GetTrialBalanceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetTrialBalanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTrialBalanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTrialBalanceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListAccountsWithResponse List ledger accounts
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /admin/v1/accounts (the `ListAccounts` operationId).
func (c *ClientWithResponses) ListAccountsWithResponse(ctx context.Context, params *ListAccountsParams, reqEditors ...RequestEditorFn) (*ListAccountsResponse, error) {
	rsp, err := c.ListAccounts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAccountsResponse(rsp)
}

// CreateAccountWithBodyWithResponse Open a spot account
//
// Phase 2 dev/admin path; from Phase 3 registration opens the account.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /admin/v1/accounts (the `CreateAccount` operationId).
func (c *ClientWithResponses) CreateAccountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAccountResponse, error) {
	rsp, err := c.CreateAccountWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAccountResponse(rsp)
}

// CreateAccountWithResponse Open a spot account
//
// Phase 2 dev/admin path; from Phase 3 registration opens the account.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /admin/v1/accounts (the `CreateAccount` operationId).
func (c *ClientWithResponses) CreateAccountWithResponse(ctx context.Context, body CreateAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAccountResponse, error) {
	rsp, err := c.CreateAccount(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAccountResponse(rsp)
}

// GetAccountWithResponse Get one account
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /admin/v1/accounts/{id} (the `GetAccount` operationId).
func (c *ClientWithResponses) GetAccountWithResponse(ctx context.Context, id AccountID, reqEditors ...RequestEditorFn) (*GetAccountResponse, error) {
	rsp, err := c.GetAccount(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountResponse(rsp)
}

// GetAccountBalancesWithResponse Cached balances of a spot account
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /admin/v1/accounts/{id}/balances (the `GetAccountBalances` operationId).
func (c *ClientWithResponses) GetAccountBalancesWithResponse(ctx context.Context, id AccountID, reqEditors ...RequestEditorFn) (*GetAccountBalancesResponse, error) {
	rsp, err := c.GetAccountBalances(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountBalancesResponse(rsp)
}

// SetAccountStatusWithBodyWithResponse Freeze or reactivate an account
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /admin/v1/accounts/{id}/status (the `SetAccountStatus` operationId).
func (c *ClientWithResponses) SetAccountStatusWithBodyWithResponse(ctx context.Context, id AccountID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetAccountStatusResponse, error) {
	rsp, err := c.SetAccountStatusWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetAccountStatusResponse(rsp)
}

// SetAccountStatusWithResponse Freeze or reactivate an account
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /admin/v1/accounts/{id}/status (the `SetAccountStatus` operationId).
func (c *ClientWithResponses) SetAccountStatusWithResponse(ctx context.Context, id AccountID, body SetAccountStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*SetAccountStatusResponse, error) {
	rsp, err := c.SetAccountStatus(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetAccountStatusResponse(rsp)
}

// ListAuditEventsWithResponse Audit trail, newest first
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /admin/v1/audit-events (the `ListAuditEvents` operationId).
func (c *ClientWithResponses) ListAuditEventsWithResponse(ctx context.Context, params *ListAuditEventsParams, reqEditors ...RequestEditorFn) (*ListAuditEventsResponse, error) {
	rsp, err := c.ListAuditEvents(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAuditEventsResponse(rsp)
}

// CreateAdjustmentWithBodyWithResponse Post a manual adjustment against the external account
//
// `credit` adds to the account's available balance (the development
// faucet, or a correction in the user's favour); `debit` removes from it.
// A reason is mandatory and the call is recorded in the audit trail.
// Repeating the same `idempotency_key` returns the original entry with
// HTTP 200 instead of 201.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /admin/v1/ledger/adjustments (the `CreateAdjustment` operationId).
func (c *ClientWithResponses) CreateAdjustmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAdjustmentResponse, error) {
	rsp, err := c.CreateAdjustmentWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAdjustmentResponse(rsp)
}

// CreateAdjustmentWithResponse Post a manual adjustment against the external account
//
// `credit` adds to the account's available balance (the development
// faucet, or a correction in the user's favour); `debit` removes from it.
// A reason is mandatory and the call is recorded in the audit trail.
// Repeating the same `idempotency_key` returns the original entry with
// HTTP 200 instead of 201.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /admin/v1/ledger/adjustments (the `CreateAdjustment` operationId).
func (c *ClientWithResponses) CreateAdjustmentWithResponse(ctx context.Context, body CreateAdjustmentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAdjustmentResponse, error) {
	rsp, err := c.CreateAdjustment(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAdjustmentResponse(rsp)
}

// ListEntriesWithResponse Journal entries with postings, newest first
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /admin/v1/ledger/entries (the `ListEntries` operationId).
func (c *ClientWithResponses) ListEntriesWithResponse(ctx context.Context, params *ListEntriesParams, reqEditors ...RequestEditorFn) (*ListEntriesResponse, error) {
	rsp, err := c.ListEntries(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEntriesResponse(rsp)
}

// GetTrialBalanceWithResponse Trial balance per asset (must be zero) and house account balances
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /admin/v1/ledger/trial-balance (the `GetTrialBalance` operationId).
func (c *ClientWithResponses) GetTrialBalanceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTrialBalanceResponse, error) {
	rsp, err := c.GetTrialBalance(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTrialBalanceResponse(rsp)
}

// ParseListAccountsResponse parses an HTTP response from a ListAccountsWithResponse call
func ParseListAccountsResponse(rsp *http.Response) (*ListAccountsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAccountsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AccountList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON500 = &dest

	}

	return response, nil
}

// ParseCreateAccountResponse parses an HTTP response from a CreateAccountWithResponse call
func ParseCreateAccountResponse(rsp *http.Response) (*CreateAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Account
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetAccountResponse parses an HTTP response from a GetAccountWithResponse call
func ParseGetAccountResponse(rsp *http.Response) (*GetAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Account
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetAccountBalancesResponse parses an HTTP response from a GetAccountBalancesWithResponse call
func ParseGetAccountBalancesResponse(rsp *http.Response) (*GetAccountBalancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountBalancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BalanceList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON500 = &dest

	}

	return response, nil
}

// ParseSetAccountStatusResponse parses an HTTP response from a SetAccountStatusWithResponse call
func ParseSetAccountStatusResponse(rsp *http.Response) (*SetAccountStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetAccountStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Account
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON500 = &dest

	}

	return response, nil
}

// ParseListAuditEventsResponse parses an HTTP response from a ListAuditEventsWithResponse call
func ParseListAuditEventsResponse(rsp *http.Response) (*ListAuditEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAuditEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuditEventList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON500 = &dest

	}

	return response, nil
}

// ParseCreateAdjustmentResponse parses an HTTP response from a CreateAdjustmentWithResponse call
func ParseCreateAdjustmentResponse(rsp *http.Response) (*CreateAdjustmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAdjustmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JournalEntry
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest JournalEntry
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON500 = &dest

	}

	return response, nil
}

// ParseListEntriesResponse parses an HTTP response from a ListEntriesWithResponse call
func ParseListEntriesResponse(rsp *http.Response) (*ListEntriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEntriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JournalEntryList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetTrialBalanceResponse parses an HTTP response from a GetTrialBalanceWithResponse call
func ParseGetTrialBalanceResponse(rsp *http.Response) (*GetTrialBalanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTrialBalanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TrialBalance
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationProblemJSON500 = &dest

	}

	return response, nil
}
